// Code generated by nuzur go-code-gen. DO NOT EDIT.

package team

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nuzur/nem/core/entity/connection"
	"github.com/nuzur/nem/core/entity/entity"
	"github.com/nuzur/nem/core/entity/enviorment"
	"github.com/nuzur/nem/core/entity/object_store"
	"github.com/nuzur/nem/core/entity/review_config"
	"github.com/nuzur/nem/core/entity/store"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type Team struct {
	UUID          uuid.UUID                    `json:"uuid"`
	Version       int64                        `json:"version"`
	Name          string                       `json:"name"`
	Enviorments   []enviorment.Enviorment      `json:"enviorments"`
	ReviewConfigs []review_config.ReviewConfig `json:"review_configs"`
	Stores        []store.Store                `json:"stores"`
	Connections   []connection.Connection      `json:"connections"`
	ObjectStores  []object_store.ObjectStore   `json:"object_stores"`
	DefaultEntity entity.Entity                `json:"default_entity"`
	OwnerUUID     uuid.UUID                    `json:"owner_uuid"`
	Status        enums.TeamStatus             `json:"status"`
	CreatedAt     time.Time                    `json:"created_at"`
	UpdatedAt     time.Time                    `json:"updated_at"`
	CreatedByUUID uuid.UUID                    `json:"created_by_uuid"`
	UpdatedByUUID uuid.UUID                    `json:"updated_by_uuid"`
}

func (e Team) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Team) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func TeamFromJSON(data json.RawMessage) Team {
	entity := Team{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error TeamFromJSON: %v\n", err2)
		}
	}
	return entity
}

func TeamSliceFromJSON(data json.RawMessage) []Team {
	entity := []Team{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Team{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Team{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error TeamSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Team) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TeamToJSON: %v\n", err)
	}
	return res
}

func TeamToJSON(e Team) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TeamToJSON: %v\n", err)
	}
	return res
}

func TeamSliceToJSON(e []Team) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TeamSliceToJSON: %v\n", err)
	}
	return res
}
