// Code generated by nuzur go-code-gen. DO NOT EDIT.

package team

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"

	"github.com/nuzur/nem/core/entity/connection"
	"github.com/nuzur/nem/core/entity/entity"
	"github.com/nuzur/nem/core/entity/enviorment"
	"github.com/nuzur/nem/core/entity/object_store"
	"github.com/nuzur/nem/core/entity/review_config"
	"github.com/nuzur/nem/core/entity/store"
)

func (e Team) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":            entitytypes.StringFieldType,
		"version":         entitytypes.IntFieldType,
		"name":            entitytypes.StringFieldType,
		"enviorments":     entitytypes.SingleDependantEntityFieldType,
		"review_configs":  entitytypes.SingleDependantEntityFieldType,
		"stores":          entitytypes.SingleDependantEntityFieldType,
		"connections":     entitytypes.SingleDependantEntityFieldType,
		"object_stores":   entitytypes.SingleDependantEntityFieldType,
		"default_entity":  entitytypes.MultiDependantEntityFieldType,
		"owner_uuid":      entitytypes.StringFieldType,
		"status":          entitytypes.SingleEnumFieldType,
		"created_at":      entitytypes.TimestampFieldType,
		"updated_at":      entitytypes.TimestampFieldType,
		"created_by_uuid": entitytypes.StringFieldType,
		"updated_by_uuid": entitytypes.StringFieldType,
	}
}

func (e Team) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "version")
	res = append(res, "name")
	res = append(res, "enviorments")
	res = append(res, "review_configs")
	res = append(res, "stores")
	res = append(res, "connections")
	res = append(res, "object_stores")
	res = append(res, "default_entity")
	res = append(res, "owner_uuid")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "created_by_uuid")
	res = append(res, "updated_by_uuid")

	return res
}

func (e Team) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["enviorments"] = enviorment.Enviorment{}.FieldIdentifierToTypeMap()
	res["review_configs"] = review_config.ReviewConfig{}.FieldIdentifierToTypeMap()
	res["stores"] = store.Store{}.FieldIdentifierToTypeMap()
	res["connections"] = connection.Connection{}.FieldIdentifierToTypeMap()
	res["object_stores"] = object_store.ObjectStore{}.FieldIdentifierToTypeMap()
	res["default_entity"] = entity.Entity{}.FieldIdentifierToTypeMap()
	return res
}

func (e Team) EntityIdentifier() string {
	return "team"
}

func (e Team) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e Team) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
