// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ChangeRequestChangeType -json
type ChangeRequestChangeType int64

const (
	CHANGE_REQUEST_CHANGE_TYPE_INVALID = iota
	CHANGE_REQUEST_CHANGE_TYPE_PROJECT_DATA
	CHANGE_REQUEST_CHANGE_TYPE_PROJECT_VERSION
)

func (e ChangeRequestChangeType) ToInt64() int64 {
	return int64(e)
}

func (e ChangeRequestChangeType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ChangeRequestChangeTypeFromString(in string) ChangeRequestChangeType {
	switch in {
	case "invalid":
		return CHANGE_REQUEST_CHANGE_TYPE_INVALID
	case "project_data":
		return CHANGE_REQUEST_CHANGE_TYPE_PROJECT_DATA
	case "project_version":
		return CHANGE_REQUEST_CHANGE_TYPE_PROJECT_VERSION
	}
	return CHANGE_REQUEST_CHANGE_TYPE_INVALID
}

func ChangeRequestChangeTypeFromPointerString(in *string) ChangeRequestChangeType {
	if in == nil {
		return CHANGE_REQUEST_CHANGE_TYPE_INVALID
	}
	return ChangeRequestChangeTypeFromString(*in)
}

func (e ChangeRequestChangeType) String() string {
	switch e {
	case CHANGE_REQUEST_CHANGE_TYPE_INVALID:
		return "invalid"
	case CHANGE_REQUEST_CHANGE_TYPE_PROJECT_DATA:
		return "project_data"
	case CHANGE_REQUEST_CHANGE_TYPE_PROJECT_VERSION:
		return "project_version"
	}

	return "invalid"
}

func (e ChangeRequestChangeType) StringPtr() *string {
	val := e.String()
	return &val
}

func ChangeRequestChangeTypeSliceToJSON(in []ChangeRequestChangeType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ChangeRequestChangeType slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToChangeRequestChangeTypeSlice(in json.RawMessage) []ChangeRequestChangeType {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ChangeRequestChangeType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ChangeRequestChangeType{}
	for _, r := range res {
		finalRes = append(finalRes, ChangeRequestChangeType(r))
	}
	return finalRes
}
