// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ConnectionDbType -json
type ConnectionDbType int64

const (
	CONNECTION_DB_TYPE_INVALID = iota
	CONNECTION_DB_TYPE_MYSQL
	CONNECTION_DB_TYPE_POSTGRES
)

func (e ConnectionDbType) ToInt64() int64 {
	return int64(e)
}

func (e ConnectionDbType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ConnectionDbTypeFromString(in string) ConnectionDbType {
	switch in {
	case "invalid":
		return CONNECTION_DB_TYPE_INVALID
	case "mysql":
		return CONNECTION_DB_TYPE_MYSQL
	case "postgres":
		return CONNECTION_DB_TYPE_POSTGRES
	}
	return CONNECTION_DB_TYPE_INVALID
}

func ConnectionDbTypeFromPointerString(in *string) ConnectionDbType {
	if in == nil {
		return CONNECTION_DB_TYPE_INVALID
	}
	return ConnectionDbTypeFromString(*in)
}

func (e ConnectionDbType) String() string {
	switch e {
	case CONNECTION_DB_TYPE_INVALID:
		return "invalid"
	case CONNECTION_DB_TYPE_MYSQL:
		return "mysql"
	case CONNECTION_DB_TYPE_POSTGRES:
		return "postgres"
	}

	return "invalid"
}

func (e ConnectionDbType) StringPtr() *string {
	val := e.String()
	return &val
}

func ConnectionDbTypeSliceToJSON(in []ConnectionDbType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ConnectionDbType slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToConnectionDbTypeSlice(in json.RawMessage) []ConnectionDbType {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ConnectionDbType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ConnectionDbType{}
	for _, r := range res {
		finalRes = append(finalRes, ConnectionDbType(r))
	}
	return finalRes
}
