// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=DeploymentMode -json
type DeploymentMode int64

const (
	DEPLOYMENT_MODE_INVALID = iota
	DEPLOYMENT_MODE_FULL_APP
	DEPLOYMENT_MODE_DB_ONLY
)

func (e DeploymentMode) ToInt64() int64 {
	return int64(e)
}

func (e DeploymentMode) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func DeploymentModeFromString(in string) DeploymentMode {
	switch in {
	case "invalid":
		return DEPLOYMENT_MODE_INVALID
	case "full_app":
		return DEPLOYMENT_MODE_FULL_APP
	case "db_only":
		return DEPLOYMENT_MODE_DB_ONLY
	}
	return DEPLOYMENT_MODE_INVALID
}

func DeploymentModeFromPointerString(in *string) DeploymentMode {
	if in == nil {
		return DEPLOYMENT_MODE_INVALID
	}
	return DeploymentModeFromString(*in)
}

func (e DeploymentMode) String() string {
	switch e {
	case DEPLOYMENT_MODE_INVALID:
		return "invalid"
	case DEPLOYMENT_MODE_FULL_APP:
		return "full_app"
	case DEPLOYMENT_MODE_DB_ONLY:
		return "db_only"
	}

	return "invalid"
}

func (e DeploymentMode) StringPtr() *string {
	val := e.String()
	return &val
}

func DeploymentModeSliceToJSON(in []DeploymentMode) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling DeploymentMode slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToDeploymentModeSlice(in json.RawMessage) []DeploymentMode {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling DeploymentMode slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []DeploymentMode{}
	for _, r := range res {
		finalRes = append(finalRes, DeploymentMode(r))
	}
	return finalRes
}
