// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=EntityType -json
type EntityType int64

const (
	ENTITY_TYPE_INVALID = iota
	ENTITY_TYPE_STANDALONE
	ENTITY_TYPE_DEPENDENT
)

func (e EntityType) ToInt64() int64 {
	return int64(e)
}

func (e EntityType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func EntityTypeFromString(in string) EntityType {
	switch in {
	case "invalid":
		return ENTITY_TYPE_INVALID
	case "standalone":
		return ENTITY_TYPE_STANDALONE
	case "dependent":
		return ENTITY_TYPE_DEPENDENT
	}
	return ENTITY_TYPE_INVALID
}

func EntityTypeFromPointerString(in *string) EntityType {
	if in == nil {
		return ENTITY_TYPE_INVALID
	}
	return EntityTypeFromString(*in)
}

func (e EntityType) String() string {
	switch e {
	case ENTITY_TYPE_INVALID:
		return "invalid"
	case ENTITY_TYPE_STANDALONE:
		return "standalone"
	case ENTITY_TYPE_DEPENDENT:
		return "dependent"
	}

	return "invalid"
}

func (e EntityType) StringPtr() *string {
	val := e.String()
	return &val
}

func EntityTypeSliceToJSON(in []EntityType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling EntityType slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToEntityTypeSlice(in json.RawMessage) []EntityType {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling EntityType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []EntityType{}
	for _, r := range res {
		finalRes = append(finalRes, EntityType(r))
	}
	return finalRes
}
