// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=EntityVersionConfigType -json
type EntityVersionConfigType int64

const (
	ENTITY_VERSION_CONFIG_TYPE_INVALID = iota
	ENTITY_VERSION_CONFIG_TYPE_FIELD
	ENTITY_VERSION_CONFIG_TYPE_ENTITY
)

func (e EntityVersionConfigType) ToInt64() int64 {
	return int64(e)
}

func (e EntityVersionConfigType) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func EntityVersionConfigTypeFromString(in string) EntityVersionConfigType {
	switch in {
	case "invalid":
		return ENTITY_VERSION_CONFIG_TYPE_INVALID
	case "field":
		return ENTITY_VERSION_CONFIG_TYPE_FIELD
	case "entity":
		return ENTITY_VERSION_CONFIG_TYPE_ENTITY
	}
	return ENTITY_VERSION_CONFIG_TYPE_INVALID
}

func EntityVersionConfigTypeFromPointerString(in *string) EntityVersionConfigType {
	if in == nil {
		return ENTITY_VERSION_CONFIG_TYPE_INVALID
	}
	return EntityVersionConfigTypeFromString(*in)
}

func (e EntityVersionConfigType) String() string {
	switch e {
	case ENTITY_VERSION_CONFIG_TYPE_INVALID:
		return "invalid"
	case ENTITY_VERSION_CONFIG_TYPE_FIELD:
		return "field"
	case ENTITY_VERSION_CONFIG_TYPE_ENTITY:
		return "entity"
	}

	return "invalid"
}

func (e EntityVersionConfigType) StringPtr() *string {
	val := e.String()
	return &val
}

func EntityVersionConfigTypeSliceToJSON(in []EntityVersionConfigType) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling EntityVersionConfigType slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToEntityVersionConfigTypeSlice(in json.RawMessage) []EntityVersionConfigType {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling EntityVersionConfigType slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []EntityVersionConfigType{}
	for _, r := range res {
		finalRes = append(finalRes, EntityVersionConfigType(r))
	}
	return finalRes
}
