// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ExtensionExecutionStatus -json
type ExtensionExecutionStatus int64

const (
	EXTENSION_EXECUTION_STATUS_INVALID = iota
	EXTENSION_EXECUTION_STATUS_INPROGRESS
	EXTENSION_EXECUTION_STATUS_SUCCEEDED
	EXTENSION_EXECUTION_STATUS_FAILED
	EXTENSION_EXECUTION_STATUS_CANCELLED
	EXTENSION_EXECUTION_STATUS_QUEUED
)

func (e ExtensionExecutionStatus) ToInt64() int64 {
	return int64(e)
}

func (e ExtensionExecutionStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ExtensionExecutionStatusFromString(in string) ExtensionExecutionStatus {
	switch in {
	case "invalid":
		return EXTENSION_EXECUTION_STATUS_INVALID
	case "inprogress":
		return EXTENSION_EXECUTION_STATUS_INPROGRESS
	case "succeeded":
		return EXTENSION_EXECUTION_STATUS_SUCCEEDED
	case "failed":
		return EXTENSION_EXECUTION_STATUS_FAILED
	case "cancelled":
		return EXTENSION_EXECUTION_STATUS_CANCELLED
	case "queued":
		return EXTENSION_EXECUTION_STATUS_QUEUED
	}
	return EXTENSION_EXECUTION_STATUS_INVALID
}

func ExtensionExecutionStatusFromPointerString(in *string) ExtensionExecutionStatus {
	if in == nil {
		return EXTENSION_EXECUTION_STATUS_INVALID
	}
	return ExtensionExecutionStatusFromString(*in)
}

func (e ExtensionExecutionStatus) String() string {
	switch e {
	case EXTENSION_EXECUTION_STATUS_INVALID:
		return "invalid"
	case EXTENSION_EXECUTION_STATUS_INPROGRESS:
		return "inprogress"
	case EXTENSION_EXECUTION_STATUS_SUCCEEDED:
		return "succeeded"
	case EXTENSION_EXECUTION_STATUS_FAILED:
		return "failed"
	case EXTENSION_EXECUTION_STATUS_CANCELLED:
		return "cancelled"
	case EXTENSION_EXECUTION_STATUS_QUEUED:
		return "queued"
	}

	return "invalid"
}

func (e ExtensionExecutionStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ExtensionExecutionStatusSliceToJSON(in []ExtensionExecutionStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ExtensionExecutionStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToExtensionExecutionStatusSlice(in json.RawMessage) []ExtensionExecutionStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ExtensionExecutionStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ExtensionExecutionStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ExtensionExecutionStatus(r))
	}
	return finalRes
}
