// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ExtensionVersionExecutionMode -json
type ExtensionVersionExecutionMode int64

const (
	EXTENSION_VERSION_EXECUTION_MODE_INVALID = iota
	EXTENSION_VERSION_EXECUTION_MODE_MANUAL
	EXTENSION_VERSION_EXECUTION_MODE_AUTOMATIC
)

func (e ExtensionVersionExecutionMode) ToInt64() int64 {
	return int64(e)
}

func (e ExtensionVersionExecutionMode) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ExtensionVersionExecutionModeFromString(in string) ExtensionVersionExecutionMode {
	switch in {
	case "invalid":
		return EXTENSION_VERSION_EXECUTION_MODE_INVALID
	case "manual":
		return EXTENSION_VERSION_EXECUTION_MODE_MANUAL
	case "automatic":
		return EXTENSION_VERSION_EXECUTION_MODE_AUTOMATIC
	}
	return EXTENSION_VERSION_EXECUTION_MODE_INVALID
}

func ExtensionVersionExecutionModeFromPointerString(in *string) ExtensionVersionExecutionMode {
	if in == nil {
		return EXTENSION_VERSION_EXECUTION_MODE_INVALID
	}
	return ExtensionVersionExecutionModeFromString(*in)
}

func (e ExtensionVersionExecutionMode) String() string {
	switch e {
	case EXTENSION_VERSION_EXECUTION_MODE_INVALID:
		return "invalid"
	case EXTENSION_VERSION_EXECUTION_MODE_MANUAL:
		return "manual"
	case EXTENSION_VERSION_EXECUTION_MODE_AUTOMATIC:
		return "automatic"
	}

	return "invalid"
}

func (e ExtensionVersionExecutionMode) StringPtr() *string {
	val := e.String()
	return &val
}

func ExtensionVersionExecutionModeSliceToJSON(in []ExtensionVersionExecutionMode) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ExtensionVersionExecutionMode slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToExtensionVersionExecutionModeSlice(in json.RawMessage) []ExtensionVersionExecutionMode {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ExtensionVersionExecutionMode slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ExtensionVersionExecutionMode{}
	for _, r := range res {
		finalRes = append(finalRes, ExtensionVersionExecutionMode(r))
	}
	return finalRes
}
