// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ExtensionVersionStatus -json
type ExtensionVersionStatus int64

const (
	EXTENSION_VERSION_STATUS_INVALID = iota
	EXTENSION_VERSION_STATUS_ACTIVE
	EXTENSION_VERSION_STATUS_DISABLED
)

func (e ExtensionVersionStatus) ToInt64() int64 {
	return int64(e)
}

func (e ExtensionVersionStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ExtensionVersionStatusFromString(in string) ExtensionVersionStatus {
	switch in {
	case "invalid":
		return EXTENSION_VERSION_STATUS_INVALID
	case "active":
		return EXTENSION_VERSION_STATUS_ACTIVE
	case "disabled":
		return EXTENSION_VERSION_STATUS_DISABLED
	}
	return EXTENSION_VERSION_STATUS_INVALID
}

func ExtensionVersionStatusFromPointerString(in *string) ExtensionVersionStatus {
	if in == nil {
		return EXTENSION_VERSION_STATUS_INVALID
	}
	return ExtensionVersionStatusFromString(*in)
}

func (e ExtensionVersionStatus) String() string {
	switch e {
	case EXTENSION_VERSION_STATUS_INVALID:
		return "invalid"
	case EXTENSION_VERSION_STATUS_ACTIVE:
		return "active"
	case EXTENSION_VERSION_STATUS_DISABLED:
		return "disabled"
	}

	return "invalid"
}

func (e ExtensionVersionStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ExtensionVersionStatusSliceToJSON(in []ExtensionVersionStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ExtensionVersionStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToExtensionVersionStatusSlice(in json.RawMessage) []ExtensionVersionStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ExtensionVersionStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ExtensionVersionStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ExtensionVersionStatus(r))
	}
	return finalRes
}
