// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ExtensionVersionReviewStatus -json
type ExtensionVersionReviewStatus int64

const (
	EXTENSION_VERSION_REVIEW_STATUS_INVALID = iota
	EXTENSION_VERSION_REVIEW_STATUS_DRAFT
	EXTENSION_VERSION_REVIEW_STATUS_IN_REVIEW
	EXTENSION_VERSION_REVIEW_STATUS_APPROVED
	EXTENSION_VERSION_REVIEW_STATUS_REJECTED
	EXTENSION_VERSION_REVIEW_STATUS_PUBLISHED
)

func (e ExtensionVersionReviewStatus) ToInt64() int64 {
	return int64(e)
}

func (e ExtensionVersionReviewStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ExtensionVersionReviewStatusFromString(in string) ExtensionVersionReviewStatus {
	switch in {
	case "invalid":
		return EXTENSION_VERSION_REVIEW_STATUS_INVALID
	case "draft":
		return EXTENSION_VERSION_REVIEW_STATUS_DRAFT
	case "in_review":
		return EXTENSION_VERSION_REVIEW_STATUS_IN_REVIEW
	case "approved":
		return EXTENSION_VERSION_REVIEW_STATUS_APPROVED
	case "rejected":
		return EXTENSION_VERSION_REVIEW_STATUS_REJECTED
	case "published":
		return EXTENSION_VERSION_REVIEW_STATUS_PUBLISHED
	}
	return EXTENSION_VERSION_REVIEW_STATUS_INVALID
}

func ExtensionVersionReviewStatusFromPointerString(in *string) ExtensionVersionReviewStatus {
	if in == nil {
		return EXTENSION_VERSION_REVIEW_STATUS_INVALID
	}
	return ExtensionVersionReviewStatusFromString(*in)
}

func (e ExtensionVersionReviewStatus) String() string {
	switch e {
	case EXTENSION_VERSION_REVIEW_STATUS_INVALID:
		return "invalid"
	case EXTENSION_VERSION_REVIEW_STATUS_DRAFT:
		return "draft"
	case EXTENSION_VERSION_REVIEW_STATUS_IN_REVIEW:
		return "in_review"
	case EXTENSION_VERSION_REVIEW_STATUS_APPROVED:
		return "approved"
	case EXTENSION_VERSION_REVIEW_STATUS_REJECTED:
		return "rejected"
	case EXTENSION_VERSION_REVIEW_STATUS_PUBLISHED:
		return "published"
	}

	return "invalid"
}

func (e ExtensionVersionReviewStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ExtensionVersionReviewStatusSliceToJSON(in []ExtensionVersionReviewStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ExtensionVersionReviewStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToExtensionVersionReviewStatusSlice(in json.RawMessage) []ExtensionVersionReviewStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ExtensionVersionReviewStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ExtensionVersionReviewStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ExtensionVersionReviewStatus(r))
	}
	return finalRes
}
