// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=FieldStatus -json
type FieldStatus int64

const (
	FIELD_STATUS_INVALID = iota
	FIELD_STATUS_ACTIVE
	FIELD_STATUS_INACTIVE
)

func (e FieldStatus) ToInt64() int64 {
	return int64(e)
}

func (e FieldStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func FieldStatusFromString(in string) FieldStatus {
	switch in {
	case "invalid":
		return FIELD_STATUS_INVALID
	case "active":
		return FIELD_STATUS_ACTIVE
	case "inactive":
		return FIELD_STATUS_INACTIVE
	}
	return FIELD_STATUS_INVALID
}

func FieldStatusFromPointerString(in *string) FieldStatus {
	if in == nil {
		return FIELD_STATUS_INVALID
	}
	return FieldStatusFromString(*in)
}

func (e FieldStatus) String() string {
	switch e {
	case FIELD_STATUS_INVALID:
		return "invalid"
	case FIELD_STATUS_ACTIVE:
		return "active"
	case FIELD_STATUS_INACTIVE:
		return "inactive"
	}

	return "invalid"
}

func (e FieldStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func FieldStatusSliceToJSON(in []FieldStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling FieldStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToFieldStatusSlice(in json.RawMessage) []FieldStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling FieldStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []FieldStatus{}
	for _, r := range res {
		finalRes = append(finalRes, FieldStatus(r))
	}
	return finalRes
}
