// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=FieldPiiConfigMaskStrategy -json
type FieldPiiConfigMaskStrategy int64

const (
	FIELD_PII_CONFIG_MASK_STRATEGY_INVALID = iota
	FIELD_PII_CONFIG_MASK_STRATEGY_FULL
	FIELD_PII_CONFIG_MASK_STRATEGY_PARTIAL
	FIELD_PII_CONFIG_MASK_STRATEGY_EMAIL
	FIELD_PII_CONFIG_MASK_STRATEGY_LAST4
	FIELD_PII_CONFIG_MASK_STRATEGY_CUSTOM
)

func (e FieldPiiConfigMaskStrategy) ToInt64() int64 {
	return int64(e)
}

func (e FieldPiiConfigMaskStrategy) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func FieldPiiConfigMaskStrategyFromString(in string) FieldPiiConfigMaskStrategy {
	switch in {
	case "invalid":
		return FIELD_PII_CONFIG_MASK_STRATEGY_INVALID
	case "full":
		return FIELD_PII_CONFIG_MASK_STRATEGY_FULL
	case "partial":
		return FIELD_PII_CONFIG_MASK_STRATEGY_PARTIAL
	case "email":
		return FIELD_PII_CONFIG_MASK_STRATEGY_EMAIL
	case "last4":
		return FIELD_PII_CONFIG_MASK_STRATEGY_LAST4
	case "custom":
		return FIELD_PII_CONFIG_MASK_STRATEGY_CUSTOM
	}
	return FIELD_PII_CONFIG_MASK_STRATEGY_INVALID
}

func FieldPiiConfigMaskStrategyFromPointerString(in *string) FieldPiiConfigMaskStrategy {
	if in == nil {
		return FIELD_PII_CONFIG_MASK_STRATEGY_INVALID
	}
	return FieldPiiConfigMaskStrategyFromString(*in)
}

func (e FieldPiiConfigMaskStrategy) String() string {
	switch e {
	case FIELD_PII_CONFIG_MASK_STRATEGY_INVALID:
		return "invalid"
	case FIELD_PII_CONFIG_MASK_STRATEGY_FULL:
		return "full"
	case FIELD_PII_CONFIG_MASK_STRATEGY_PARTIAL:
		return "partial"
	case FIELD_PII_CONFIG_MASK_STRATEGY_EMAIL:
		return "email"
	case FIELD_PII_CONFIG_MASK_STRATEGY_LAST4:
		return "last4"
	case FIELD_PII_CONFIG_MASK_STRATEGY_CUSTOM:
		return "custom"
	}

	return "invalid"
}

func (e FieldPiiConfigMaskStrategy) StringPtr() *string {
	val := e.String()
	return &val
}

func FieldPiiConfigMaskStrategySliceToJSON(in []FieldPiiConfigMaskStrategy) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling FieldPiiConfigMaskStrategy slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToFieldPiiConfigMaskStrategySlice(in json.RawMessage) []FieldPiiConfigMaskStrategy {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling FieldPiiConfigMaskStrategy slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []FieldPiiConfigMaskStrategy{}
	for _, r := range res {
		finalRes = append(finalRes, FieldPiiConfigMaskStrategy(r))
	}
	return finalRes
}
