// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=LocalAgentStatus -json
type LocalAgentStatus int64

const (
	LOCAL_AGENT_STATUS_INVALID = iota
	LOCAL_AGENT_STATUS_ONLINE
	LOCAL_AGENT_STATUS_OFFLINE
	LOCAL_AGENT_STATUS_REVOKED
)

func (e LocalAgentStatus) ToInt64() int64 {
	return int64(e)
}

func (e LocalAgentStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func LocalAgentStatusFromString(in string) LocalAgentStatus {
	switch in {
	case "invalid":
		return LOCAL_AGENT_STATUS_INVALID
	case "online":
		return LOCAL_AGENT_STATUS_ONLINE
	case "offline":
		return LOCAL_AGENT_STATUS_OFFLINE
	case "revoked":
		return LOCAL_AGENT_STATUS_REVOKED
	}
	return LOCAL_AGENT_STATUS_INVALID
}

func LocalAgentStatusFromPointerString(in *string) LocalAgentStatus {
	if in == nil {
		return LOCAL_AGENT_STATUS_INVALID
	}
	return LocalAgentStatusFromString(*in)
}

func (e LocalAgentStatus) String() string {
	switch e {
	case LOCAL_AGENT_STATUS_INVALID:
		return "invalid"
	case LOCAL_AGENT_STATUS_ONLINE:
		return "online"
	case LOCAL_AGENT_STATUS_OFFLINE:
		return "offline"
	case LOCAL_AGENT_STATUS_REVOKED:
		return "revoked"
	}

	return "invalid"
}

func (e LocalAgentStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func LocalAgentStatusSliceToJSON(in []LocalAgentStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling LocalAgentStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToLocalAgentStatusSlice(in json.RawMessage) []LocalAgentStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling LocalAgentStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []LocalAgentStatus{}
	for _, r := range res {
		finalRes = append(finalRes, LocalAgentStatus(r))
	}
	return finalRes
}
