// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ProjectExtensionStatus -json
type ProjectExtensionStatus int64

const (
	PROJECT_EXTENSION_STATUS_INVALID = iota
	PROJECT_EXTENSION_STATUS_ACTIVE
	PROJECT_EXTENSION_STATUS_DISABLED
)

func (e ProjectExtensionStatus) ToInt64() int64 {
	return int64(e)
}

func (e ProjectExtensionStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ProjectExtensionStatusFromString(in string) ProjectExtensionStatus {
	switch in {
	case "invalid":
		return PROJECT_EXTENSION_STATUS_INVALID
	case "active":
		return PROJECT_EXTENSION_STATUS_ACTIVE
	case "disabled":
		return PROJECT_EXTENSION_STATUS_DISABLED
	}
	return PROJECT_EXTENSION_STATUS_INVALID
}

func ProjectExtensionStatusFromPointerString(in *string) ProjectExtensionStatus {
	if in == nil {
		return PROJECT_EXTENSION_STATUS_INVALID
	}
	return ProjectExtensionStatusFromString(*in)
}

func (e ProjectExtensionStatus) String() string {
	switch e {
	case PROJECT_EXTENSION_STATUS_INVALID:
		return "invalid"
	case PROJECT_EXTENSION_STATUS_ACTIVE:
		return "active"
	case PROJECT_EXTENSION_STATUS_DISABLED:
		return "disabled"
	}

	return "invalid"
}

func (e ProjectExtensionStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ProjectExtensionStatusSliceToJSON(in []ProjectExtensionStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ProjectExtensionStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToProjectExtensionStatusSlice(in json.RawMessage) []ProjectExtensionStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ProjectExtensionStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ProjectExtensionStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ProjectExtensionStatus(r))
	}
	return finalRes
}
