// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ProjectVersionReviewStatus -json
type ProjectVersionReviewStatus int64

const (
	PROJECT_VERSION_REVIEW_STATUS_INVALID = iota
	PROJECT_VERSION_REVIEW_STATUS_DRAFT
	PROJECT_VERSION_REVIEW_STATUS_IN_REVIEW
	PROJECT_VERSION_REVIEW_STATUS_APPROVED
	PROJECT_VERSION_REVIEW_STATUS_REJECTED
	PROJECT_VERSION_REVIEW_STATUS_PUBLISHED
)

func (e ProjectVersionReviewStatus) ToInt64() int64 {
	return int64(e)
}

func (e ProjectVersionReviewStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ProjectVersionReviewStatusFromString(in string) ProjectVersionReviewStatus {
	switch in {
	case "invalid":
		return PROJECT_VERSION_REVIEW_STATUS_INVALID
	case "draft":
		return PROJECT_VERSION_REVIEW_STATUS_DRAFT
	case "in_review":
		return PROJECT_VERSION_REVIEW_STATUS_IN_REVIEW
	case "approved":
		return PROJECT_VERSION_REVIEW_STATUS_APPROVED
	case "rejected":
		return PROJECT_VERSION_REVIEW_STATUS_REJECTED
	case "published":
		return PROJECT_VERSION_REVIEW_STATUS_PUBLISHED
	}
	return PROJECT_VERSION_REVIEW_STATUS_INVALID
}

func ProjectVersionReviewStatusFromPointerString(in *string) ProjectVersionReviewStatus {
	if in == nil {
		return PROJECT_VERSION_REVIEW_STATUS_INVALID
	}
	return ProjectVersionReviewStatusFromString(*in)
}

func (e ProjectVersionReviewStatus) String() string {
	switch e {
	case PROJECT_VERSION_REVIEW_STATUS_INVALID:
		return "invalid"
	case PROJECT_VERSION_REVIEW_STATUS_DRAFT:
		return "draft"
	case PROJECT_VERSION_REVIEW_STATUS_IN_REVIEW:
		return "in_review"
	case PROJECT_VERSION_REVIEW_STATUS_APPROVED:
		return "approved"
	case PROJECT_VERSION_REVIEW_STATUS_REJECTED:
		return "rejected"
	case PROJECT_VERSION_REVIEW_STATUS_PUBLISHED:
		return "published"
	}

	return "invalid"
}

func (e ProjectVersionReviewStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ProjectVersionReviewStatusSliceToJSON(in []ProjectVersionReviewStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ProjectVersionReviewStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToProjectVersionReviewStatusSlice(in json.RawMessage) []ProjectVersionReviewStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ProjectVersionReviewStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ProjectVersionReviewStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ProjectVersionReviewStatus(r))
	}
	return finalRes
}
