// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=ProjectStatus -json
type ProjectStatus int64

const (
	PROJECT_STATUS_INVALID = iota
	PROJECT_STATUS_ACTIVE
	PROJECT_STATUS_DISABLED
)

func (e ProjectStatus) ToInt64() int64 {
	return int64(e)
}

func (e ProjectStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func ProjectStatusFromString(in string) ProjectStatus {
	switch in {
	case "invalid":
		return PROJECT_STATUS_INVALID
	case "active":
		return PROJECT_STATUS_ACTIVE
	case "disabled":
		return PROJECT_STATUS_DISABLED
	}
	return PROJECT_STATUS_INVALID
}

func ProjectStatusFromPointerString(in *string) ProjectStatus {
	if in == nil {
		return PROJECT_STATUS_INVALID
	}
	return ProjectStatusFromString(*in)
}

func (e ProjectStatus) String() string {
	switch e {
	case PROJECT_STATUS_INVALID:
		return "invalid"
	case PROJECT_STATUS_ACTIVE:
		return "active"
	case PROJECT_STATUS_DISABLED:
		return "disabled"
	}

	return "invalid"
}

func (e ProjectStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func ProjectStatusSliceToJSON(in []ProjectStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling ProjectStatus slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToProjectStatusSlice(in json.RawMessage) []ProjectStatus {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling ProjectStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []ProjectStatus{}
	for _, r := range res {
		finalRes = append(finalRes, ProjectStatus(r))
	}
	return finalRes
}
