// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=VisibilityRoles -json
type VisibilityRoles int64

const (
	VISIBILITY_ROLES_INVALID = iota
	VISIBILITY_ROLES_ADMIN
	VISIBILITY_ROLES_DEVELOPER
	VISIBILITY_ROLES_DATA_MANAGER
	VISIBILITY_ROLES_DATA_ANALYST
	VISIBILITY_ROLES_VIEWER
)

func (e VisibilityRoles) ToInt64() int64 {
	return int64(e)
}

func (e VisibilityRoles) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func VisibilityRolesFromString(in string) VisibilityRoles {
	switch in {
	case "invalid":
		return VISIBILITY_ROLES_INVALID
	case "admin":
		return VISIBILITY_ROLES_ADMIN
	case "developer":
		return VISIBILITY_ROLES_DEVELOPER
	case "data_manager":
		return VISIBILITY_ROLES_DATA_MANAGER
	case "data_analyst":
		return VISIBILITY_ROLES_DATA_ANALYST
	case "viewer":
		return VISIBILITY_ROLES_VIEWER
	}
	return VISIBILITY_ROLES_INVALID
}

func VisibilityRolesFromPointerString(in *string) VisibilityRoles {
	if in == nil {
		return VISIBILITY_ROLES_INVALID
	}
	return VisibilityRolesFromString(*in)
}

func (e VisibilityRoles) String() string {
	switch e {
	case VISIBILITY_ROLES_INVALID:
		return "invalid"
	case VISIBILITY_ROLES_ADMIN:
		return "admin"
	case VISIBILITY_ROLES_DEVELOPER:
		return "developer"
	case VISIBILITY_ROLES_DATA_MANAGER:
		return "data_manager"
	case VISIBILITY_ROLES_DATA_ANALYST:
		return "data_analyst"
	case VISIBILITY_ROLES_VIEWER:
		return "viewer"
	}

	return "invalid"
}

func (e VisibilityRoles) StringPtr() *string {
	val := e.String()
	return &val
}

func VisibilityRolesSliceToJSON(in []VisibilityRoles) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling VisibilityRoles slice to json: %v", err)
		return json.RawMessage{}
	}
	return jr
}

func JSONToVisibilityRolesSlice(in json.RawMessage) []VisibilityRoles {
	res := []int64{}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling VisibilityRoles slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []VisibilityRoles{}
	for _, r := range res {
		finalRes = append(finalRes, VisibilityRoles(r))
	}
	return finalRes
}
