// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/change_request/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchChangeRequestByStatus(
	ctx context.Context,
	req types.FetchChangeRequestByStatusRequest,
	opts ...Option,
) (types.FetchChangeRequestByStatusResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchChangeRequestByStatus:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchChangeRequestByStatusResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchChangeRequestByStatus(
				ctx,
				nemdb.FetchChangeRequestByStatusParams{
					Status: req.Status.ToInt64(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchChangeRequestByStatusResponse{}, err
			}
			return types.FetchChangeRequestByStatusResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchChangeRequestByStatusResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchChangeRequestByStatusResponse{}, fetchErr
	}
	result := v.(types.FetchChangeRequestByStatusResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
