// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/change_request/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchChangeRequestByOwnerUuid(
	ctx context.Context,
	req types.FetchChangeRequestByOwnerUuidRequest,
	opts ...Option,
) (types.FetchChangeRequestByOwnerUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchChangeRequestByOwnerUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchChangeRequestByOwnerUuidResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchChangeRequestByOwnerUuid(
				ctx,
				nemdb.FetchChangeRequestByOwnerUuidParams{
					OwnerUUID: req.OwnerUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchChangeRequestByOwnerUuidResponse{}, err
			}
			return types.FetchChangeRequestByOwnerUuidResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchChangeRequestByOwnerUuidResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchChangeRequestByOwnerUuidResponse{}, fetchErr
	}
	result := v.(types.FetchChangeRequestByOwnerUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
