// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/change_request/types"
)

func (m *module) FetchChangeRequestByUuid(
	ctx context.Context,
	req types.FetchChangeRequestByUuidRequest,
	opts ...Option,
) (types.FetchChangeRequestByUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchChangeRequestByUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchChangeRequestByUuidResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchChangeRequestByUuid(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchChangeRequestByUuidResponse{}, err
		}
		return types.FetchChangeRequestByUuidResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchChangeRequestByUuidResponse{}, err
	}
	result := v.(types.FetchChangeRequestByUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
