// Code generated by nuzur go-code-gen. DO NOT EDIT.

package ai_usage

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type AiUsage struct {
	UUID               uuid.UUID             `json:"uuid"`
	UserUUID           uuid.UUID             `json:"user_uuid"`
	ProjectUUID        uuid.UUID             `json:"project_uuid"`
	ProjectVersionUUID uuid.UUID             `json:"project_version_uuid"`
	UserPrompt         string                `json:"user_prompt"`
	Step               string                `json:"step"`
	Context            enums.AiUsageContext  `json:"context"`
	Provider           enums.AiUsageProvider `json:"provider"`
	InputTokens        int64                 `json:"input_tokens"`
	OutputTokens       int64                 `json:"output_tokens"`
	Status             enums.AiUsageStatus   `json:"status"`
	CreatedAt          time.Time             `json:"created_at"`
	UpdatedAt          time.Time             `json:"updated_at"`
	CreatedByUUID      uuid.UUID             `json:"created_by_uuid"`
	UpdatedByUUID      uuid.UUID             `json:"updated_by_uuid"`
}

func (e AiUsage) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e AiUsage) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func AiUsageFromJSON(data json.RawMessage) AiUsage {
	entity := AiUsage{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error AiUsageFromJSON: %v\n", err2)
		}
	}
	return entity
}

func AiUsageSliceFromJSON(data json.RawMessage) []AiUsage {
	entity := []AiUsage{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []AiUsage{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := AiUsage{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error AiUsageSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e AiUsage) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AiUsageToJSON: %v\n", err)
	}
	return res
}

func AiUsageToJSON(e AiUsage) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AiUsageToJSON: %v\n", err)
	}
	return res
}

func AiUsageSliceToJSON(e []AiUsage) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AiUsageSliceToJSON: %v\n", err)
	}
	return res
}
