// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/extension_version"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchExtensionVersionByExtensionUUIDRequest struct {
	ExtensionUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchExtensionVersionByExtensionUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("extension_uuid", r.ExtensionUUID.String())

	return nil
}

type FetchExtensionVersionByExtensionUUIDResponse struct {
	Results []main_entity.ExtensionVersion
}
