// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/extension_version"

	"github.com/nuzur/nem/enums"
	"go.uber.org/zap/zapcore"
)

type FetchExtensionVersionByStatusRequest struct {
	Status enums.ExtensionVersionStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchExtensionVersionByStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchExtensionVersionByStatusResponse struct {
	Results []main_entity.ExtensionVersion
}
