// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/project/types"
)

func (m *module) FetchProjectByUuid(
	ctx context.Context,
	req types.FetchProjectByUuidRequest,
	opts ...Option,
) (types.FetchProjectByUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchProjectByUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchProjectByUuidResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchProjectByUuid(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchProjectByUuidResponse{}, err
		}
		return types.FetchProjectByUuidResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchProjectByUuidResponse{}, err
	}
	result := v.(types.FetchProjectByUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
