// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/project/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchProjectByUpdatedByUUID(
	ctx context.Context,
	req types.FetchProjectByUpdatedByUUIDRequest,
	opts ...Option,
) (types.FetchProjectByUpdatedByUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchProjectByUpdatedByUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchProjectByUpdatedByUUIDResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchProjectByUpdatedByUUID(
				ctx,
				nemdb.FetchProjectByUpdatedByUUIDParams{
					UpdatedByUUID: req.UpdatedByUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchProjectByUpdatedByUUIDResponse{}, err
			}
			return types.FetchProjectByUpdatedByUUIDResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchProjectByUpdatedByUUIDResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchProjectByUpdatedByUUIDResponse{}, fetchErr
	}
	result := v.(types.FetchProjectByUpdatedByUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
