// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project

import (
	"context"

	"github.com/nuzur/nem/core/module/project/types"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/project_extension"

	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	params.Version = time.Now().Unix()

	_, err := qtx.InsertProject(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.Project.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) nemdb.InsertProjectParams {
	return nemdb.InsertProjectParams{
		UUID: req.Project.UUID.String(),

		Version: req.Project.Version,

		Name: req.Project.Name,

		Description: req.Project.Description,

		Tags: mapper.SliceToJSON(req.Project.Tags),

		URL: req.Project.URL,

		OwnerUUID: req.Project.OwnerUUID.String(),

		TeamUUID: req.Project.TeamUUID.String(),

		AccessType: req.Project.AccessType.ToInt64(),

		ProjectExtensions: project_extension.ProjectExtensionSliceToJSON(req.Project.ProjectExtensions),

		Status: req.Project.Status.ToInt64(),

		CreatedAt: req.Project.CreatedAt,

		UpdatedAt: req.Project.UpdatedAt,

		CreatedByUUID: req.Project.CreatedByUUID.String(),

		UpdatedByUUID: req.Project.UpdatedByUUID.String(),
	}
}
