// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project

import (
	"context"
	"errors"

	"github.com/nuzur/nem/core/module/project/types"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/project_extension"

	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchProjectByUUIDForUpdate(ctx,
		req.Project.UUID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	if existing[0].Version != req.Project.Version {
		err := errors.New("upsert version conflict")

		return types.UpsertResponse{}, err
	}

	// Bump the optimistic-concurrency token. It is a unix-second timestamp, but two
	// writes in the same second would otherwise mint the same token and weaken the
	// compare-and-swap above (a second concurrent writer could pass the check and
	// silently overwrite). Force it strictly greater than the row we just read so
	// the token is monotonic even under sub-second contention.
	{
		newVersion := time.Now().Unix()
		if newVersion <= existing[0].Version {
			newVersion = existing[0].Version + 1
		}
		req.Project.Version = newVersion
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.Project.UpdatedAt = time.Now()

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateProject(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.Project.UUID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) nemdb.UpdateProjectParams {
	return nemdb.UpdateProjectParams{
		UUID: req.Project.UUID.String(),

		Version: req.Project.Version,

		Name: req.Project.Name,

		Description: req.Project.Description,

		Tags: mapper.SliceToJSON(req.Project.Tags),

		URL: req.Project.URL,

		OwnerUUID: req.Project.OwnerUUID.String(),

		TeamUUID: req.Project.TeamUUID.String(),

		AccessType: req.Project.AccessType.ToInt64(),

		ProjectExtensions: project_extension.ProjectExtensionSliceToJSON(req.Project.ProjectExtensions),

		Status: req.Project.Status.ToInt64(),

		CreatedAt: req.Project.CreatedAt,

		UpdatedAt: req.Project.UpdatedAt,

		CreatedByUUID: req.Project.CreatedByUUID.String(),

		UpdatedByUUID: req.Project.UpdatedByUUID.String(),
	}
}
