// Code generated by nuzur go-code-gen. DO NOT EDIT.

package db_type_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this DbTypeConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e DbTypeConfig) Validate() error {
	c := validation.NewCollector()
	if validation.IsZeroEntity(e.Postgres) {
		c.Require("db_type_config.postgres")
	} else {
		c.Merge("db_type_config.postgres", e.Postgres.Validate())
	}
	if validation.IsZeroEntity(e.Mysql) {
		c.Require("db_type_config.mysql")
	} else {
		c.Merge("db_type_config.mysql", e.Mysql.Validate())
	}

	return c.Result()
}
