// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_datetime_config

import (
	"encoding/json"
	"log"

	"github.com/guregu/null/v6"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FieldTypeDatetimeConfig struct {
	EnforceFuture   bool        `json:"enforce_future"`
	EnforcePast     bool        `json:"enforce_past"`
	DisplayTimezone null.String `json:"display_timezone"`
	StorageTimezone null.String `json:"storage_timezone"`
}

func (e FieldTypeDatetimeConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FieldTypeDatetimeConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FieldTypeDatetimeConfigFromJSON(data json.RawMessage) FieldTypeDatetimeConfig {
	entity := FieldTypeDatetimeConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FieldTypeDatetimeConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FieldTypeDatetimeConfigSliceFromJSON(data json.RawMessage) []FieldTypeDatetimeConfig {
	entity := []FieldTypeDatetimeConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FieldTypeDatetimeConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FieldTypeDatetimeConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FieldTypeDatetimeConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FieldTypeDatetimeConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeDatetimeConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeDatetimeConfigToJSON(e FieldTypeDatetimeConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeDatetimeConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeDatetimeConfigSliceToJSON(e []FieldTypeDatetimeConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeDatetimeConfigSliceToJSON: %v\n", err)
	}
	return res
}
