// Code generated by nuzur go-code-gen. DO NOT EDIT.

package index

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this Index against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Index) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("index.uuid")
	}
	if e.Identifier == "" {
		c.Require("index.identifier")
	} else {
		c.Field("index.identifier", validation.String(e.Identifier, 0, 255, ""))

	}
	if e.Type.ToInt64() == 0 {
		c.Require("index.type")
	} else {
		c.Field("index.type", validation.EnumMember(e.Type.ToInt64(), []int64{0, 1, 2, 3, 4}, "index_type"))

	}
	if len(e.Fields) == 0 {
		c.Require("index.fields")
	} else {
		for i, item := range e.Fields {
			c.Merge(validation.Index("index.fields", i), item.Validate())
		}

	}
	if e.Status.ToInt64() == 0 {
		c.Require("index.status")
	} else {
		c.Field("index.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "index_status"))

	}
	if e.CreatedAt.IsZero() {
		c.Require("index.created_at")
	}
	if e.UpdatedAt.IsZero() {
		c.Require("index.updated_at")
	}
	if e.CreatedByUUID.IsNil() {
		c.Require("index.created_by_uuid")
	}
	if e.UpdatedByUUID.IsNil() {
		c.Require("index.updated_by_uuid")
	}

	return c.Result()
}
