// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/user_project"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	UserProject main_entity.UserProject
}

type UpsertResponse struct {
	UUID uuid.UUID
}
