// Code generated by nuzur go-code-gen. DO NOT EDIT.

package index_field

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e IndexField) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"field_uuid": entitytypes.StringFieldType,
		"priority":   entitytypes.IntFieldType,
		"order":      entitytypes.SingleEnumFieldType,
		"length":     entitytypes.IntFieldType,
	}
}

func (e IndexField) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "field_uuid")
	res = append(res, "priority")
	res = append(res, "order")
	res = append(res, "length")

	return res
}

func (e IndexField) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e IndexField) EntityIdentifier() string {
	return "index_field"
}

func (e IndexField) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e IndexField) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
