// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project_extension

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e ProjectExtension) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":                        entitytypes.StringFieldType,
		"extension_uuid":              entitytypes.StringFieldType,
		"extension_version_uuid":      entitytypes.StringFieldType,
		"configuration_entity_values": entitytypes.StringFieldType,
		"blocking":                    entitytypes.BooleanFieldType,
		"status":                      entitytypes.SingleEnumFieldType,
		"created_at":                  entitytypes.TimestampFieldType,
		"updated_at":                  entitytypes.TimestampFieldType,
		"created_by_uuid":             entitytypes.StringFieldType,
		"updated_by_uuid":             entitytypes.StringFieldType,
	}
}

func (e ProjectExtension) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "extension_uuid")
	res = append(res, "extension_version_uuid")
	res = append(res, "configuration_entity_values")
	res = append(res, "blocking")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "created_by_uuid")
	res = append(res, "updated_by_uuid")

	return res
}

func (e ProjectExtension) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e ProjectExtension) EntityIdentifier() string {
	return "project_extension"
}

func (e ProjectExtension) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e ProjectExtension) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
