// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_phone_config

import (
	"encoding/json"
	"log"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FieldTypePhoneConfig struct {
	AllowCountries   []string `json:"allow_countries"`
	ExcludeCountries []string `json:"exclude_countries"`
}

func (e FieldTypePhoneConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FieldTypePhoneConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FieldTypePhoneConfigFromJSON(data json.RawMessage) FieldTypePhoneConfig {
	entity := FieldTypePhoneConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FieldTypePhoneConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FieldTypePhoneConfigSliceFromJSON(data json.RawMessage) []FieldTypePhoneConfig {
	entity := []FieldTypePhoneConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FieldTypePhoneConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FieldTypePhoneConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FieldTypePhoneConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FieldTypePhoneConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypePhoneConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypePhoneConfigToJSON(e FieldTypePhoneConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypePhoneConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypePhoneConfigSliceToJSON(e []FieldTypePhoneConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypePhoneConfigSliceToJSON: %v\n", err)
	}
	return res
}
