// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_version

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/extension_version/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchExtensionVersionByStatus(
	ctx context.Context,
	req types.FetchExtensionVersionByStatusRequest,
	opts ...Option,
) (types.FetchExtensionVersionByStatusResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchExtensionVersionByStatus:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchExtensionVersionByStatusResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchExtensionVersionByStatus(
				ctx,
				nemdb.FetchExtensionVersionByStatusParams{
					Status: req.Status.ToInt64(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchExtensionVersionByStatusResponse{}, err
			}
			return types.FetchExtensionVersionByStatusResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchExtensionVersionByStatusResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchExtensionVersionByStatusResponse{}, fetchErr
	}
	result := v.(types.FetchExtensionVersionByStatusResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
