// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_version

import (
	"context"
	"database/sql"
	"fmt"
	main_entity "github.com/nuzur/nem/core/entity/extension_version"
	"github.com/nuzur/nem/core/module/extension_version/types"
	repogen "github.com/nuzur/nem/core/repository/gen"

	"go.uber.org/zap"
	"slices"
)

func (m *module) List(ctx context.Context,
	request types.ListRequest,
	opts ...Option) (types.ListResponse, error) {

	reqPlusOne := request
	reqPlusOne.PageSize = request.PageSize + 1

	query, err := m.repository.BuildListEntityQuery(
		ctx,
		reqPlusOne,
		main_entity.ExtensionVersion{},
		false)
	if err != nil {

		return types.ListResponse{}, err
	}

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("ListExtensionVersion:%v", request)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.ListResponse), nil
		}
	}

	v, listErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		var rows *sql.Rows
		rows, err = m.repository.DB.QueryContext(ctx, query)
		if err != nil {

			m.logger.Error("error in executing query for ListExtensionVersion", zap.String("query", query), zap.Error(err))
			return types.ListResponse{}, err
		}
		defer rows.Close()
		var scanGetters []func(*repogen.ExtensionVersion) any
		if len(request.GetIncludeFields()) > 0 {
			for _, f := range listFields {
				if slices.Contains(request.GetIncludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else if len(request.GetExcludeFields()) > 0 {
			for _, f := range listFields {
				if !slices.Contains(request.GetExcludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else {
			for _, f := range listFields {
				scanGetters = append(scanGetters, listFieldRegistry[f])
			}
		}

		var items []repogen.ExtensionVersion
		for rows.Next() {
			var i repogen.ExtensionVersion
			fields := make([]any, 0, len(scanGetters))
			for _, getter := range scanGetters {
				fields = append(fields, getter(&i))
			}
			if err := rows.Scan(fields...); err != nil {

				return types.ListResponse{}, err
			}
			items = append(items, i)
		}
		if err := rows.Close(); err != nil {

			return types.ListResponse{}, err
		}
		if err := rows.Err(); err != nil {

			return types.ListResponse{}, err
		}

		hasNextPage := false
		if len(items) > int(request.PageSize) {
			hasNextPage = true
			items = items[:request.PageSize]
		}

		return types.ListResponse{
			ExtensionVersion: mapModelsToEntities(items),
			HasNextPage:      hasNextPage,
		}, nil
	})
	if listErr != nil {
		return types.ListResponse{}, listErr
	}
	listResponse := v.(types.ListResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, listResponse, 0)
	}
	return listResponse, nil
}

var listFields = []string{

	"uuid",

	"version",

	"extension_uuid",

	"display_version",

	"description",

	"repository_tag",

	"configuration_entity",

	"execution_mode",

	"review_status",

	"status",

	"created_at",

	"updated_at",

	"created_by_uuid",

	"updated_by_uuid",
}

var listFieldRegistry = map[string]func(*repogen.ExtensionVersion) any{

	"uuid": func(i *repogen.ExtensionVersion) any { return &i.UUID },

	"version": func(i *repogen.ExtensionVersion) any { return &i.Version },

	"extension_uuid": func(i *repogen.ExtensionVersion) any { return &i.ExtensionUUID },

	"display_version": func(i *repogen.ExtensionVersion) any { return &i.DisplayVersion },

	"description": func(i *repogen.ExtensionVersion) any { return &i.Description },

	"repository_tag": func(i *repogen.ExtensionVersion) any { return &i.RepositoryTag },

	"configuration_entity": func(i *repogen.ExtensionVersion) any { return &i.ConfigurationEntity },

	"execution_mode": func(i *repogen.ExtensionVersion) any { return &i.ExecutionMode },

	"review_status": func(i *repogen.ExtensionVersion) any { return &i.ReviewStatus },

	"status": func(i *repogen.ExtensionVersion) any { return &i.Status },

	"created_at": func(i *repogen.ExtensionVersion) any { return &i.CreatedAt },

	"updated_at": func(i *repogen.ExtensionVersion) any { return &i.UpdatedAt },

	"created_by_uuid": func(i *repogen.ExtensionVersion) any { return &i.CreatedByUUID },

	"updated_by_uuid": func(i *repogen.ExtensionVersion) any { return &i.UpdatedByUUID },
}
