// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_version

import (
	"context"
	"errors"

	"github.com/nuzur/nem/core/module/extension_version/types"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"time"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchExtensionVersionByUUIDForUpdate(ctx,
		req.ExtensionVersion.UUID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	if existing[0].Version != req.ExtensionVersion.Version {
		err := errors.New("upsert version conflict")

		return types.UpsertResponse{}, err
	}

	req.ExtensionVersion.Version = time.Now().Unix()

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateExtensionVersion(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.ExtensionVersion.UUID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) nemdb.UpdateExtensionVersionParams {
	return nemdb.UpdateExtensionVersionParams{
		UUID: req.ExtensionVersion.UUID.String(),

		Version: req.ExtensionVersion.Version,

		ExtensionUUID: req.ExtensionVersion.ExtensionUUID.String(),

		DisplayVersion: req.ExtensionVersion.DisplayVersion,

		Description: req.ExtensionVersion.Description,

		RepositoryTag: req.ExtensionVersion.RepositoryTag,

		ConfigurationEntity: req.ExtensionVersion.ConfigurationEntity,

		ExecutionMode: req.ExtensionVersion.ExecutionMode.ToInt64(),

		ReviewStatus: req.ExtensionVersion.ReviewStatus.ToInt64(),

		Status: req.ExtensionVersion.Status.ToInt64(),

		CreatedAt: req.ExtensionVersion.CreatedAt,

		UpdatedAt: req.ExtensionVersion.UpdatedAt,

		CreatedByUUID: req.ExtensionVersion.CreatedByUUID.String(),

		UpdatedByUUID: req.ExtensionVersion.UpdatedByUUID.String(),
	}
}
