// Code generated by nuzur go-code-gen. DO NOT EDIT.

package local_agent

import (
	"context"
	"database/sql"
	"fmt"
	main_entity "github.com/nuzur/nem/core/entity/local_agent"
	"github.com/nuzur/nem/core/module/local_agent/types"
	repogen "github.com/nuzur/nem/core/repository/gen"

	"go.uber.org/zap"
	"slices"
)

func (m *module) List(ctx context.Context,
	request types.ListRequest,
	opts ...Option) (types.ListResponse, error) {

	reqPlusOne := request
	reqPlusOne.PageSize = request.PageSize + 1

	query, err := m.repository.BuildListEntityQuery(
		ctx,
		reqPlusOne,
		main_entity.LocalAgent{},
		false)
	if err != nil {

		return types.ListResponse{}, err
	}

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("ListLocalAgent:%v", request)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.ListResponse), nil
		}
	}

	v, listErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		var rows *sql.Rows
		rows, err = m.repository.DB.QueryContext(ctx, query)
		if err != nil {

			m.logger.Error("error in executing query for ListLocalAgent", zap.String("query", query), zap.Error(err))
			return types.ListResponse{}, err
		}
		defer rows.Close()
		var scanGetters []func(*repogen.LocalAgent) any
		if len(request.GetIncludeFields()) > 0 {
			for _, f := range listFields {
				if slices.Contains(request.GetIncludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else if len(request.GetExcludeFields()) > 0 {
			for _, f := range listFields {
				if !slices.Contains(request.GetExcludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else {
			for _, f := range listFields {
				scanGetters = append(scanGetters, listFieldRegistry[f])
			}
		}

		var items []repogen.LocalAgent
		for rows.Next() {
			var i repogen.LocalAgent
			fields := make([]any, 0, len(scanGetters))
			for _, getter := range scanGetters {
				fields = append(fields, getter(&i))
			}
			if err := rows.Scan(fields...); err != nil {

				return types.ListResponse{}, err
			}
			items = append(items, i)
		}
		if err := rows.Close(); err != nil {

			return types.ListResponse{}, err
		}
		if err := rows.Err(); err != nil {

			return types.ListResponse{}, err
		}

		hasNextPage := false
		if len(items) > int(request.PageSize) {
			hasNextPage = true
			items = items[:request.PageSize]
		}

		return types.ListResponse{
			LocalAgent:  mapModelsToEntities(items),
			HasNextPage: hasNextPage,
		}, nil
	})
	if listErr != nil {
		return types.ListResponse{}, listErr
	}
	listResponse := v.(types.ListResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, listResponse, 0)
	}
	return listResponse, nil
}

var listFields = []string{

	"uuid",

	"user_uuid",

	"token_hash",

	"machine_name",

	"os",

	"cli_version",

	"connections",

	"status",

	"last_seen_at",

	"revoked_at",

	"created_at",

	"updated_at",

	"created_by_uuid",

	"updated_by_uuid",
}

var listFieldRegistry = map[string]func(*repogen.LocalAgent) any{

	"uuid": func(i *repogen.LocalAgent) any { return &i.UUID },

	"user_uuid": func(i *repogen.LocalAgent) any { return &i.UserUUID },

	"token_hash": func(i *repogen.LocalAgent) any { return &i.TokenHash },

	"machine_name": func(i *repogen.LocalAgent) any { return &i.MachineName },

	"os": func(i *repogen.LocalAgent) any { return &i.Os },

	"cli_version": func(i *repogen.LocalAgent) any { return &i.CliVersion },

	"connections": func(i *repogen.LocalAgent) any { return &i.Connections },

	"status": func(i *repogen.LocalAgent) any { return &i.Status },

	"last_seen_at": func(i *repogen.LocalAgent) any { return &i.LastSeenAt },

	"revoked_at": func(i *repogen.LocalAgent) any { return &i.RevokedAt },

	"created_at": func(i *repogen.LocalAgent) any { return &i.CreatedAt },

	"updated_at": func(i *repogen.LocalAgent) any { return &i.UpdatedAt },

	"created_by_uuid": func(i *repogen.LocalAgent) any { return &i.CreatedByUUID },

	"updated_by_uuid": func(i *repogen.LocalAgent) any { return &i.UpdatedByUUID },
}
