// Code generated by nuzur go-code-gen. DO NOT EDIT.

package object_store_s3_type_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this ObjectStoreS3TypeConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e ObjectStoreS3TypeConfig) Validate() error {
	c := validation.NewCollector()
	if e.Region.Valid && e.Region.String != "" {
		c.Field("object_store_s3_type_config.region", validation.String(e.Region.String, 0, 255, ""))

	}
	if e.Key.Valid && e.Key.String != "" {
		c.Field("object_store_s3_type_config.key", validation.String(e.Key.String, 0, 255, ""))

	}
	if e.Secret.Valid && e.Secret.String != "" {
		c.Field("object_store_s3_type_config.secret", validation.String(e.Secret.String, 0, 255, ""))

	}
	if e.Bucket.Valid && e.Bucket.String != "" {
		c.Field("object_store_s3_type_config.bucket", validation.String(e.Bucket.String, 0, 255, ""))

	}

	return c.Result()
}
