// Code generated by nuzur go-code-gen. DO NOT EDIT.

package object_store_s3_type_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e ObjectStoreS3TypeConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"region": entitytypes.StringFieldType,
		"key":    entitytypes.StringFieldType,
		"secret": entitytypes.StringFieldType,
		"bucket": entitytypes.StringFieldType,
	}
}

func (e ObjectStoreS3TypeConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "region")
	res = append(res, "key")
	res = append(res, "secret")
	res = append(res, "bucket")

	return res
}

func (e ObjectStoreS3TypeConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e ObjectStoreS3TypeConfig) EntityIdentifier() string {
	return "object_store_s3_type_config"
}

func (e ObjectStoreS3TypeConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e ObjectStoreS3TypeConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
