// Code generated by nuzur go-code-gen. DO NOT EDIT.

package main

import (
	"go.uber.org/config"
	"net/http"

	nemconfig "github.com/nuzur/nem/config"
	"github.com/nuzur/nem/core"
	"go.uber.org/fx"
	"go.uber.org/zap"

	pbserver "github.com/nuzur/nem/idl/server"

	auth "github.com/nuzur/nem/auth/keycloak"
)

func main() {
	fx.New(
		fx.Provide(
			zap.NewProduction,
			nemconfig.New,
			core.New,

			auth.New,
		),

		fx.Invoke(httpServer),

		fx.Invoke(pbserver.New),
	).Run()
}

func httpServer(config config.Provider, logger *zap.Logger) {
	// http port from config
	httpPort := config.Get("ports.http").String()

	go http.ListenAndServe(":"+httpPort, nil)

	logger.Info(`Serving HTTP on PORT: %s`, zap.String("port", httpPort))
}
