// Code generated by nuzur go-code-gen. DO NOT EDIT.

package entity_type_dependent_config

import (
	"encoding/json"
	"log"

	"github.com/nuzur/nem/core/entity/mapper"
)

type EntityTypeDependentConfig struct {
	ServiceSourceUUIDs json.RawMessage `json:"service_source_uuids"`
	EntitySourceUUIDs  json.RawMessage `json:"entity_source_uuids"`
}

func (e EntityTypeDependentConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e EntityTypeDependentConfig) PrimaryKeyValues() []string {
	return []string{}
}

func EntityTypeDependentConfigFromJSON(data json.RawMessage) EntityTypeDependentConfig {
	entity := EntityTypeDependentConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error EntityTypeDependentConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func EntityTypeDependentConfigSliceFromJSON(data json.RawMessage) []EntityTypeDependentConfig {
	entity := []EntityTypeDependentConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []EntityTypeDependentConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := EntityTypeDependentConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error EntityTypeDependentConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e EntityTypeDependentConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EntityTypeDependentConfigToJSON: %v\n", err)
	}
	return res
}

func EntityTypeDependentConfigToJSON(e EntityTypeDependentConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EntityTypeDependentConfigToJSON: %v\n", err)
	}
	return res
}

func EntityTypeDependentConfigSliceToJSON(e []EntityTypeDependentConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EntityTypeDependentConfigSliceToJSON: %v\n", err)
	}
	return res
}
