// Code generated by nuzur go-code-gen. DO NOT EDIT.

package entity_type_dependent_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this EntityTypeDependentConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e EntityTypeDependentConfig) Validate() error {
	c := validation.NewCollector()
	if len(e.ServiceSourceUUIDs) == 0 {
		c.Require("entity_type_dependent_config.service_source_uuids")
	}
	if len(e.ServiceSourceUUIDs) > 0 {
		c.Field("entity_type_dependent_config.service_source_uuids", validation.Unique(e.ServiceSourceUUIDs))

	}
	if len(e.EntitySourceUUIDs) == 0 {
		c.Require("entity_type_dependent_config.entity_source_uuids")
	}
	if len(e.EntitySourceUUIDs) > 0 {
		c.Field("entity_type_dependent_config.entity_source_uuids", validation.Unique(e.EntitySourceUUIDs))

	}

	return c.Result()
}
