// Code generated by nuzur go-code-gen. DO NOT EDIT.

package entity_type_dependent_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e EntityTypeDependentConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"service_source_uuids": entitytypes.RawJSONFieldType,
		"entity_source_uuids":  entitytypes.RawJSONFieldType,
	}
}

func (e EntityTypeDependentConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "service_source_uuids")
	res = append(res, "entity_source_uuids")

	return res
}

func (e EntityTypeDependentConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e EntityTypeDependentConfig) EntityIdentifier() string {
	return "entity_type_dependent_config"
}

func (e EntityTypeDependentConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e EntityTypeDependentConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
