// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_integer_config

import (
	"encoding/json"
	"log"

	"github.com/nuzur/nem/enums"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FieldTypeIntegerConfig struct {
	Size              enums.FieldTypeIntegerConfigSize `json:"size"`
	MinValue          int64                            `json:"min_value"`
	MinValueInclusive bool                             `json:"min_value_inclusive"`
	MaxValue          int64                            `json:"max_value"`
	MaxValueInclusive bool                             `json:"max_value_inclusive"`
	AllowNegatives    bool                             `json:"allow_negatives"`
	EnableLimits      bool                             `json:"enable_limits"`
}

func (e FieldTypeIntegerConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FieldTypeIntegerConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FieldTypeIntegerConfigFromJSON(data json.RawMessage) FieldTypeIntegerConfig {
	entity := FieldTypeIntegerConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FieldTypeIntegerConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FieldTypeIntegerConfigSliceFromJSON(data json.RawMessage) []FieldTypeIntegerConfig {
	entity := []FieldTypeIntegerConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FieldTypeIntegerConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FieldTypeIntegerConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FieldTypeIntegerConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FieldTypeIntegerConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeIntegerConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeIntegerConfigToJSON(e FieldTypeIntegerConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeIntegerConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeIntegerConfigSliceToJSON(e []FieldTypeIntegerConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeIntegerConfigSliceToJSON: %v\n", err)
	}
	return res
}
