// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_json_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this FieldTypeJSONConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e FieldTypeJSONConfig) Validate() error {
	c := validation.NewCollector()

	return c.Result()
}
