// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/deployment"

	"github.com/nuzur/nem/enums"
	"go.uber.org/zap/zapcore"
)

type FetchDeploymentByStatusRequest struct {
	Status enums.DeploymentStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchDeploymentByStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchDeploymentByStatusResponse struct {
	Results []main_entity.Deployment
}
