// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/deployment"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchDeploymentByUserUUIDAndHostAndIdentifierRequest struct {
	UserUUID   uuid.UUID
	Host       string
	Identifier string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchDeploymentByUserUUIDAndHostAndIdentifierRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("user_uuid", r.UserUUID.String())

	return nil
}

type FetchDeploymentByUserUUIDAndHostAndIdentifierResponse struct {
	Results []main_entity.Deployment
}
