// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/deployment"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchDeploymentByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchDeploymentByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchDeploymentByUUIDResponse struct {
	Results []main_entity.Deployment
}
