// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_connection

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this UserConnection against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e UserConnection) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("user_connection.uuid")
	}
	if e.UserUUID.IsNil() {
		c.Require("user_connection.user_uuid")
	}
	if e.ProjectUUID.IsNil() {
		c.Require("user_connection.project_uuid")
	}
	if e.Type.ToInt64() == 0 {
		c.Require("user_connection.type")
	} else {
		c.Field("user_connection.type", validation.EnumMember(e.Type.ToInt64(), []int64{0, 1, 2}, "user_connection_type"))

	}
	if validation.IsZeroEntity(e.TypeConfig) {
		c.Require("user_connection.type_config")
	} else {
		c.Merge("user_connection.type_config", e.TypeConfig.Validate())
	}
	if e.DbSchema == "" {
		c.Require("user_connection.db_schema")
	} else {
		c.Field("user_connection.db_schema", validation.String(e.DbSchema, 0, 255, ""))

	}
	for i, item := range e.Executions {
		c.Merge(validation.Index("user_connection.executions", i), item.Validate())
	}
	if e.Status.ToInt64() == 0 {
		c.Require("user_connection.status")
	} else {
		c.Field("user_connection.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "user_connection_status"))

	}

	return c.Result()
}
