// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_connection

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nuzur/nem/core/entity/user_connection_execution"
	"github.com/nuzur/nem/core/entity/user_connection_type_config"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type UserConnection struct {
	UUID               uuid.UUID                                            `json:"uuid"`
	UserUUID           uuid.UUID                                            `json:"user_uuid"`
	ProjectUUID        uuid.UUID                                            `json:"project_uuid"`
	ProjectVersionUUID *uuid.UUID                                           `json:"project_version_uuid"`
	Type               enums.UserConnectionType                             `json:"type"`
	TypeConfig         user_connection_type_config.UserConnectionTypeConfig `json:"type_config"`
	DbSchema           string                                               `json:"db_schema"`
	Executions         []user_connection_execution.UserConnectionExecution  `json:"executions"`
	Status             enums.UserConnectionStatus                           `json:"status"`
	CreatedAt          time.Time                                            `json:"created_at"`
	UpdatedAt          time.Time                                            `json:"updated_at"`
}

func (e UserConnection) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e UserConnection) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func UserConnectionFromJSON(data json.RawMessage) UserConnection {
	entity := UserConnection{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error UserConnectionFromJSON: %v\n", err2)
		}
	}
	return entity
}

func UserConnectionSliceFromJSON(data json.RawMessage) []UserConnection {
	entity := []UserConnection{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []UserConnection{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := UserConnection{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error UserConnectionSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e UserConnection) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserConnectionToJSON: %v\n", err)
	}
	return res
}

func UserConnectionToJSON(e UserConnection) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserConnectionToJSON: %v\n", err)
	}
	return res
}

func UserConnectionSliceToJSON(e []UserConnection) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserConnectionSliceToJSON: %v\n", err)
	}
	return res
}
