// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request_scope_config_local

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"

	"github.com/nuzur/nem/core/entity/mapper"
)

type ChangeRequestScopeConfigLocal struct {
	AgentUUID           uuid.UUID `json:"agent_uuid"`
	AgentConnectionUUID uuid.UUID `json:"agent_connection_uuid"`
}

func (e ChangeRequestScopeConfigLocal) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e ChangeRequestScopeConfigLocal) PrimaryKeyValues() []string {
	return []string{}
}

func ChangeRequestScopeConfigLocalFromJSON(data json.RawMessage) ChangeRequestScopeConfigLocal {
	entity := ChangeRequestScopeConfigLocal{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ChangeRequestScopeConfigLocalFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ChangeRequestScopeConfigLocalSliceFromJSON(data json.RawMessage) []ChangeRequestScopeConfigLocal {
	entity := []ChangeRequestScopeConfigLocal{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []ChangeRequestScopeConfigLocal{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := ChangeRequestScopeConfigLocal{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ChangeRequestScopeConfigLocalSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e ChangeRequestScopeConfigLocal) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ChangeRequestScopeConfigLocalToJSON: %v\n", err)
	}
	return res
}

func ChangeRequestScopeConfigLocalToJSON(e ChangeRequestScopeConfigLocal) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ChangeRequestScopeConfigLocalToJSON: %v\n", err)
	}
	return res
}

func ChangeRequestScopeConfigLocalSliceToJSON(e []ChangeRequestScopeConfigLocal) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ChangeRequestScopeConfigLocalSliceToJSON: %v\n", err)
	}
	return res
}
