// Code generated by nuzur go-code-gen. DO NOT EDIT.

package review_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this ReviewConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e ReviewConfig) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("review_config.uuid")
	}
	if len(e.ReviewUserRoles) == 0 {
		c.Require("review_config.review_user_roles")
	} else {
		for _, v := range e.ReviewUserRoles {
			c.Field("review_config.review_user_roles", validation.EnumMember(v.ToInt64(), []int64{0, 1, 2, 3, 4, 5}, "review_config_review_user_roles"))

		}

	}
	if len(e.ReviewUserUUIDs) == 0 {
		c.Require("review_config.review_user_uuids")
	}
	if len(e.ReviewUserUUIDs) > 0 {
		c.Field("review_config.review_user_uuids", validation.Unique(e.ReviewUserUUIDs))

	}
	c.Field("review_config.min_reviews", validation.Integer(e.MinReviews, false, 0, 0, false, false, false, false, 0, 0))
	if e.Status.ToInt64() == 0 {
		c.Require("review_config.status")
	} else {
		c.Field("review_config.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "review_config_status"))

	}
	if e.CreatedAt.IsZero() {
		c.Require("review_config.created_at")
	}
	if e.UpdatedAt.IsZero() {
		c.Require("review_config.updated_at")
	}
	if e.CreatedByUUID.IsNil() {
		c.Require("review_config.created_by_uuid")
	}
	if e.UpdatedByUUID.IsNil() {
		c.Require("review_config.updated_by_uuid")
	}

	return c.Result()
}
