// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/user_team"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	UserTeam main_entity.UserTeam
}

type UpsertResponse struct {
	UUID uuid.UUID
}
