// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_project_version

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/user_project_version/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchUserProjectVersionByUserUuid(
	ctx context.Context,
	req types.FetchUserProjectVersionByUserUuidRequest,
	opts ...Option,
) (types.FetchUserProjectVersionByUserUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchUserProjectVersionByUserUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchUserProjectVersionByUserUuidResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchUserProjectVersionByUserUuid(
				ctx,
				nemdb.FetchUserProjectVersionByUserUuidParams{
					UserUUID: req.UserUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchUserProjectVersionByUserUuidResponse{}, err
			}
			return types.FetchUserProjectVersionByUserUuidResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchUserProjectVersionByUserUuidResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchUserProjectVersionByUserUuidResponse{}, fetchErr
	}
	result := v.(types.FetchUserProjectVersionByUserUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
