// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_project_version

import (
	"context"

	"github.com/nuzur/nem/core/module/user_project_version/types"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"time"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	params.Version = time.Now().Unix()

	_, err := qtx.InsertUserProjectVersion(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.UserProjectVersion.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) nemdb.InsertUserProjectVersionParams {
	return nemdb.InsertUserProjectVersionParams{
		UUID: req.UserProjectVersion.UUID.String(),

		Version: req.UserProjectVersion.Version,

		ProjectVersionUUID: req.UserProjectVersion.ProjectVersionUUID.String(),

		UserUUID: req.UserProjectVersion.UserUUID.String(),

		Data: req.UserProjectVersion.Data,

		Status: req.UserProjectVersion.Status.ToInt64(),

		CreatedAt: req.UserProjectVersion.CreatedAt,

		UpdatedAt: req.UserProjectVersion.UpdatedAt,

		CreatedByUUID: req.UserProjectVersion.CreatedByUUID.String(),

		UpdatedByUUID: req.UserProjectVersion.UpdatedByUUID.String(),
	}
}
