// Code generated by nuzur go-code-gen. DO NOT EDIT.

package local_agent

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/core/entity/local_agent_connection"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type LocalAgent struct {
	UUID          uuid.UUID                                     `json:"uuid"`
	UserUUID      uuid.UUID                                     `json:"user_uuid"`
	TokenHash     null.String                                   `json:"token_hash"`
	MachineName   null.String                                   `json:"machine_name"`
	Os            null.String                                   `json:"os"`
	CliVersion    null.String                                   `json:"cli_version"`
	Connections   []local_agent_connection.LocalAgentConnection `json:"connections"`
	Status        enums.LocalAgentStatus                        `json:"status"`
	LastSeenAt    null.Time                                     `json:"last_seen_at"`
	RevokedAt     null.Time                                     `json:"revoked_at"`
	CreatedAt     time.Time                                     `json:"created_at"`
	UpdatedAt     time.Time                                     `json:"updated_at"`
	CreatedByUUID uuid.UUID                                     `json:"created_by_uuid"`
	UpdatedByUUID uuid.UUID                                     `json:"updated_by_uuid"`
}

func (e LocalAgent) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e LocalAgent) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func LocalAgentFromJSON(data json.RawMessage) LocalAgent {
	entity := LocalAgent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error LocalAgentFromJSON: %v\n", err2)
		}
	}
	return entity
}

func LocalAgentSliceFromJSON(data json.RawMessage) []LocalAgent {
	entity := []LocalAgent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []LocalAgent{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := LocalAgent{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error LocalAgentSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e LocalAgent) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error LocalAgentToJSON: %v\n", err)
	}
	return res
}

func LocalAgentToJSON(e LocalAgent) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error LocalAgentToJSON: %v\n", err)
	}
	return res
}

func LocalAgentSliceToJSON(e []LocalAgent) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error LocalAgentSliceToJSON: %v\n", err)
	}
	return res
}
