// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visibility

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e Visibility) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":               entitytypes.StringFieldType,
		"description":        entitytypes.StringFieldType,
		"organization_uuids": entitytypes.StringFieldType,
		"team_uuids":         entitytypes.StringFieldType,
		"user_uuids":         entitytypes.StringFieldType,
		"roles":              entitytypes.MultiEnumFieldType,
		"created_at":         entitytypes.TimestampFieldType,
		"updated_at":         entitytypes.TimestampFieldType,
		"created_by_uuid":    entitytypes.StringFieldType,
		"updated_by_uuid":    entitytypes.StringFieldType,
	}
}

func (e Visibility) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "description")
	res = append(res, "organization_uuids")
	res = append(res, "team_uuids")
	res = append(res, "user_uuids")
	res = append(res, "roles")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "created_by_uuid")
	res = append(res, "updated_by_uuid")

	return res
}

func (e Visibility) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Visibility) EntityIdentifier() string {
	return "visibility"
}

func (e Visibility) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e Visibility) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	res["organization_uuids"] = entitytypes.StringFieldType
	res["team_uuids"] = entitytypes.StringFieldType
	res["user_uuids"] = entitytypes.StringFieldType
	return res
}
