// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visibility

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this Visibility against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Visibility) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("visibility.uuid")
	}
	if e.Description.Valid && e.Description.String != "" {
		c.Field("visibility.description", validation.String(e.Description.String, 0, 255, ""))

	}
	if len(e.OrganizationUUIDs) == 0 {
		c.Require("visibility.organization_uuids")
	}
	if len(e.OrganizationUUIDs) > 0 {
		c.Field("visibility.organization_uuids", validation.Unique(e.OrganizationUUIDs))

	}
	if len(e.TeamUUIDs) == 0 {
		c.Require("visibility.team_uuids")
	}
	if len(e.TeamUUIDs) > 0 {
		c.Field("visibility.team_uuids", validation.Unique(e.TeamUUIDs))

	}
	if len(e.UserUUIDs) == 0 {
		c.Require("visibility.user_uuids")
	}
	if len(e.UserUUIDs) > 0 {
		c.Field("visibility.user_uuids", validation.Unique(e.UserUUIDs))

	}
	if len(e.Roles) == 0 {
		c.Require("visibility.roles")
	} else {
		for _, v := range e.Roles {
			c.Field("visibility.roles", validation.EnumMember(v.ToInt64(), []int64{0, 1, 2, 3, 4, 5}, "visibility_roles"))

		}

	}
	if e.CreatedAt.IsZero() {
		c.Require("visibility.created_at")
	}
	if e.UpdatedAt.IsZero() {
		c.Require("visibility.updated_at")
	}
	if e.CreatedByUUID.IsNil() {
		c.Require("visibility.created_by_uuid")
	}
	if e.UpdatedByUUID.IsNil() {
		c.Require("visibility.updated_by_uuid")
	}

	return c.Result()
}
