// Code generated by nuzur go-code-gen. DO NOT EDIT.

package deployment_revision

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/deployment_revision/types"
)

func (m *module) FetchDeploymentRevisionByUUID(
	ctx context.Context,
	req types.FetchDeploymentRevisionByUUIDRequest,
	opts ...Option,
) (types.FetchDeploymentRevisionByUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchDeploymentRevisionByUUID:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchDeploymentRevisionByUUIDResponse), nil
		}
	}
	fetch := func() (any, error) {
		models, err := queries.FetchDeploymentRevisionByUUID(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchDeploymentRevisionByUUIDResponse{}, err
		}
		return types.FetchDeploymentRevisionByUUIDResponse{
			Results: mapModelsToEntities(models),
		}, nil
	}
	var v any
	var err error
	if skipShared {
		v, err = fetch()
	} else {
		v, err, _ = m.sg.Do(cacheKey, fetch)
	}
	if err != nil {
		return types.FetchDeploymentRevisionByUUIDResponse{}, err
	}
	result := v.(types.FetchDeploymentRevisionByUUIDResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
