// Code generated by nuzur go-code-gen. DO NOT EDIT.

package deployment_revision

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/deployment_revision/types"
)

func (m *module) FetchDeploymentRevisionByUUID(
	ctx context.Context,
	req types.FetchDeploymentRevisionByUUIDRequest,
	opts ...Option,
) (types.FetchDeploymentRevisionByUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchDeploymentRevisionByUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchDeploymentRevisionByUUIDResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchDeploymentRevisionByUUID(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchDeploymentRevisionByUUIDResponse{}, err
		}
		return types.FetchDeploymentRevisionByUUIDResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchDeploymentRevisionByUUIDResponse{}, err
	}
	result := v.(types.FetchDeploymentRevisionByUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
