// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_url_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this FieldTypeURLConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e FieldTypeURLConfig) Validate() error {
	c := validation.NewCollector()
	if len(e.AllowDomains) == 0 {
		c.Require("field_type_url_config.allow_domains")
	}
	if len(e.AllowDomains) > 0 {
		c.Field("field_type_url_config.allow_domains", validation.Unique(e.AllowDomains))
		for i, el := range e.AllowDomains {
			c.Field(validation.Index("field_type_url_config.allow_domains", i), validation.String(el, 0, 0, ""))
		}

	}
	if len(e.ExcludeDomains) == 0 {
		c.Require("field_type_url_config.exclude_domains")
	}
	if len(e.ExcludeDomains) > 0 {
		c.Field("field_type_url_config.exclude_domains", validation.Unique(e.ExcludeDomains))
		for i, el := range e.ExcludeDomains {
			c.Field(validation.Index("field_type_url_config.exclude_domains", i), validation.String(el, 0, 0, ""))
		}

	}
	if len(e.AllowedExtensions) == 0 {
		c.Require("field_type_url_config.allowed_extensions")
	}
	if len(e.AllowedExtensions) > 0 {
		c.Field("field_type_url_config.allowed_extensions", validation.Unique(e.AllowedExtensions))
		for i, el := range e.AllowedExtensions {
			c.Field(validation.Index("field_type_url_config.allowed_extensions", i), validation.String(el, 0, 0, ""))
		}

	}

	return c.Result()
}
