// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/extension_execution"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchExtensionExecutionByUuidRequest struct {
	UUID uuid.UUID
}

func (r FetchExtensionExecutionByUuidRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchExtensionExecutionByUuidResponse struct {
	Results []main_entity.ExtensionExecution
}
