// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/extension_execution"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchExtensionExecutionByProjectVersionUuidRequest struct {
	ProjectVersionUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchExtensionExecutionByProjectVersionUuidRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("project_version_uuid", r.ProjectVersionUUID.String())

	return nil
}

type FetchExtensionExecutionByProjectVersionUuidResponse struct {
	Results []main_entity.ExtensionExecution
}
