// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/extension_execution"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	ExtensionExecution main_entity.ExtensionExecution
}

type UpsertResponse struct {
	UUID uuid.UUID
}
