// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/team"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchTeamByUuidRequest struct {
	UUID uuid.UUID
}

func (r FetchTeamByUuidRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchTeamByUuidResponse struct {
	Results []main_entity.Team
}
