// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/team"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchTeamByUpdatedByUUIDRequest struct {
	UpdatedByUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchTeamByUpdatedByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("updated_by_uuid", r.UpdatedByUUID.String())

	return nil
}

type FetchTeamByUpdatedByUUIDResponse struct {
	Results []main_entity.Team
}
