// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/extension/types"
)

func (m *module) FetchExtensionByUuid(
	ctx context.Context,
	req types.FetchExtensionByUuidRequest,
	opts ...Option,
) (types.FetchExtensionByUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchExtensionByUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchExtensionByUuidResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchExtensionByUuid(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchExtensionByUuidResponse{}, err
		}
		return types.FetchExtensionByUuidResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchExtensionByUuidResponse{}, err
	}
	result := v.(types.FetchExtensionByUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
