// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/extension/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchExtensionByExtensionType(
	ctx context.Context,
	req types.FetchExtensionByExtensionTypeRequest,
	opts ...Option,
) (types.FetchExtensionByExtensionTypeResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchExtensionByExtensionType:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchExtensionByExtensionTypeResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchExtensionByExtensionType(
				ctx,
				nemdb.FetchExtensionByExtensionTypeParams{
					ExtensionType: req.ExtensionType.ToInt64(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchExtensionByExtensionTypeResponse{}, err
			}
			return types.FetchExtensionByExtensionTypeResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchExtensionByExtensionTypeResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchExtensionByExtensionTypeResponse{}, fetchErr
	}
	result := v.(types.FetchExtensionByExtensionTypeResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
