// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension

import (
	"context"

	"github.com/nuzur/nem/core/module/extension/types"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/visibility"

	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	params.Version = time.Now().Unix()

	_, err := qtx.InsertExtension(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.Extension.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) nemdb.InsertExtensionParams {
	return nemdb.InsertExtensionParams{
		UUID: req.Extension.UUID.String(),

		Version: req.Extension.Version,

		Identifier: req.Extension.Identifier,

		DisplayName: req.Extension.DisplayName,

		DisplayAuthorName: req.Extension.DisplayAuthorName,

		Description: req.Extension.Description,

		URL: req.Extension.URL,

		Verified: req.Extension.Verified,

		Repository: req.Extension.Repository,

		ExtensionType: req.Extension.ExtensionType.ToInt64(),

		Tags: mapper.SliceToJSON(req.Extension.Tags),

		Pro: req.Extension.Pro,

		Public: req.Extension.Public,

		Visibility: visibility.VisibilitySliceToJSON(req.Extension.Visibility),

		Status: req.Extension.Status.ToInt64(),

		OwnerUUID: req.Extension.OwnerUUID.String(),

		CreatedAt: req.Extension.CreatedAt,

		UpdatedAt: req.Extension.UpdatedAt,

		CreatedByUUID: req.Extension.CreatedByUUID.String(),

		UpdatedByUUID: req.Extension.UpdatedByUUID.String(),
	}
}
