// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_email_config

import (
	"encoding/json"
	"log"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FieldTypeEmailConfig struct {
	AllowDomains   json.RawMessage `json:"allow_domains"`
	ExcludeDomains json.RawMessage `json:"exclude_domains"`
}

func (e FieldTypeEmailConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FieldTypeEmailConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FieldTypeEmailConfigFromJSON(data json.RawMessage) FieldTypeEmailConfig {
	entity := FieldTypeEmailConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FieldTypeEmailConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FieldTypeEmailConfigSliceFromJSON(data json.RawMessage) []FieldTypeEmailConfig {
	entity := []FieldTypeEmailConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FieldTypeEmailConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FieldTypeEmailConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FieldTypeEmailConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FieldTypeEmailConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeEmailConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeEmailConfigToJSON(e FieldTypeEmailConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeEmailConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeEmailConfigSliceToJSON(e []FieldTypeEmailConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeEmailConfigSliceToJSON: %v\n", err)
	}
	return res
}
