// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_email_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e FieldTypeEmailConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"allow_domains":   entitytypes.StringFieldType,
		"exclude_domains": entitytypes.StringFieldType,
	}
}

func (e FieldTypeEmailConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "allow_domains")
	res = append(res, "exclude_domains")

	return res
}

func (e FieldTypeEmailConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e FieldTypeEmailConfig) EntityIdentifier() string {
	return "field_type_email_config"
}

func (e FieldTypeEmailConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e FieldTypeEmailConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	res["allow_domains"] = entitytypes.StringFieldType
	res["exclude_domains"] = entitytypes.StringFieldType
	return res
}
