// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/user_connection"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchUserConnectionByProjectVersionUUIDRequest struct {
	ProjectVersionUUID *uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchUserConnectionByProjectVersionUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchUserConnectionByProjectVersionUUIDResponse struct {
	Results []main_entity.UserConnection
}
