// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/user_connection"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchUserConnectionByUserUUIDRequest struct {
	UserUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchUserConnectionByUserUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("user_uuid", r.UserUUID.String())

	return nil
}

type FetchUserConnectionByUserUUIDResponse struct {
	Results []main_entity.UserConnection
}
