// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_execution

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/extension_execution/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchExtensionExecutionByExtensionUuid(
	ctx context.Context,
	req types.FetchExtensionExecutionByExtensionUuidRequest,
	opts ...Option,
) (types.FetchExtensionExecutionByExtensionUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchExtensionExecutionByExtensionUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchExtensionExecutionByExtensionUuidResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchExtensionExecutionByExtensionUuid(
				ctx,
				nemdb.FetchExtensionExecutionByExtensionUuidParams{
					ExtensionUUID: req.ExtensionUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchExtensionExecutionByExtensionUuidResponse{}, err
			}
			return types.FetchExtensionExecutionByExtensionUuidResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchExtensionExecutionByExtensionUuidResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchExtensionExecutionByExtensionUuidResponse{}, fetchErr
	}
	result := v.(types.FetchExtensionExecutionByExtensionUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
