// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_execution

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/extension_execution/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchExtensionExecutionByProjectUUID(
	ctx context.Context,
	req types.FetchExtensionExecutionByProjectUUIDRequest,
	opts ...Option,
) (types.FetchExtensionExecutionByProjectUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchExtensionExecutionByProjectUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchExtensionExecutionByProjectUUIDResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchExtensionExecutionByProjectUUID(
				ctx,
				nemdb.FetchExtensionExecutionByProjectUUIDParams{
					ProjectUUID: req.ProjectUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchExtensionExecutionByProjectUUIDResponse{}, err
			}
			return types.FetchExtensionExecutionByProjectUUIDResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchExtensionExecutionByProjectUUIDResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchExtensionExecutionByProjectUUIDResponse{}, fetchErr
	}
	result := v.(types.FetchExtensionExecutionByProjectUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
