// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_execution

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/extension_execution/types"
)

func (m *module) FetchExtensionExecutionByUUID(
	ctx context.Context,
	req types.FetchExtensionExecutionByUUIDRequest,
	opts ...Option,
) (types.FetchExtensionExecutionByUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchExtensionExecutionByUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchExtensionExecutionByUUIDResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchExtensionExecutionByUUID(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchExtensionExecutionByUUIDResponse{}, err
		}
		return types.FetchExtensionExecutionByUUIDResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchExtensionExecutionByUUIDResponse{}, err
	}
	result := v.(types.FetchExtensionExecutionByUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
