// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_execution

import (
	"context"
	"errors"

	"github.com/nuzur/nem/core/module/extension_execution/types"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchExtensionExecutionByUUIDForUpdate(ctx,
		req.ExtensionExecution.UUID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.ExtensionExecution.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.ExtensionExecution.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateExtensionExecution(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.ExtensionExecution.UUID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) nemdb.UpdateExtensionExecutionParams {
	return nemdb.UpdateExtensionExecutionParams{
		UUID: req.ExtensionExecution.UUID.String(),

		ExtensionUUID: req.ExtensionExecution.ExtensionUUID.String(),

		ExtensionVersionUUID: req.ExtensionExecution.ExtensionVersionUUID.String(),

		ProjectExtensionUUID: mapper.UUIDPtrToNullString(req.ExtensionExecution.ProjectExtensionUUID),

		ProjectUUID: req.ExtensionExecution.ProjectUUID.String(),

		ProjectVersionUUID: req.ExtensionExecution.ProjectVersionUUID.String(),

		ExecutedByUUID: req.ExtensionExecution.ExecutedByUUID.String(),

		Metadata: mapper.NullifyEmptyJSON(req.ExtensionExecution.Metadata),

		Status: req.ExtensionExecution.Status.ToInt64(),

		StatusMsg: req.ExtensionExecution.StatusMsg,

		CreatedAt: req.ExtensionExecution.CreatedAt,

		UpdatedAt: req.ExtensionExecution.UpdatedAt,
	}
}
