// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_char_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e FieldTypeCharConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"min_size":         entitytypes.IntFieldType,
		"max_size":         entitytypes.IntFieldType,
		"regex_validation": entitytypes.StringFieldType,
	}
}

func (e FieldTypeCharConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "min_size")
	res = append(res, "max_size")
	res = append(res, "regex_validation")

	return res
}

func (e FieldTypeCharConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e FieldTypeCharConfig) EntityIdentifier() string {
	return "field_type_char_config"
}

func (e FieldTypeCharConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e FieldTypeCharConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
