// Code generated by nuzur go-code-gen. DO NOT EDIT.

package file_object_storage_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e FileObjectStorageConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"object_store_uuid": entitytypes.StringFieldType,
		"path":              entitytypes.StringFieldType,
	}
}

func (e FileObjectStorageConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "object_store_uuid")
	res = append(res, "path")

	return res
}

func (e FileObjectStorageConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e FileObjectStorageConfig) EntityIdentifier() string {
	return "file_object_storage_config"
}

func (e FileObjectStorageConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e FileObjectStorageConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
