// Code generated by nuzur go-code-gen. DO NOT EDIT.

package object_store

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this ObjectStore against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e ObjectStore) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("object_store.uuid")
	}
	if e.Identifier == "" {
		c.Require("object_store.identifier")
	} else {
		c.Field("object_store.identifier", validation.String(e.Identifier, 0, 255, ""))

	}
	if e.Type.ToInt64() == 0 {
		c.Require("object_store.type")
	} else {
		c.Field("object_store.type", validation.EnumMember(e.Type.ToInt64(), []int64{0, 1}, "object_store_type"))

	}
	if validation.IsZeroEntity(e.TypeConfig) {
		c.Require("object_store.type_config")
	} else {
		c.Merge("object_store.type_config", e.TypeConfig.Validate())
	}
	if e.Status.ToInt64() == 0 {
		c.Require("object_store.status")
	} else {
		c.Field("object_store.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "object_store_status"))

	}
	if e.CreatedAt.IsZero() {
		c.Require("object_store.created_at")
	}
	if e.UpdatedAt.IsZero() {
		c.Require("object_store.updated_at")
	}
	if e.CreatedByUUID.IsNil() {
		c.Require("object_store.created_by_uuid")
	}
	if e.UpdatedByUUID.IsNil() {
		c.Require("object_store.updated_by_uuid")
	}

	return c.Result()
}
