// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/project_version"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchProjectVersionByUuidRequest struct {
	UUID uuid.UUID
}

func (r FetchProjectVersionByUuidRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchProjectVersionByUuidResponse struct {
	Results []main_entity.ProjectVersion
}
