// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/project_version"

	"github.com/nuzur/nem/enums"
	"go.uber.org/zap/zapcore"
)

type FetchProjectVersionByStatusRequest struct {
	Status enums.ProjectVersionStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchProjectVersionByStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchProjectVersionByStatusResponse struct {
	Results []main_entity.ProjectVersion
}
