// Code generated by nuzur go-code-gen. DO NOT EDIT.

package entity_type_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this EntityTypeConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e EntityTypeConfig) Validate() error {
	c := validation.NewCollector()
	if validation.IsZeroEntity(e.Standalone) {
		c.Require("entity_type_config.standalone")
	} else {
		c.Merge("entity_type_config.standalone", e.Standalone.Validate())
	}
	if validation.IsZeroEntity(e.Dependent) {
		c.Require("entity_type_config.dependent")
	} else {
		c.Merge("entity_type_config.dependent", e.Dependent.Validate())
	}

	return c.Result()
}
