// Code generated by nuzur go-code-gen. DO NOT EDIT.

package entity_type_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"

	"github.com/nuzur/nem/core/entity/entity_type_dependent_config"
	"github.com/nuzur/nem/core/entity/entity_type_standalone_config"
)

func (e EntityTypeConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"standalone": entitytypes.MultiDependantEntityFieldType,
		"dependent":  entitytypes.MultiDependantEntityFieldType,
	}
}

func (e EntityTypeConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "standalone")
	res = append(res, "dependent")

	return res
}

func (e EntityTypeConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["standalone"] = entity_type_standalone_config.EntityTypeStandaloneConfig{}.FieldIdentifierToTypeMap()
	res["dependent"] = entity_type_dependent_config.EntityTypeDependentConfig{}.FieldIdentifierToTypeMap()
	return res
}

func (e EntityTypeConfig) EntityIdentifier() string {
	return "entity_type_config"
}

func (e EntityTypeConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e EntityTypeConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
