// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_execution

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e ExtensionExecution) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":                   entitytypes.StringFieldType,
		"extension_uuid":         entitytypes.StringFieldType,
		"extension_version_uuid": entitytypes.StringFieldType,
		"project_extension_uuid": entitytypes.StringFieldType,
		"project_uuid":           entitytypes.StringFieldType,
		"project_version_uuid":   entitytypes.StringFieldType,
		"executed_by_uuid":       entitytypes.StringFieldType,
		"metadata":               entitytypes.RawJSONFieldType,
		"status":                 entitytypes.SingleEnumFieldType,
		"status_msg":             entitytypes.StringFieldType,
		"created_at":             entitytypes.TimestampFieldType,
		"updated_at":             entitytypes.TimestampFieldType,
		"queue_priority":         entitytypes.IntFieldType,
		"last_heartbeat_at":      entitytypes.TimestampFieldType,
	}
}

func (e ExtensionExecution) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "extension_uuid")
	res = append(res, "extension_version_uuid")
	res = append(res, "project_extension_uuid")
	res = append(res, "project_uuid")
	res = append(res, "project_version_uuid")
	res = append(res, "executed_by_uuid")
	res = append(res, "metadata")
	res = append(res, "status")
	res = append(res, "status_msg")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "queue_priority")
	res = append(res, "last_heartbeat_at")

	return res
}

func (e ExtensionExecution) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e ExtensionExecution) EntityIdentifier() string {
	return "extension_execution"
}

func (e ExtensionExecution) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e ExtensionExecution) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
