// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_execution

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this ExtensionExecution against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e ExtensionExecution) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("extension_execution.uuid")
	}
	if e.ExtensionUUID.IsNil() {
		c.Require("extension_execution.extension_uuid")
	}
	if e.ExtensionVersionUUID.IsNil() {
		c.Require("extension_execution.extension_version_uuid")
	}
	if e.ProjectUUID.IsNil() {
		c.Require("extension_execution.project_uuid")
	}
	if e.ProjectVersionUUID.IsNil() {
		c.Require("extension_execution.project_version_uuid")
	}
	if e.ExecutedByUUID.IsNil() {
		c.Require("extension_execution.executed_by_uuid")
	}
	c.Field("extension_execution.metadata", validation.JSONBytes(e.Metadata))
	if e.Status.ToInt64() == 0 {
		c.Require("extension_execution.status")
	} else {
		c.Field("extension_execution.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3, 4}, "extension_execution_status"))

	}
	if e.StatusMsg.Valid && e.StatusMsg.String != "" {
		c.Field("extension_execution.status_msg", validation.String(e.StatusMsg.String, 0, 255, ""))

	}

	return c.Result()
}
