// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension_execution

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type ExtensionExecution struct {
	UUID                 uuid.UUID                      `json:"uuid"`
	ExtensionUUID        uuid.UUID                      `json:"extension_uuid"`
	ExtensionVersionUUID uuid.UUID                      `json:"extension_version_uuid"`
	ProjectExtensionUUID *uuid.UUID                     `json:"project_extension_uuid"`
	ProjectUUID          uuid.UUID                      `json:"project_uuid"`
	ProjectVersionUUID   uuid.UUID                      `json:"project_version_uuid"`
	ExecutedByUUID       uuid.UUID                      `json:"executed_by_uuid"`
	Metadata             json.RawMessage                `json:"metadata,omitempty"`
	Status               enums.ExtensionExecutionStatus `json:"status"`
	StatusMsg            null.String                    `json:"status_msg"`
	CreatedAt            time.Time                      `json:"created_at"`
	UpdatedAt            time.Time                      `json:"updated_at"`
	QueuePriority        null.Int64                     `json:"queue_priority"`
	LastHeartbeatAt      null.Time                      `json:"last_heartbeat_at"`
}

func (e ExtensionExecution) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e ExtensionExecution) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func ExtensionExecutionFromJSON(data json.RawMessage) ExtensionExecution {
	entity := ExtensionExecution{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ExtensionExecutionFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ExtensionExecutionSliceFromJSON(data json.RawMessage) []ExtensionExecution {
	entity := []ExtensionExecution{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []ExtensionExecution{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := ExtensionExecution{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ExtensionExecutionSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e ExtensionExecution) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ExtensionExecutionToJSON: %v\n", err)
	}
	return res
}

func ExtensionExecutionToJSON(e ExtensionExecution) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ExtensionExecutionToJSON: %v\n", err)
	}
	return res
}

func ExtensionExecutionSliceToJSON(e []ExtensionExecution) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ExtensionExecutionSliceToJSON: %v\n", err)
	}
	return res
}
