// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	"github.com/nuzur/nem/core/repository"
	"go.uber.org/zap"
)

type ModuleParams struct {
	Repository *repository.Implementation
	Logger     *zap.Logger
}
