// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/automation_event"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAutomationEventByChangeRequestUUIDRequest struct {
	ChangeRequestUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAutomationEventByChangeRequestUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("change_request_uuid", r.ChangeRequestUUID.String())

	return nil
}

type FetchAutomationEventByChangeRequestUUIDResponse struct {
	Results []main_entity.AutomationEvent
}
