// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/automation_event"

	"github.com/nuzur/nem/enums"
	"go.uber.org/zap/zapcore"
)

type FetchAutomationEventByStatusRequest struct {
	Status enums.AutomationEventStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAutomationEventByStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchAutomationEventByStatusResponse struct {
	Results []main_entity.AutomationEvent
}
