// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enum_value

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e EnumValue) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"identifier":    entitytypes.StringFieldType,
		"display":       entitytypes.StringFieldType,
		"numeric_value": entitytypes.IntFieldType,
	}
}

func (e EnumValue) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "identifier")
	res = append(res, "display")
	res = append(res, "numeric_value")

	return res
}

func (e EnumValue) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e EnumValue) EntityIdentifier() string {
	return "enum_value"
}

func (e EnumValue) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e EnumValue) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
