// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enum_value

import (
	"encoding/json"
	"log"

	"github.com/nuzur/nem/core/entity/mapper"
)

type EnumValue struct {
	Identifier   string `json:"identifier"`
	Display      string `json:"display"`
	NumericValue int64  `json:"numeric_value"`
}

func (e EnumValue) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e EnumValue) PrimaryKeyValues() []string {
	return []string{}
}

func EnumValueFromJSON(data json.RawMessage) EnumValue {
	entity := EnumValue{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error EnumValueFromJSON: %v\n", err2)
		}
	}
	return entity
}

func EnumValueSliceFromJSON(data json.RawMessage) []EnumValue {
	entity := []EnumValue{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []EnumValue{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := EnumValue{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error EnumValueSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e EnumValue) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnumValueToJSON: %v\n", err)
	}
	return res
}

func EnumValueToJSON(e EnumValue) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnumValueToJSON: %v\n", err)
	}
	return res
}

func EnumValueSliceToJSON(e []EnumValue) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnumValueSliceToJSON: %v\n", err)
	}
	return res
}
