// Code generated by nuzur go-code-gen. DO NOT EDIT.

package connection

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"

	"github.com/nuzur/nem/core/entity/connection_type_config"
	"github.com/nuzur/nem/core/entity/db_type_config"
)

func (e Connection) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":            entitytypes.StringFieldType,
		"version":         entitytypes.IntFieldType,
		"store_uuid":      entitytypes.StringFieldType,
		"enviorment_uuid": entitytypes.StringFieldType,
		"identifier":      entitytypes.StringFieldType,
		"db_type":         entitytypes.SingleEnumFieldType,
		"db_type_config":  entitytypes.MultiDependantEntityFieldType,
		"db_version":      entitytypes.StringFieldType,
		"type":            entitytypes.SingleEnumFieldType,
		"type_config":     entitytypes.MultiDependantEntityFieldType,
		"status":          entitytypes.SingleEnumFieldType,
		"created_at":      entitytypes.TimestampFieldType,
		"updated_at":      entitytypes.TimestampFieldType,
		"created_by_uuid": entitytypes.StringFieldType,
		"updated_by_uuid": entitytypes.StringFieldType,
	}
}

func (e Connection) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "version")
	res = append(res, "store_uuid")
	res = append(res, "enviorment_uuid")
	res = append(res, "identifier")
	res = append(res, "db_type")
	res = append(res, "db_type_config")
	res = append(res, "db_version")
	res = append(res, "type")
	res = append(res, "type_config")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "created_by_uuid")
	res = append(res, "updated_by_uuid")

	return res
}

func (e Connection) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["db_type_config"] = db_type_config.DbTypeConfig{}.FieldIdentifierToTypeMap()
	res["type_config"] = connection_type_config.ConnectionTypeConfig{}.FieldIdentifierToTypeMap()
	return res
}

func (e Connection) EntityIdentifier() string {
	return "connection"
}

func (e Connection) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e Connection) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
