// Code generated by nuzur go-code-gen. DO NOT EDIT.

package connection

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this Connection against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Connection) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("connection.uuid")
	}
	c.Field("connection.version", validation.Integer(e.Version, false, 0, 0, false, false, false, false, 0, 0))
	if e.StoreUUID.IsNil() {
		c.Require("connection.store_uuid")
	}
	if e.EnviormentUUID.IsNil() {
		c.Require("connection.enviorment_uuid")
	}
	if e.Identifier == "" {
		c.Require("connection.identifier")
	} else {
		c.Field("connection.identifier", validation.String(e.Identifier, 0, 255, ""))

	}
	if e.DbType.ToInt64() == 0 {
		c.Require("connection.db_type")
	} else {
		c.Field("connection.db_type", validation.EnumMember(e.DbType.ToInt64(), []int64{0, 1, 2}, "connection_db_type"))

	}
	if validation.IsZeroEntity(e.DbTypeConfig) {
		c.Require("connection.db_type_config")
	} else {
		c.Merge("connection.db_type_config", e.DbTypeConfig.Validate())
	}
	if e.DbVersion == "" {
		c.Require("connection.db_version")
	} else {
		c.Field("connection.db_version", validation.String(e.DbVersion, 0, 255, ""))

	}
	if e.Type.ToInt64() == 0 {
		c.Require("connection.type")
	} else {
		c.Field("connection.type", validation.EnumMember(e.Type.ToInt64(), []int64{0, 1, 2}, "connection_type"))

	}
	if validation.IsZeroEntity(e.TypeConfig) {
		c.Require("connection.type_config")
	} else {
		c.Merge("connection.type_config", e.TypeConfig.Validate())
	}
	if e.Status.ToInt64() == 0 {
		c.Require("connection.status")
	} else {
		c.Field("connection.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "connection_status"))

	}
	if e.CreatedAt.IsZero() {
		c.Require("connection.created_at")
	}
	if e.UpdatedAt.IsZero() {
		c.Require("connection.updated_at")
	}
	if e.CreatedByUUID.IsNil() {
		c.Require("connection.created_by_uuid")
	}
	if e.UpdatedByUUID.IsNil() {
		c.Require("connection.updated_by_uuid")
	}

	return c.Result()
}
