// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_project

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/user_project/types"
)

func (m *module) FetchUserProjectByUuid(
	ctx context.Context,
	req types.FetchUserProjectByUuidRequest,
	opts ...Option,
) (types.FetchUserProjectByUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchUserProjectByUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchUserProjectByUuidResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchUserProjectByUuid(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchUserProjectByUuidResponse{}, err
		}
		return types.FetchUserProjectByUuidResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchUserProjectByUuidResponse{}, err
	}
	result := v.(types.FetchUserProjectByUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
