// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_project

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/user_project/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/mapper"
)

func (m *module) FetchUserProjectByUserUUID(
	ctx context.Context,
	req types.FetchUserProjectByUserUUIDRequest,
	opts ...Option,
) (types.FetchUserProjectByUserUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchUserProjectByUserUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchUserProjectByUserUUIDResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchUserProjectByUserUUID(
				ctx,
				nemdb.FetchUserProjectByUserUUIDParams{
					UserUUID: mapper.UUIDPtrToNullString(req.UserUUID),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchUserProjectByUserUUIDResponse{}, err
			}
			return types.FetchUserProjectByUserUUIDResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchUserProjectByUserUUIDResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchUserProjectByUserUUIDResponse{}, fetchErr
	}
	result := v.(types.FetchUserProjectByUserUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
