// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_project

import (
	main_entity "github.com/nuzur/nem/core/entity/user_project"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/enums"
)

func mapModelsToEntities(models []nemdb.UserProject) []main_entity.UserProject {
	result := []main_entity.UserProject{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m nemdb.UserProject) main_entity.UserProject {
	return main_entity.UserProject{
		UUID:                    mapper.StringToUUID(m.UUID),
		UserUUID:                mapper.StringToUUIDPtr(m.UserUUID),
		UserEmail:               null.NewString(m.UserEmail.String, m.UserEmail.Valid),
		ProjectUUID:             mapper.StringToUUID(m.ProjectUUID),
		Role:                    enums.UserProjectRole(m.Role),
		ReviewRequiredStructure: m.ReviewRequiredStructure,
		ReviewRequiredData:      m.ReviewRequiredData,
		Status:                  enums.UserProjectStatus(m.Status),
		CreatedAt:               m.CreatedAt,
		UpdatedAt:               m.UpdatedAt,
		CreatedByUUID:           mapper.StringToUUID(m.CreatedByUUID),
		UpdatedByUUID:           mapper.StringToUUID(m.UpdatedByUUID),
	}
}
