// Code generated by nuzur go-code-gen. DO NOT EDIT.

package data_change_type_config_update

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nuzur/nem/core/entity/data_change_field_value"
	"github.com/nuzur/nem/core/entity/data_change_type_config_update_field"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type DataChangeTypeConfigUpdate struct {
	EntityUUID uuid.UUID                                                              `json:"entity_uuid"`
	Fields     []data_change_type_config_update_field.DataChangeTypeConfigUpdateField `json:"fields"`
	Keys       []data_change_field_value.DataChangeFieldValue                         `json:"keys"`
	CreatedAt  time.Time                                                              `json:"created_at"`
}

func (e DataChangeTypeConfigUpdate) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e DataChangeTypeConfigUpdate) PrimaryKeyValues() []string {
	return []string{}
}

func DataChangeTypeConfigUpdateFromJSON(data json.RawMessage) DataChangeTypeConfigUpdate {
	entity := DataChangeTypeConfigUpdate{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error DataChangeTypeConfigUpdateFromJSON: %v\n", err2)
		}
	}
	return entity
}

func DataChangeTypeConfigUpdateSliceFromJSON(data json.RawMessage) []DataChangeTypeConfigUpdate {
	entity := []DataChangeTypeConfigUpdate{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []DataChangeTypeConfigUpdate{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := DataChangeTypeConfigUpdate{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error DataChangeTypeConfigUpdateSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e DataChangeTypeConfigUpdate) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DataChangeTypeConfigUpdateToJSON: %v\n", err)
	}
	return res
}

func DataChangeTypeConfigUpdateToJSON(e DataChangeTypeConfigUpdate) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DataChangeTypeConfigUpdateToJSON: %v\n", err)
	}
	return res
}

func DataChangeTypeConfigUpdateSliceToJSON(e []DataChangeTypeConfigUpdate) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DataChangeTypeConfigUpdateSliceToJSON: %v\n", err)
	}
	return res
}
