// Code generated by nuzur go-code-gen. DO NOT EDIT.

package data_change_type_config_update

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this DataChangeTypeConfigUpdate against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e DataChangeTypeConfigUpdate) Validate() error {
	c := validation.NewCollector()
	if e.EntityUUID.IsNil() {
		c.Require("data_change_type_config_update.entity_uuid")
	}
	if len(e.Fields) == 0 {
		c.Require("data_change_type_config_update.fields")
	} else {
		for i, item := range e.Fields {
			c.Merge(validation.Index("data_change_type_config_update.fields", i), item.Validate())
		}

	}
	if len(e.Keys) == 0 {
		c.Require("data_change_type_config_update.keys")
	} else {
		for i, item := range e.Keys {
			c.Merge(validation.Index("data_change_type_config_update.keys", i), item.Validate())
		}

	}
	if e.CreatedAt.IsZero() {
		c.Require("data_change_type_config_update.created_at")
	}

	return c.Result()
}
