// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/automation"

	"github.com/nuzur/nem/enums"
	"go.uber.org/zap/zapcore"
)

type FetchAutomationByStatusRequest struct {
	Status enums.AutomationStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAutomationByStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchAutomationByStatusResponse struct {
	Results []main_entity.Automation
}
