// Code generated by nuzur go-code-gen. DO NOT EDIT.

package array_type_config

import (
	"encoding/json"
	"log"

	"github.com/nuzur/nem/core/entity/field_type_char_config"
	"github.com/nuzur/nem/core/entity/field_type_date_config"
	"github.com/nuzur/nem/core/entity/field_type_datetime_config"
	"github.com/nuzur/nem/core/entity/field_type_decimal_config"
	"github.com/nuzur/nem/core/entity/field_type_email_config"
	"github.com/nuzur/nem/core/entity/field_type_encrypted_config"
	"github.com/nuzur/nem/core/entity/field_type_enum_config"
	"github.com/nuzur/nem/core/entity/field_type_float_config"
	"github.com/nuzur/nem/core/entity/field_type_integer_config"
	"github.com/nuzur/nem/core/entity/field_type_phone_config"
	"github.com/nuzur/nem/core/entity/field_type_url_config"
	"github.com/nuzur/nem/core/entity/field_type_varchar_config"

	"github.com/nuzur/nem/core/entity/mapper"
)

type ArrayTypeConfig struct {
	Integer   field_type_integer_config.FieldTypeIntegerConfig     `json:"integer"`
	Float     field_type_float_config.FieldTypeFloatConfig         `json:"float"`
	Decimal   field_type_decimal_config.FieldTypeDecimalConfig     `json:"decimal"`
	Char      field_type_char_config.FieldTypeCharConfig           `json:"char"`
	Varchar   field_type_varchar_config.FieldTypeVarcharConfig     `json:"varchar"`
	Encrypted field_type_encrypted_config.FieldTypeEncryptedConfig `json:"encrypted"`
	URL       field_type_url_config.FieldTypeURLConfig             `json:"url"`
	Email     field_type_email_config.FieldTypeEmailConfig         `json:"email"`
	Phone     field_type_phone_config.FieldTypePhoneConfig         `json:"phone"`
	Date      field_type_date_config.FieldTypeDateConfig           `json:"date"`
	Datetime  field_type_datetime_config.FieldTypeDatetimeConfig   `json:"datetime"`
	Enum      field_type_enum_config.FieldTypeEnumConfig           `json:"enum"`
}

func (e ArrayTypeConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e ArrayTypeConfig) PrimaryKeyValues() []string {
	return []string{}
}

func ArrayTypeConfigFromJSON(data json.RawMessage) ArrayTypeConfig {
	entity := ArrayTypeConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ArrayTypeConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ArrayTypeConfigSliceFromJSON(data json.RawMessage) []ArrayTypeConfig {
	entity := []ArrayTypeConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []ArrayTypeConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := ArrayTypeConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ArrayTypeConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e ArrayTypeConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ArrayTypeConfigToJSON: %v\n", err)
	}
	return res
}

func ArrayTypeConfigToJSON(e ArrayTypeConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ArrayTypeConfigToJSON: %v\n", err)
	}
	return res
}

func ArrayTypeConfigSliceToJSON(e []ArrayTypeConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ArrayTypeConfigSliceToJSON: %v\n", err)
	}
	return res
}
