// Code generated by nuzur go-code-gen. DO NOT EDIT.

package object_store_type_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"

	"github.com/nuzur/nem/core/entity/object_store_s3_type_config"
)

func (e ObjectStoreTypeConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"s3": entitytypes.MultiDependantEntityFieldType,
	}
}

func (e ObjectStoreTypeConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "s3")

	return res
}

func (e ObjectStoreTypeConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["s3"] = object_store_s3_type_config.ObjectStoreS3TypeConfig{}.FieldIdentifierToTypeMap()
	return res
}

func (e ObjectStoreTypeConfig) EntityIdentifier() string {
	return "object_store_type_config"
}

func (e ObjectStoreTypeConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e ObjectStoreTypeConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
