// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"

	"github.com/nuzur/nem/core/entity/field_type_array_config"
	"github.com/nuzur/nem/core/entity/field_type_char_config"
	"github.com/nuzur/nem/core/entity/field_type_date_config"
	"github.com/nuzur/nem/core/entity/field_type_datetime_config"
	"github.com/nuzur/nem/core/entity/field_type_decimal_config"
	"github.com/nuzur/nem/core/entity/field_type_email_config"
	"github.com/nuzur/nem/core/entity/field_type_encrypted_config"
	"github.com/nuzur/nem/core/entity/field_type_enum_config"
	"github.com/nuzur/nem/core/entity/field_type_file_config"
	"github.com/nuzur/nem/core/entity/field_type_float_config"
	"github.com/nuzur/nem/core/entity/field_type_integer_config"
	"github.com/nuzur/nem/core/entity/field_type_json_config"
	"github.com/nuzur/nem/core/entity/field_type_phone_config"
	"github.com/nuzur/nem/core/entity/field_type_slug_config"
	"github.com/nuzur/nem/core/entity/field_type_text_config"
	"github.com/nuzur/nem/core/entity/field_type_url_config"
	"github.com/nuzur/nem/core/entity/field_type_varchar_config"
)

func (e FieldTypeConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":      entitytypes.RawJSONFieldType,
		"integer":   entitytypes.MultiDependantEntityFieldType,
		"float":     entitytypes.MultiDependantEntityFieldType,
		"decimal":   entitytypes.MultiDependantEntityFieldType,
		"boolean":   entitytypes.RawJSONFieldType,
		"char":      entitytypes.MultiDependantEntityFieldType,
		"varchar":   entitytypes.MultiDependantEntityFieldType,
		"text":      entitytypes.MultiDependantEntityFieldType,
		"encrypted": entitytypes.MultiDependantEntityFieldType,
		"email":     entitytypes.MultiDependantEntityFieldType,
		"phone":     entitytypes.MultiDependantEntityFieldType,
		"url":       entitytypes.MultiDependantEntityFieldType,
		"location":  entitytypes.RawJSONFieldType,
		"color":     entitytypes.RawJSONFieldType,
		"rich_text": entitytypes.RawJSONFieldType,
		"code":      entitytypes.RawJSONFieldType,
		"markdown":  entitytypes.RawJSONFieldType,
		"file":      entitytypes.MultiDependantEntityFieldType,
		"image":     entitytypes.MultiDependantEntityFieldType,
		"video":     entitytypes.MultiDependantEntityFieldType,
		"audio":     entitytypes.MultiDependantEntityFieldType,
		"enum":      entitytypes.MultiDependantEntityFieldType,
		"json":      entitytypes.MultiDependantEntityFieldType,
		"array":     entitytypes.MultiDependantEntityFieldType,
		"date":      entitytypes.MultiDependantEntityFieldType,
		"datetime":  entitytypes.MultiDependantEntityFieldType,
		"time":      entitytypes.RawJSONFieldType,
		"slug":      entitytypes.MultiDependantEntityFieldType,
	}
}

func (e FieldTypeConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "integer")
	res = append(res, "float")
	res = append(res, "decimal")
	res = append(res, "boolean")
	res = append(res, "char")
	res = append(res, "varchar")
	res = append(res, "text")
	res = append(res, "encrypted")
	res = append(res, "email")
	res = append(res, "phone")
	res = append(res, "url")
	res = append(res, "location")
	res = append(res, "color")
	res = append(res, "rich_text")
	res = append(res, "code")
	res = append(res, "markdown")
	res = append(res, "file")
	res = append(res, "image")
	res = append(res, "video")
	res = append(res, "audio")
	res = append(res, "enum")
	res = append(res, "json")
	res = append(res, "array")
	res = append(res, "date")
	res = append(res, "datetime")
	res = append(res, "time")
	res = append(res, "slug")

	return res
}

func (e FieldTypeConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["integer"] = field_type_integer_config.FieldTypeIntegerConfig{}.FieldIdentifierToTypeMap()
	res["float"] = field_type_float_config.FieldTypeFloatConfig{}.FieldIdentifierToTypeMap()
	res["decimal"] = field_type_decimal_config.FieldTypeDecimalConfig{}.FieldIdentifierToTypeMap()
	res["char"] = field_type_char_config.FieldTypeCharConfig{}.FieldIdentifierToTypeMap()
	res["varchar"] = field_type_varchar_config.FieldTypeVarcharConfig{}.FieldIdentifierToTypeMap()
	res["text"] = field_type_text_config.FieldTypeTextConfig{}.FieldIdentifierToTypeMap()
	res["encrypted"] = field_type_encrypted_config.FieldTypeEncryptedConfig{}.FieldIdentifierToTypeMap()
	res["email"] = field_type_email_config.FieldTypeEmailConfig{}.FieldIdentifierToTypeMap()
	res["phone"] = field_type_phone_config.FieldTypePhoneConfig{}.FieldIdentifierToTypeMap()
	res["url"] = field_type_url_config.FieldTypeURLConfig{}.FieldIdentifierToTypeMap()
	res["file"] = field_type_file_config.FieldTypeFileConfig{}.FieldIdentifierToTypeMap()
	res["image"] = field_type_file_config.FieldTypeFileConfig{}.FieldIdentifierToTypeMap()
	res["video"] = field_type_file_config.FieldTypeFileConfig{}.FieldIdentifierToTypeMap()
	res["audio"] = field_type_file_config.FieldTypeFileConfig{}.FieldIdentifierToTypeMap()
	res["enum"] = field_type_enum_config.FieldTypeEnumConfig{}.FieldIdentifierToTypeMap()
	res["json"] = field_type_json_config.FieldTypeJSONConfig{}.FieldIdentifierToTypeMap()
	res["array"] = field_type_array_config.FieldTypeArrayConfig{}.FieldIdentifierToTypeMap()
	res["date"] = field_type_date_config.FieldTypeDateConfig{}.FieldIdentifierToTypeMap()
	res["datetime"] = field_type_datetime_config.FieldTypeDatetimeConfig{}.FieldIdentifierToTypeMap()
	res["slug"] = field_type_slug_config.FieldTypeSlugConfig{}.FieldIdentifierToTypeMap()
	return res
}

func (e FieldTypeConfig) EntityIdentifier() string {
	return "field_type_config"
}

func (e FieldTypeConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e FieldTypeConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
