
CREATE TABLE IF NOT EXISTS `extension` ( 
  `uuid` CHAR(36) NOT NULL  ,
  `version` INT NOT NULL  ,
  `identifier` VARCHAR(255) NOT NULL UNIQUE ,
  `display_name` VARCHAR(255)   ,
  `display_author_name` VARCHAR(255)   ,
  `description` VARCHAR(255)   ,
  `url` VARCHAR(255)   ,
  `verfied` TINYINT(1) NOT NULL  ,
  `repository` VARCHAR(255) NOT NULL  ,
  `extension_type` INT NOT NULL  ,
  `tags` JSON   ,
  `public` TINYINT(1) NOT NULL  ,
  `visibility` JSON   ,
  `status` INT NOT NULL  ,
  `owner_uuid` CHAR(36) NOT NULL  ,
  `created_at` DATETIME NOT NULL  default CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL  default CURRENT_TIMESTAMP,
  `created_by_uuid` CHAR(36) NOT NULL  ,
  `updated_by_uuid` CHAR(36) NOT NULL  ,  
  PRIMARY KEY (`uuid`),
  INDEX `version` (`version` ASC),
  INDEX `repository` (`repository` ASC),
  INDEX `extension_type` (`extension_type` ASC),
  INDEX `public` (`public` ASC),
  INDEX `status` (`status` ASC),
  INDEX `owner_uuid` (`owner_uuid` ASC),
  INDEX `created_at` (`created_at` ASC),
  INDEX `updated_at` (`updated_at` ASC))  
ENGINE = InnoDB;
