
CREATE TABLE IF NOT EXISTS `project_version` ( 
  `uuid` CHAR(36) NOT NULL  ,
  `version` INT NOT NULL  ,
  `identifier` VARCHAR(255) NOT NULL  ,
  `description` VARCHAR(255) NOT NULL  ,
  `project_uuid` CHAR(36) NOT NULL  ,
  `entities` JSON NOT NULL  ,
  `relationships` JSON NOT NULL  ,
  `enums` JSON NOT NULL  ,
  `services` JSON NOT NULL  ,
  `base_version_uuid` CHAR(36) NOT NULL  ,
  `review_status` INT NOT NULL  ,
  `deployments` JSON NOT NULL  ,
  `status` INT NOT NULL  ,
  `created_at` DATETIME NOT NULL  default CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL  default CURRENT_TIMESTAMP,
  `created_by_uuid` CHAR(36) NOT NULL  ,
  `updated_by_uuid` CHAR(36) NOT NULL  ,  
  PRIMARY KEY (`uuid`),
  INDEX `version` (`version` ASC),
  INDEX `project_uuid` (`project_uuid` ASC),
  INDEX `base_version_uuid` (`base_version_uuid` ASC),
  INDEX `review_status` (`review_status` ASC),
  INDEX `status` (`status` ASC),
  INDEX `created_at` (`created_at` ASC),
  INDEX `updated_at` (`updated_at` ASC),
  INDEX `created_by_uuid` (`created_by_uuid` ASC),
  INDEX `updated_by_uuid` (`updated_by_uuid` ASC))  
ENGINE = InnoDB;
