// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enum

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nuzur/nem/core/entity/enum_value"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type Enum struct {
	UUID          uuid.UUID              `json:"uuid"`
	Version       int64                  `json:"version"`
	Identifier    string                 `json:"identifier"`
	StaticValues  []enum_value.EnumValue `json:"static_values"`
	RemoteValues  bool                   `json:"remote_values"`
	Status        enums.EnumStatus       `json:"status"`
	CreatedAt     time.Time              `json:"created_at"`
	UpdatedAt     time.Time              `json:"updated_at"`
	CreatedByUUID uuid.UUID              `json:"created_by_uuid"`
	UpdatedByUUID uuid.UUID              `json:"updated_by_uuid"`
}

func (e Enum) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Enum) PrimaryKeyValues() []string {
	return []string{}
}

func EnumFromJSON(data json.RawMessage) Enum {
	entity := Enum{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error EnumFromJSON: %v\n", err2)
		}
	}
	return entity
}

func EnumSliceFromJSON(data json.RawMessage) []Enum {
	entity := []Enum{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Enum{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Enum{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error EnumSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Enum) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnumToJSON: %v\n", err)
	}
	return res
}

func EnumToJSON(e Enum) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnumToJSON: %v\n", err)
	}
	return res
}

func EnumSliceToJSON(e []Enum) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnumSliceToJSON: %v\n", err)
	}
	return res
}
