// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/project"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchProjectByCreatedByUUIDRequest struct {
	CreatedByUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchProjectByCreatedByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("created_by_uuid", r.CreatedByUUID.String())

	return nil
}

type FetchProjectByCreatedByUUIDResponse struct {
	Results []main_entity.Project
}
