// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/project"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchProjectByUuidRequest struct {
	UUID uuid.UUID
}

func (r FetchProjectByUuidRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchProjectByUuidResponse struct {
	Results []main_entity.Project
}
