// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request_review

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e ChangeRequestReview) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":       entitytypes.StringFieldType,
		"user_uuid":  entitytypes.StringFieldType,
		"comment":    entitytypes.StringFieldType,
		"response":   entitytypes.SingleEnumFieldType,
		"created_at": entitytypes.TimestampFieldType,
		"updated_at": entitytypes.TimestampFieldType,
	}
}

func (e ChangeRequestReview) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "user_uuid")
	res = append(res, "comment")
	res = append(res, "response")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e ChangeRequestReview) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e ChangeRequestReview) EntityIdentifier() string {
	return "change_request_review"
}

func (e ChangeRequestReview) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e ChangeRequestReview) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
