// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_date_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this FieldTypeDateConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e FieldTypeDateConfig) Validate() error {
	c := validation.NewCollector()
	if e.DisplayTimezone.Valid && e.DisplayTimezone.String != "" {
		c.Field("field_type_date_config.display_timezone", validation.String(e.DisplayTimezone.String, 0, 255, ""))

	}
	if e.StorageTimezone.Valid && e.StorageTimezone.String != "" {
		c.Field("field_type_date_config.storage_timezone", validation.String(e.StorageTimezone.String, 0, 255, ""))

	}

	return c.Result()
}
