// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_date_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e FieldTypeDateConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"enforce_future":   entitytypes.BooleanFieldType,
		"enforce_past":     entitytypes.BooleanFieldType,
		"display_timezone": entitytypes.StringFieldType,
		"storage_timezone": entitytypes.StringFieldType,
	}
}

func (e FieldTypeDateConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "enforce_future")
	res = append(res, "enforce_past")
	res = append(res, "display_timezone")
	res = append(res, "storage_timezone")

	return res
}

func (e FieldTypeDateConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e FieldTypeDateConfig) EntityIdentifier() string {
	return "field_type_date_config"
}

func (e FieldTypeDateConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e FieldTypeDateConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
