// Code generated by nuzur go-code-gen. DO NOT EDIT.

package automation

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type Automation struct {
	UUID          uuid.UUID                  `json:"uuid"`
	ProjectUUID   uuid.UUID                  `json:"project_uuid"`
	EntityUUID    uuid.UUID                  `json:"entity_uuid"`
	Name          string                     `json:"name"`
	Operation     enums.AutomationOperation  `json:"operation"`
	Condition     json.RawMessage            `json:"condition,omitempty"`
	ActionType    enums.AutomationActionType `json:"action_type"`
	ActionConfig  json.RawMessage            `json:"action_config,omitempty"`
	Enabled       bool                       `json:"enabled"`
	Status        enums.AutomationStatus     `json:"status"`
	CreatedAt     time.Time                  `json:"created_at"`
	UpdatedAt     time.Time                  `json:"updated_at"`
	CreatedByUUID uuid.UUID                  `json:"created_by_uuid"`
	UpdatedByUUID uuid.UUID                  `json:"updated_by_uuid"`
}

func (e Automation) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Automation) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func AutomationFromJSON(data json.RawMessage) Automation {
	entity := Automation{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error AutomationFromJSON: %v\n", err2)
		}
	}
	return entity
}

func AutomationSliceFromJSON(data json.RawMessage) []Automation {
	entity := []Automation{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Automation{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Automation{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error AutomationSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Automation) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AutomationToJSON: %v\n", err)
	}
	return res
}

func AutomationToJSON(e Automation) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AutomationToJSON: %v\n", err)
	}
	return res
}

func AutomationSliceToJSON(e []Automation) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AutomationSliceToJSON: %v\n", err)
	}
	return res
}
