// Code generated by nuzur go-code-gen. DO NOT EDIT.

package automation

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e Automation) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":            entitytypes.StringFieldType,
		"project_uuid":    entitytypes.StringFieldType,
		"entity_uuid":     entitytypes.StringFieldType,
		"name":            entitytypes.StringFieldType,
		"operation":       entitytypes.SingleEnumFieldType,
		"condition":       entitytypes.RawJSONFieldType,
		"action_type":     entitytypes.SingleEnumFieldType,
		"action_config":   entitytypes.RawJSONFieldType,
		"enabled":         entitytypes.BooleanFieldType,
		"status":          entitytypes.SingleEnumFieldType,
		"created_at":      entitytypes.TimestampFieldType,
		"updated_at":      entitytypes.TimestampFieldType,
		"created_by_uuid": entitytypes.StringFieldType,
		"updated_by_uuid": entitytypes.StringFieldType,
	}
}

func (e Automation) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "project_uuid")
	res = append(res, "entity_uuid")
	res = append(res, "name")
	res = append(res, "operation")
	res = append(res, "condition")
	res = append(res, "action_type")
	res = append(res, "action_config")
	res = append(res, "enabled")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "created_by_uuid")
	res = append(res, "updated_by_uuid")

	return res
}

func (e Automation) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Automation) EntityIdentifier() string {
	return "automation"
}

func (e Automation) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e Automation) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
