// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request_metadata_data

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"

	"github.com/nuzur/nem/core/entity/mapper"
)

type ChangeRequestMetadataData struct {
	StoreUUID      uuid.UUID   `json:"store_uuid"`
	ConnectionUUID uuid.UUID   `json:"connection_uuid"`
	Schema         null.String `json:"schema"`
}

func (e ChangeRequestMetadataData) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e ChangeRequestMetadataData) PrimaryKeyValues() []string {
	return []string{}
}

func ChangeRequestMetadataDataFromJSON(data json.RawMessage) ChangeRequestMetadataData {
	entity := ChangeRequestMetadataData{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ChangeRequestMetadataDataFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ChangeRequestMetadataDataSliceFromJSON(data json.RawMessage) []ChangeRequestMetadataData {
	entity := []ChangeRequestMetadataData{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []ChangeRequestMetadataData{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := ChangeRequestMetadataData{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ChangeRequestMetadataDataSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e ChangeRequestMetadataData) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ChangeRequestMetadataDataToJSON: %v\n", err)
	}
	return res
}

func ChangeRequestMetadataDataToJSON(e ChangeRequestMetadataData) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ChangeRequestMetadataDataToJSON: %v\n", err)
	}
	return res
}

func ChangeRequestMetadataDataSliceToJSON(e []ChangeRequestMetadataData) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ChangeRequestMetadataDataSliceToJSON: %v\n", err)
	}
	return res
}
