// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request_metadata_data

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this ChangeRequestMetadataData against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e ChangeRequestMetadataData) Validate() error {
	c := validation.NewCollector()
	if e.StoreUUID.IsNil() {
		c.Require("change_request_metadata_data.store_uuid")
	}
	if e.ConnectionUUID.IsNil() {
		c.Require("change_request_metadata_data.connection_uuid")
	}
	if e.Schema.Valid && e.Schema.String != "" {
		c.Field("change_request_metadata_data.schema", validation.String(e.Schema.String, 0, 255, ""))

	}

	return c.Result()
}
