// Code generated by nuzur go-code-gen. DO NOT EDIT.

package team

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/team/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchTeamByOwnerUuid(
	ctx context.Context,
	req types.FetchTeamByOwnerUuidRequest,
	opts ...Option,
) (types.FetchTeamByOwnerUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchTeamByOwnerUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchTeamByOwnerUuidResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchTeamByOwnerUuid(
				ctx,
				nemdb.FetchTeamByOwnerUuidParams{
					OwnerUUID: req.OwnerUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchTeamByOwnerUuidResponse{}, err
			}
			return types.FetchTeamByOwnerUuidResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchTeamByOwnerUuidResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchTeamByOwnerUuidResponse{}, fetchErr
	}
	result := v.(types.FetchTeamByOwnerUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
