// Code generated by nuzur go-code-gen. DO NOT EDIT.

package team

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/team/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchTeamByVersion(
	ctx context.Context,
	req types.FetchTeamByVersionRequest,
	opts ...Option,
) (types.FetchTeamByVersionResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchTeamByVersion:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchTeamByVersionResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchTeamByVersion(
				ctx,
				nemdb.FetchTeamByVersionParams{
					Version: req.Version,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchTeamByVersionResponse{}, err
			}
			return types.FetchTeamByVersionResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchTeamByVersionResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchTeamByVersionResponse{}, fetchErr
	}
	result := v.(types.FetchTeamByVersionResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
