// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/deployment_revision"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchDeploymentRevisionByUUIDRequest struct {
	UUID uuid.UUID
}

func (r FetchDeploymentRevisionByUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("uuid", r.UUID.String())

	return nil
}

type FetchDeploymentRevisionByUUIDResponse struct {
	Results []main_entity.DeploymentRevision
}
