// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/deployment_revision"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchDeploymentRevisionByDeploymentUUIDRequest struct {
	DeploymentUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchDeploymentRevisionByDeploymentUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("deployment_uuid", r.DeploymentUUID.String())

	return nil
}

type FetchDeploymentRevisionByDeploymentUUIDResponse struct {
	Results []main_entity.DeploymentRevision
}
