// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_connection_local_config

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"

	"github.com/nuzur/nem/core/entity/mapper"
)

type UserConnectionLocalConfig struct {
	LocalAgentUUID           uuid.UUID `json:"local_agent_uuid"`
	LocalAgentConnectionUUID uuid.UUID `json:"local_agent_connection_uuid"`
}

func (e UserConnectionLocalConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e UserConnectionLocalConfig) PrimaryKeyValues() []string {
	return []string{}
}

func UserConnectionLocalConfigFromJSON(data json.RawMessage) UserConnectionLocalConfig {
	entity := UserConnectionLocalConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error UserConnectionLocalConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func UserConnectionLocalConfigSliceFromJSON(data json.RawMessage) []UserConnectionLocalConfig {
	entity := []UserConnectionLocalConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []UserConnectionLocalConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := UserConnectionLocalConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error UserConnectionLocalConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e UserConnectionLocalConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserConnectionLocalConfigToJSON: %v\n", err)
	}
	return res
}

func UserConnectionLocalConfigToJSON(e UserConnectionLocalConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserConnectionLocalConfigToJSON: %v\n", err)
	}
	return res
}

func UserConnectionLocalConfigSliceToJSON(e []UserConnectionLocalConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserConnectionLocalConfigSliceToJSON: %v\n", err)
	}
	return res
}
