// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_pii_config

import (
	"encoding/json"
	"log"

	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/core/entity/visibility"
	"github.com/nuzur/nem/enums"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FieldPiiConfig struct {
	MaskStrategy       enums.FieldPiiConfigMaskStrategy `json:"mask_strategy"`
	CustomMaskTemplate null.String                      `json:"custom_mask_template"`
	Visibility         []visibility.Visibility          `json:"visibility"`
}

func (e FieldPiiConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FieldPiiConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FieldPiiConfigFromJSON(data json.RawMessage) FieldPiiConfig {
	entity := FieldPiiConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FieldPiiConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FieldPiiConfigSliceFromJSON(data json.RawMessage) []FieldPiiConfig {
	entity := []FieldPiiConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FieldPiiConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FieldPiiConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FieldPiiConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FieldPiiConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldPiiConfigToJSON: %v\n", err)
	}
	return res
}

func FieldPiiConfigToJSON(e FieldPiiConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldPiiConfigToJSON: %v\n", err)
	}
	return res
}

func FieldPiiConfigSliceToJSON(e []FieldPiiConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldPiiConfigSliceToJSON: %v\n", err)
	}
	return res
}
