// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/extension"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchExtensionByOwnerUuidRequest struct {
	OwnerUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchExtensionByOwnerUuidRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("owner_uuid", r.OwnerUUID.String())

	return nil
}

type FetchExtensionByOwnerUuidResponse struct {
	Results []main_entity.Extension
}
