// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	ai_usagemodule "github.com/nuzur/nem/core/module/ai_usage"
	"github.com/nuzur/nem/core/module/ai_usage/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"
)

func (s *server) CreateAiUsage(ctx context.Context, req *pb.CreateAiUsageRequest) (*pb.AiUsage, error) {
	res, err := s.core.AiUsage().Insert(ctx, types.UpsertRequest{
		AiUsage: pbmapper.AiUsageFromProto(req.GetAiUsage()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.AiUsage().FetchAiUsageByUUID(ctx, types.FetchAiUsageByUUIDRequest(res), ai_usagemodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.AiUsageToProto(fetchRes.Results[0]), nil
}
