// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	automationmodule "github.com/nuzur/nem/core/module/automation"
	"github.com/nuzur/nem/core/module/automation/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"
)

func (s *server) CreateAutomation(ctx context.Context, req *pb.CreateAutomationRequest) (*pb.Automation, error) {
	res, err := s.core.Automation().Insert(ctx, types.UpsertRequest{
		Automation: pbmapper.AutomationFromProto(req.GetAutomation()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.Automation().FetchAutomationByUUID(ctx, types.FetchAutomationByUUIDRequest(res), automationmodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.AutomationToProto(fetchRes.Results[0]), nil
}
