// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	projectmodule "github.com/nuzur/nem/core/module/project"
	"github.com/nuzur/nem/core/module/project/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"
)

func (s *server) CreateProject(ctx context.Context, req *pb.CreateProjectRequest) (*pb.Project, error) {
	res, err := s.core.Project().Insert(ctx, types.UpsertRequest{
		Project: pbmapper.ProjectFromProto(req.GetProject()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.Project().FetchProjectByUuid(ctx, types.FetchProjectByUuidRequest(res), projectmodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.ProjectToProto(fetchRes.Results[0]), nil
}
