// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	extensionmodule "github.com/nuzur/nem/core/module/extension"
	"github.com/nuzur/nem/core/module/extension/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"
)

func (s *server) CreateExtension(ctx context.Context, req *pb.CreateExtensionRequest) (*pb.Extension, error) {
	res, err := s.core.Extension().Insert(ctx, types.UpsertRequest{
		Extension: pbmapper.ExtensionFromProto(req.GetExtension()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.Extension().FetchExtensionByUuid(ctx, types.FetchExtensionByUuidRequest(res), extensionmodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.ExtensionToProto(fetchRes.Results[0]), nil
}
