// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	user_teammodule "github.com/nuzur/nem/core/module/user_team"
	"github.com/nuzur/nem/core/module/user_team/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"
)

func (s *server) CreateUserTeam(ctx context.Context, req *pb.CreateUserTeamRequest) (*pb.UserTeam, error) {
	res, err := s.core.UserTeam().Insert(ctx, types.UpsertRequest{
		UserTeam: pbmapper.UserTeamFromProto(req.GetUserTeam()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.UserTeam().FetchUserTeamByUUID(ctx, types.FetchUserTeamByUUIDRequest(res), user_teammodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.UserTeamToProto(fetchRes.Results[0]), nil
}
