// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"fmt"
	"log"
	//"encoding/json"

	user_teammodule "github.com/nuzur/nem/core/module/user_team"
	"github.com/nuzur/nem/core/module/user_team/types"
	pb "github.com/nuzur/nem/idl/gen"

	pbmapper "github.com/nuzur/nem/idl/mapper"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"
	"go.einride.tech/aip/pagination"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func BuildListUserTeamRequest(ctx context.Context, request *pb.ListUserTeamRequest) (types.ListRequest, *pagination.PageToken, error) {
	err := validatePageSizeForListUserTeam(request)
	if err != nil {
		return types.ListRequest{}, nil, err
	}

	// Use pagination.PageToken for offset-based page tokens.
	pageToken, err := pagination.ParsePageToken(request)
	if err != nil {
		return types.ListRequest{}, nil, status.Errorf(codes.InvalidArgument, "invalid page token")
	}

	// parse filters
	declarations := user_teamDeclarations()
	filter, err := filtering.ParseFilter(request, declarations)
	if err != nil {
		return types.ListRequest{}, nil, fmt.Errorf("error parsing filter: %w", err)
	}

	/* // enable for debugging
	if filter.CheckedExpr != nil {
		b, _ := json.Marshal(filter.CheckedExpr.Expr)
		log.Printf("filtering: %v \n", string(b))
	}
	*/

	orderBy, err := ordering.ParseOrderBy(request)
	if err != nil {
		return types.ListRequest{}, nil, fmt.Errorf("error parsing order by: %w", err)
	}

	/* // enable for debugging
	if orderBy.Fields != nil {
		b, _ := json.Marshal(orderBy.Fields)
		log.Printf("ordering: %v \n", string(b))
	}
	*/

	return types.ListRequest{
		Offset:                pageToken.Offset,
		PageSize:              request.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		OrderBy:               orderBy,
		IncludeFields:         request.GetIncludeFields(),
		ExcludeFields:         request.GetExcludeFields(),
	}, &pageToken, nil
}

func (s *server) ListUserTeam(ctx context.Context, request *pb.ListUserTeamRequest) (*pb.ListUserTeamResponse, error) {

	var err error
	req, pageToken, err := BuildListUserTeamRequest(ctx, request)
	if err != nil {

		return nil, err
	}

	// Query the storage.
	var result types.ListResponse
	if request.GetSkipCache() {
		result, err = s.core.UserTeam().List(ctx, req, user_teammodule.WithSkipCache())
	} else {
		result, err = s.core.UserTeam().List(ctx, req)
	}
	if err != nil {

		return nil, err
	}

	// Build the response.
	response := &pb.ListUserTeamResponse{
		UserTeam: pbmapper.UserTeamSliceToProto(result.UserTeam),
	}
	// Set the next page token.
	if result.HasNextPage {
		response.NextPageToken = pageToken.Next(request).String()
	}

	// Respond.
	return response, nil
}

func validatePageSizeForListUserTeam(request *pb.ListUserTeamRequest) error {
	// Handle request constraints.
	const (
		defaultPageSize = 10
	)
	switch {
	case request.PageSize < 0:
		return status.Errorf(codes.InvalidArgument, "page size is negative")
	case request.PageSize == 0:
		request.PageSize = defaultPageSize
	}
	return nil
}

func user_teamDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		// boolean values
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		//user_team

		filtering.DeclareIdent("uuid", filtering.TypeString),

		filtering.DeclareIdent("user_uuid", filtering.TypeString),

		filtering.DeclareIdent("user_email", filtering.TypeString),

		filtering.DeclareIdent("team_uuid", filtering.TypeString),

		filtering.DeclareEnumIdent("role", pb.UserTeamRole(0).Type()),

		filtering.DeclareIdent("review_required_structure", filtering.TypeBool),

		filtering.DeclareIdent("review_required_data", filtering.TypeBool),

		filtering.DeclareEnumIdent("status", pb.UserTeamStatus(0).Type()),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("created_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("updated_by_uuid", filtering.TypeString),
	)
	if err != nil {
		log.Printf("error creating declarations: %v", err)
	}
	return declarations
}
