// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"fmt"
	"log"
	//"encoding/json"

	change_requestmodule "github.com/nuzur/nem/core/module/change_request"
	"github.com/nuzur/nem/core/module/change_request/types"
	pb "github.com/nuzur/nem/idl/gen"

	pbmapper "github.com/nuzur/nem/idl/mapper"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"
	"go.einride.tech/aip/pagination"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func BuildListChangeRequestRequest(ctx context.Context, request *pb.ListChangeRequestRequest) (types.ListRequest, *pagination.PageToken, error) {
	err := validatePageSizeForListChangeRequest(request)
	if err != nil {
		return types.ListRequest{}, nil, err
	}

	// Use pagination.PageToken for offset-based page tokens.
	pageToken, err := pagination.ParsePageToken(request)
	if err != nil {
		return types.ListRequest{}, nil, status.Errorf(codes.InvalidArgument, "invalid page token")
	}

	// parse filters
	declarations := change_requestDeclarations()
	filter, err := filtering.ParseFilter(request, declarations)
	if err != nil {
		return types.ListRequest{}, nil, fmt.Errorf("error parsing filter: %w", err)
	}

	/* // enable for debugging
	if filter.CheckedExpr != nil {
		b, _ := json.Marshal(filter.CheckedExpr.Expr)
		log.Printf("filtering: %v \n", string(b))
	}
	*/

	orderBy, err := ordering.ParseOrderBy(request)
	if err != nil {
		return types.ListRequest{}, nil, fmt.Errorf("error parsing order by: %w", err)
	}

	/* // enable for debugging
	if orderBy.Fields != nil {
		b, _ := json.Marshal(orderBy.Fields)
		log.Printf("ordering: %v \n", string(b))
	}
	*/

	return types.ListRequest{
		Offset:                pageToken.Offset,
		PageSize:              request.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		OrderBy:               orderBy,
		IncludeFields:         request.GetIncludeFields(),
		ExcludeFields:         request.GetExcludeFields(),
	}, &pageToken, nil
}

func (s *server) ListChangeRequest(ctx context.Context, request *pb.ListChangeRequestRequest) (*pb.ListChangeRequestResponse, error) {

	var err error
	req, pageToken, err := BuildListChangeRequestRequest(ctx, request)
	if err != nil {

		return nil, err
	}

	// Query the storage.
	var result types.ListResponse
	if request.GetSkipCache() {
		result, err = s.core.ChangeRequest().List(ctx, req, change_requestmodule.WithSkipCache())
	} else {
		result, err = s.core.ChangeRequest().List(ctx, req)
	}
	if err != nil {

		return nil, err
	}

	// Build the response.
	response := &pb.ListChangeRequestResponse{
		ChangeRequest: pbmapper.ChangeRequestSliceToProto(result.ChangeRequest),
	}
	// Set the next page token.
	if result.HasNextPage {
		response.NextPageToken = pageToken.Next(request).String()
	}

	// Respond.
	return response, nil
}

func validatePageSizeForListChangeRequest(request *pb.ListChangeRequestRequest) error {
	// Handle request constraints.
	const (
		defaultPageSize = 10
	)
	switch {
	case request.PageSize < 0:
		return status.Errorf(codes.InvalidArgument, "page size is negative")
	case request.PageSize == 0:
		request.PageSize = defaultPageSize
	}
	return nil
}

func change_requestDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		// boolean values
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		//data_change_type_config_update_field

		filtering.DeclareIdent("data_change_type_config_update_field.field_uuid", filtering.TypeString),

		filtering.DeclareIdent("data_change_type_config_update_field.current_value", filtering.TypeString),

		filtering.DeclareIdent("data_change_type_config_update_field.new_value", filtering.TypeString),

		//data_change_field_value

		filtering.DeclareIdent("data_change_field_value.field_uuid", filtering.TypeString),

		filtering.DeclareIdent("data_change_field_value.value", filtering.TypeString),

		//data_change_type_config_update

		filtering.DeclareIdent("data_change_type_config_update.entity_uuid", filtering.TypeString),

		filtering.DeclareIdent("data_change_type_config_update.created_at", filtering.TypeTimestamp),

		//data_change_type_config_create

		filtering.DeclareIdent("data_change_type_config_create.entity_uuid", filtering.TypeString),

		filtering.DeclareIdent("data_change_type_config_create.created_at", filtering.TypeTimestamp),

		//data_change_type_config_delete

		filtering.DeclareIdent("data_change_type_config_delete.entity_uuid", filtering.TypeString),

		filtering.DeclareIdent("data_change_type_config_delete.created_at", filtering.TypeTimestamp),

		//data_change_type_config

		//change_request_data_change

		filtering.DeclareIdent("change_request_data_change.uuid", filtering.TypeString),

		filtering.DeclareEnumIdent("change_request_data_change.data_change_type", pb.ChangeRequestDataChangeDataChangeType(0).Type()),

		filtering.DeclareIdent("change_request_data_change.order", filtering.TypeInt),

		//change_request_metadata_data

		filtering.DeclareIdent("change_request_metadata_data.store_uuid", filtering.TypeString),

		filtering.DeclareIdent("change_request_metadata_data.connection_uuid", filtering.TypeString),

		filtering.DeclareIdent("change_request_metadata_data.schema", filtering.TypeString),

		//change_request_metadata

		//change_request_review

		filtering.DeclareIdent("change_request_review.uuid", filtering.TypeString),

		filtering.DeclareIdent("change_request_review.user_uuid", filtering.TypeString),

		filtering.DeclareIdent("change_request_review.comment", filtering.TypeString),

		filtering.DeclareEnumIdent("change_request_review.response", pb.ChangeRequestReviewResponse(0).Type()),

		filtering.DeclareIdent("change_request_review.created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("change_request_review.updated_at", filtering.TypeTimestamp),

		//change_request_scope_config_local

		filtering.DeclareIdent("change_request_scope_config_local.agent_uuid", filtering.TypeString),

		filtering.DeclareIdent("change_request_scope_config_local.agent_connection_uuid", filtering.TypeString),

		//change_request_scope_config_remote

		filtering.DeclareIdent("change_request_scope_config_remote.team_uuid", filtering.TypeString),

		filtering.DeclareIdent("change_request_scope_config_remote.store_uuid", filtering.TypeString),

		filtering.DeclareIdent("change_request_scope_config_remote.connection_uuid", filtering.TypeString),

		//change_request_scope_config

		//change_request

		filtering.DeclareIdent("uuid", filtering.TypeString),

		filtering.DeclareIdent("version", filtering.TypeInt),

		filtering.DeclareIdent("title", filtering.TypeString),

		filtering.DeclareIdent("description", filtering.TypeString),

		filtering.DeclareIdent("project_uuid", filtering.TypeString),

		filtering.DeclareIdent("project_version_uuid", filtering.TypeString),

		filtering.DeclareEnumIdent("change_type", pb.ChangeRequestChangeType(0).Type()),

		filtering.DeclareEnumIdent("review_status", pb.ChangeRequestReviewStatus(0).Type()),

		filtering.DeclareIdent("owner_uuid", filtering.TypeString),

		filtering.DeclareEnumIdent("status", pb.ChangeRequestStatus(0).Type()),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("created_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("updated_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("ai_generated", filtering.TypeBool),

		filtering.DeclareEnumIdent("scope", pb.ChangeRequestScope(0).Type()),
	)
	if err != nil {
		log.Printf("error creating declarations: %v", err)
	}
	return declarations
}
