// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"fmt"
	"log"
	//"encoding/json"

	extensionmodule "github.com/nuzur/nem/core/module/extension"
	"github.com/nuzur/nem/core/module/extension/types"
	pb "github.com/nuzur/nem/idl/gen"

	pbmapper "github.com/nuzur/nem/idl/mapper"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"
	"go.einride.tech/aip/pagination"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func BuildListExtensionRequest(ctx context.Context, request *pb.ListExtensionRequest) (types.ListRequest, *pagination.PageToken, error) {
	err := validatePageSizeForListExtension(request)
	if err != nil {
		return types.ListRequest{}, nil, err
	}

	// Use pagination.PageToken for offset-based page tokens.
	pageToken, err := pagination.ParsePageToken(request)
	if err != nil {
		return types.ListRequest{}, nil, status.Errorf(codes.InvalidArgument, "invalid page token")
	}

	// parse filters
	declarations := extensionDeclarations()
	filter, err := filtering.ParseFilter(request, declarations)
	if err != nil {
		return types.ListRequest{}, nil, fmt.Errorf("error parsing filter: %w", err)
	}

	/* // enable for debugging
	if filter.CheckedExpr != nil {
		b, _ := json.Marshal(filter.CheckedExpr.Expr)
		log.Printf("filtering: %v \n", string(b))
	}
	*/

	orderBy, err := ordering.ParseOrderBy(request)
	if err != nil {
		return types.ListRequest{}, nil, fmt.Errorf("error parsing order by: %w", err)
	}

	/* // enable for debugging
	if orderBy.Fields != nil {
		b, _ := json.Marshal(orderBy.Fields)
		log.Printf("ordering: %v \n", string(b))
	}
	*/

	return types.ListRequest{
		Offset:                pageToken.Offset,
		PageSize:              request.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		OrderBy:               orderBy,
		IncludeFields:         request.GetIncludeFields(),
		ExcludeFields:         request.GetExcludeFields(),
	}, &pageToken, nil
}

func (s *server) ListExtension(ctx context.Context, request *pb.ListExtensionRequest) (*pb.ListExtensionResponse, error) {

	var err error
	req, pageToken, err := BuildListExtensionRequest(ctx, request)
	if err != nil {

		return nil, err
	}

	// Query the storage.
	var result types.ListResponse
	if request.GetSkipCache() {
		result, err = s.core.Extension().List(ctx, req, extensionmodule.WithSkipCache())
	} else {
		result, err = s.core.Extension().List(ctx, req)
	}
	if err != nil {

		return nil, err
	}

	// Build the response.
	response := &pb.ListExtensionResponse{
		Extension: pbmapper.ExtensionSliceToProto(result.Extension),
	}
	// Set the next page token.
	if result.HasNextPage {
		response.NextPageToken = pageToken.Next(request).String()
	}

	// Respond.
	return response, nil
}

func validatePageSizeForListExtension(request *pb.ListExtensionRequest) error {
	// Handle request constraints.
	const (
		defaultPageSize = 10
	)
	switch {
	case request.PageSize < 0:
		return status.Errorf(codes.InvalidArgument, "page size is negative")
	case request.PageSize == 0:
		request.PageSize = defaultPageSize
	}
	return nil
}

func extensionDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		// boolean values
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		//visibility

		filtering.DeclareIdent("visibility.uuid", filtering.TypeString),

		filtering.DeclareIdent("visibility.description", filtering.TypeString),

		filtering.DeclareIdent("visibility.organization_uuids", filtering.TypeString),

		filtering.DeclareIdent("visibility.team_uuids", filtering.TypeString),

		filtering.DeclareIdent("visibility.user_uuids", filtering.TypeString),

		filtering.DeclareEnumIdent("visibility.roles", pb.VisibilityRoles(0).Type()),

		filtering.DeclareIdent("visibility.created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("visibility.updated_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("visibility.created_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("visibility.updated_by_uuid", filtering.TypeString),

		//extension

		filtering.DeclareIdent("uuid", filtering.TypeString),

		filtering.DeclareIdent("version", filtering.TypeInt),

		filtering.DeclareIdent("identifier", filtering.TypeString),

		filtering.DeclareIdent("display_name", filtering.TypeString),

		filtering.DeclareIdent("display_author_name", filtering.TypeString),

		filtering.DeclareIdent("description", filtering.TypeString),

		filtering.DeclareIdent("url", filtering.TypeString),

		filtering.DeclareIdent("verified", filtering.TypeBool),

		filtering.DeclareIdent("repository", filtering.TypeString),

		filtering.DeclareEnumIdent("extension_type", pb.ExtensionType(0).Type()),

		filtering.DeclareIdent("tags", filtering.TypeString),

		filtering.DeclareIdent("pro", filtering.TypeBool),

		filtering.DeclareIdent("public", filtering.TypeBool),

		filtering.DeclareEnumIdent("status", pb.ExtensionStatus(0).Type()),

		filtering.DeclareIdent("owner_uuid", filtering.TypeString),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("created_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("updated_by_uuid", filtering.TypeString),
	)
	if err != nil {
		log.Printf("error creating declarations: %v", err)
	}
	return declarations
}
