// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	extensionmodule "github.com/nuzur/nem/core/module/extension"
	"github.com/nuzur/nem/core/module/extension/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"

	"go.einride.tech/aip/fieldmask"
	"strings"
)

func (s *server) UpdateExtension(ctx context.Context, req *pb.UpdateExtensionRequest) (*pb.Extension, error) {

	if req.Extension.Uuid == "" {
		return nil, errors.New("please provide a valid UUID to update")
	}

	if req.Extension.Version == 0 {
		return nil, errors.New("please provide a valid version to update")
	}

	err := fieldmask.Validate(req.UpdateMask, req.GetExtension())
	if err != nil {

		return nil, err
	}

	isFull := fieldmask.IsFullReplacement(req.UpdateMask)

	if !isFull && req.UpdateMask != nil {

		if !strings.Contains(req.UpdateMask.String(), "uuid") {
			req.UpdateMask.Append(req.GetExtension(), "uuid")
		}

		if !strings.Contains(req.UpdateMask.String(), "version") {
			req.UpdateMask.Append(req.GetExtension(), "version")
		}

		pkEntity := pbmapper.ExtensionFromProto(req.GetExtension())
		existingRes, err := s.core.Extension().FetchExtensionByUUID(ctx,
			types.FetchExtensionByUUIDRequest{
				UUID: pkEntity.UUID,
			},
			extensionmodule.WithSkipCache(),
		)
		if err != nil {

			return nil, err
		}
		if len(existingRes.Results) == 0 {
			return nil, errors.New("entity not found")
		}

		merged := pbmapper.ExtensionToProto(existingRes.Results[0])
		fieldmask.Update(req.UpdateMask, merged, req.GetExtension())
		req = &pb.UpdateExtensionRequest{Extension: merged, UpdateMask: req.UpdateMask}
	}

	res, err := s.core.Extension().Update(ctx, types.UpsertRequest{
		Extension: pbmapper.ExtensionFromProto(req.GetExtension()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.Extension().FetchExtensionByUUID(ctx, types.FetchExtensionByUUIDRequest(res), extensionmodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.ExtensionToProto(fetchRes.Results[0]), nil
}
