// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	membershipmodule "github.com/nuzur/nem/core/module/membership"
	"github.com/nuzur/nem/core/module/membership/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"

	"go.einride.tech/aip/fieldmask"
	"strings"
)

func (s *server) UpdateMembership(ctx context.Context, req *pb.UpdateMembershipRequest) (*pb.Membership, error) {

	if req.Membership.Uuid == "" {
		return nil, errors.New("please provide a valid UUID to update")
	}

	err := fieldmask.Validate(req.UpdateMask, req.GetMembership())
	if err != nil {

		return nil, err
	}

	isFull := fieldmask.IsFullReplacement(req.UpdateMask)

	if !isFull && req.UpdateMask != nil {

		if !strings.Contains(req.UpdateMask.String(), "uuid") {
			req.UpdateMask.Append(req.GetMembership(), "uuid")
		}

		pkEntity := pbmapper.MembershipFromProto(req.GetMembership())
		existingRes, err := s.core.Membership().FetchMembershipByUUID(ctx,
			types.FetchMembershipByUUIDRequest{
				UUID: pkEntity.UUID,
			},
			membershipmodule.WithSkipCache(),
		)
		if err != nil {

			return nil, err
		}
		if len(existingRes.Results) == 0 {
			return nil, errors.New("entity not found")
		}

		merged := pbmapper.MembershipToProto(existingRes.Results[0])
		fieldmask.Update(req.UpdateMask, merged, req.GetMembership())
		req = &pb.UpdateMembershipRequest{Membership: merged, UpdateMask: req.UpdateMask}
	}

	res, err := s.core.Membership().Update(ctx, types.UpsertRequest{
		Membership: pbmapper.MembershipFromProto(req.GetMembership()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.Membership().FetchMembershipByUUID(ctx, types.FetchMembershipByUUIDRequest(res), membershipmodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.MembershipToProto(fetchRes.Results[0]), nil
}
