// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	deployment_revisionmodule "github.com/nuzur/nem/core/module/deployment_revision"
	"github.com/nuzur/nem/core/module/deployment_revision/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"

	"go.einride.tech/aip/fieldmask"
	"strings"
)

func (s *server) UpdateDeploymentRevision(ctx context.Context, req *pb.UpdateDeploymentRevisionRequest) (*pb.DeploymentRevision, error) {

	if req.DeploymentRevision.Uuid == "" {
		return nil, errors.New("please provide a valid UUID to update")
	}

	err := fieldmask.Validate(req.UpdateMask, req.GetDeploymentRevision())
	if err != nil {

		return nil, err
	}

	isFull := fieldmask.IsFullReplacement(req.UpdateMask)

	if !isFull && req.UpdateMask != nil {

		if !strings.Contains(req.UpdateMask.String(), "uuid") {
			req.UpdateMask.Append(req.GetDeploymentRevision(), "uuid")
		}

		pkEntity := pbmapper.DeploymentRevisionFromProto(req.GetDeploymentRevision())
		existingRes, err := s.core.DeploymentRevision().FetchDeploymentRevisionByUUID(ctx,
			types.FetchDeploymentRevisionByUUIDRequest{
				UUID: pkEntity.UUID,
			},
			deployment_revisionmodule.WithSkipCache(),
		)
		if err != nil {

			return nil, err
		}
		if len(existingRes.Results) == 0 {
			return nil, errors.New("entity not found")
		}

		merged := pbmapper.DeploymentRevisionToProto(existingRes.Results[0])
		fieldmask.Update(req.UpdateMask, merged, req.GetDeploymentRevision())
		req = &pb.UpdateDeploymentRevisionRequest{DeploymentRevision: merged, UpdateMask: req.UpdateMask}
	}

	res, err := s.core.DeploymentRevision().Update(ctx, types.UpsertRequest{
		DeploymentRevision: pbmapper.DeploymentRevisionFromProto(req.GetDeploymentRevision()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.DeploymentRevision().FetchDeploymentRevisionByUUID(ctx, types.FetchDeploymentRevisionByUUIDRequest(res), deployment_revisionmodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.DeploymentRevisionToProto(fetchRes.Results[0]), nil
}
