// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	project_versionmodule "github.com/nuzur/nem/core/module/project_version"
	"github.com/nuzur/nem/core/module/project_version/types"
	pb "github.com/nuzur/nem/idl/gen"
	pbmapper "github.com/nuzur/nem/idl/mapper"

	"go.einride.tech/aip/fieldmask"
	"strings"
)

func (s *server) UpdateProjectVersion(ctx context.Context, req *pb.UpdateProjectVersionRequest) (*pb.ProjectVersion, error) {

	if req.ProjectVersion.Uuid == "" {
		return nil, errors.New("please provide a valid UUID to update")
	}

	if req.ProjectVersion.Version == 0 {
		return nil, errors.New("please provide a valid version to update")
	}

	err := fieldmask.Validate(req.UpdateMask, req.GetProjectVersion())
	if err != nil {

		return nil, err
	}

	isFull := fieldmask.IsFullReplacement(req.UpdateMask)

	if !isFull && req.UpdateMask != nil {

		if !strings.Contains(req.UpdateMask.String(), "uuid") {
			req.UpdateMask.Append(req.GetProjectVersion(), "uuid")
		}

		if !strings.Contains(req.UpdateMask.String(), "version") {
			req.UpdateMask.Append(req.GetProjectVersion(), "version")
		}

		pkEntity := pbmapper.ProjectVersionFromProto(req.GetProjectVersion())
		existingRes, err := s.core.ProjectVersion().FetchProjectVersionByUUID(ctx,
			types.FetchProjectVersionByUUIDRequest{
				UUID: pkEntity.UUID,
			},
			project_versionmodule.WithSkipCache(),
		)
		if err != nil {

			return nil, err
		}
		if len(existingRes.Results) == 0 {
			return nil, errors.New("entity not found")
		}

		merged := pbmapper.ProjectVersionToProto(existingRes.Results[0])
		fieldmask.Update(req.UpdateMask, merged, req.GetProjectVersion())
		req = &pb.UpdateProjectVersionRequest{ProjectVersion: merged, UpdateMask: req.UpdateMask}
	}

	res, err := s.core.ProjectVersion().Update(ctx, types.UpsertRequest{
		ProjectVersion: pbmapper.ProjectVersionFromProto(req.GetProjectVersion()),
	})
	if err != nil {

		return nil, err
	}

	fetchRes, err := s.core.ProjectVersion().FetchProjectVersionByUUID(ctx, types.FetchProjectVersionByUUIDRequest(res), project_versionmodule.WithSkipCache())
	if err != nil {

		return nil, err
	}

	if len(fetchRes.Results) == 0 {
		err := errors.New("error fetching entity")

		return nil, err
	}

	return pbmapper.ProjectVersionToProto(fetchRes.Results[0]), nil
}
