// Code generated by nuzur go-code-gen. DO NOT EDIT.

package deployment_database

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/enums"

	"github.com/nuzur/nem/core/entity/mapper"
)

type DeploymentDatabase struct {
	Engine         enums.LocalAgentConnectionDbType `json:"engine"`
	Location       enums.DeploymentDbLocation       `json:"location"`
	Port           null.Int64                       `json:"port"`
	Schema         null.String                      `json:"schema"`
	ConnectionUUID *uuid.UUID                       `json:"connection_uuid"`
}

func (e DeploymentDatabase) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e DeploymentDatabase) PrimaryKeyValues() []string {
	return []string{}
}

func DeploymentDatabaseFromJSON(data json.RawMessage) DeploymentDatabase {
	entity := DeploymentDatabase{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error DeploymentDatabaseFromJSON: %v\n", err2)
		}
	}
	return entity
}

func DeploymentDatabaseSliceFromJSON(data json.RawMessage) []DeploymentDatabase {
	entity := []DeploymentDatabase{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []DeploymentDatabase{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := DeploymentDatabase{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error DeploymentDatabaseSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e DeploymentDatabase) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DeploymentDatabaseToJSON: %v\n", err)
	}
	return res
}

func DeploymentDatabaseToJSON(e DeploymentDatabase) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DeploymentDatabaseToJSON: %v\n", err)
	}
	return res
}

func DeploymentDatabaseSliceToJSON(e []DeploymentDatabase) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DeploymentDatabaseSliceToJSON: %v\n", err)
	}
	return res
}
