// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/membership"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchMembershipByOwnerUUIDRequest struct {
	OwnerUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchMembershipByOwnerUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("owner_uuid", r.OwnerUUID.String())

	return nil
}

type FetchMembershipByOwnerUUIDResponse struct {
	Results []main_entity.Membership
}
