// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/membership"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Membership main_entity.Membership
}

type UpsertResponse struct {
	UUID uuid.UUID
}
