// Code generated by nuzur go-code-gen. DO NOT EDIT.

// Package validation provides the per-type value validators used by each
// entity's generated Validate() method. It mirrors the change-request data
// validation enforced server-side in product/module/datavalidation
// (github.com/nuzur/nem-adjacent product module): the rule logic here is a
// direct port so data written through this service's API is held to the same
// schema rules the change-request pipeline enforces.
//
// IMPORTANT: keep these rules in sync with product/module/datavalidation.
// Unlike that package (which validates stringly-typed change-request values),
// these validators operate on the already-typed Go values of the entity
// structs, so input-format-only checks (UUID parseability, float separator /
// decimal-count, temporal parsing) are unnecessary and intentionally omitted.
package validation

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"time"
)

var (
	emailRegex    = regexp.MustCompile(`^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$`)
	phoneRegex    = regexp.MustCompile(`^\+?[1-9]\d{1,14}$`)
	locationRegex = regexp.MustCompile(`^-?\d+(\.\d+)?,-?\d+(\.\d+)?$`)
	colorRegex    = regexp.MustCompile(`^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$`)
)

// Error aggregates every problem found while validating an entity. Mirrors
// datavalidation.ValidationError so callers get every issue at once.
type Error struct {
	Issues []string
}

func (e *Error) Error() string {
	return "data validation failed: " + strings.Join(e.Issues, "; ")
}

// Collector accumulates validation issues, each prefixed with an
// entity.field path so the message is actionable on its own.
type Collector struct {
	issues []string
}

func NewCollector() *Collector {
	return &Collector{}
}

// Require records that a required field is missing.
func (c *Collector) Require(path string) {
	c.issues = append(c.issues, path+": field is required")
}

// Field records err (if non-nil) against the given entity.field path.
func (c *Collector) Field(path string, err error) {
	if err != nil {
		c.issues = append(c.issues, path+": "+err.Error())
	}
}

// Merge folds the issues of a nested entity's *Error into this collector,
// prefixing each with path so nested problems are addressable (e.g.
// "order.items[0].price: ...").
func (c *Collector) Merge(path string, err error) {
	if err == nil {
		return
	}
	var ve *Error
	if errors.As(err, &ve) {
		for _, iss := range ve.Issues {
			c.issues = append(c.issues, path+"."+iss)
		}
		return
	}
	c.issues = append(c.issues, path+": "+err.Error())
}

// Result returns a non-nil *Error if any issues were collected, otherwise nil.
func (c *Collector) Result() error {
	if len(c.issues) == 0 {
		return nil
	}
	return &Error{Issues: c.issues}
}

// String validates a string against a min/max length and optional regex.
func String(v string, minSize, maxSize int64, regex string) error {
	length := int64(len([]rune(v)))
	if maxSize > 0 && length > maxSize {
		return fmt.Errorf("value is longer than the maximum size of %d", maxSize)
	}
	if minSize > 0 && length < minSize {
		return fmt.Errorf("value is shorter than the minimum size of %d", minSize)
	}
	if regex != "" {
		re, err := regexp.Compile(regex)
		if err != nil {
			return fmt.Errorf("field has an invalid regex validation %q", regex)
		}
		if !re.MatchString(v) {
			return fmt.Errorf("value does not match the required format %q", regex)
		}
	}
	return nil
}

// Integer validates an integer against optional limits, negativity and size bounds.
func Integer(v int64, enableLimits bool, minValue, maxValue int64, minInclusive, maxInclusive, allowNegatives bool, hasSize bool, sizeMin, sizeMax int64) error {
	if enableLimits {
		minV := minValue
		maxV := maxValue
		if !minInclusive {
			minV++
		}
		if !maxInclusive {
			maxV--
		}
		if minV != maxV && (v < minV || v > maxV) {
			return fmt.Errorf("value %d is out of range [%d, %d]", v, minV, maxV)
		}
	}
	if !allowNegatives && v < 0 {
		return fmt.Errorf("value %d cannot be negative", v)
	}
	if hasSize {
		if v < sizeMin || v > sizeMax {
			return fmt.Errorf("value %d is out of range for its size [%d, %d]", v, sizeMin, sizeMax)
		}
	}
	return nil
}

// Float validates a float/decimal against optional limits and negativity.
func Float(v float64, enableLimits bool, minValue, maxValue float64, minInclusive, maxInclusive, allowNegatives bool) error {
	if enableLimits {
		minV := minValue
		maxV := maxValue
		if !minInclusive {
			minV++
		}
		if !maxInclusive {
			maxV--
		}
		if minV != maxV && (v < minV || v > maxV) {
			return fmt.Errorf("value %v is out of range [%v, %v]", v, minV, maxV)
		}
	}
	if !allowNegatives && v < 0 {
		return fmt.Errorf("value %v cannot be negative", v)
	}
	return nil
}

// Email validates an email address and optional allow/exclude domain lists.
func Email(v string, allowDomains, excludeDomains []string) error {
	if !emailRegex.MatchString(strings.ToLower(v)) {
		return fmt.Errorf("%q is not a valid email address", v)
	}
	at := strings.LastIndex(v, "@")
	if at < 0 || at == len(v)-1 {
		return fmt.Errorf("%q is not a valid email address", v)
	}
	domain := v[at+1:]
	if len(allowDomains) > 0 && !hasAnySuffix(domain, allowDomains) {
		return fmt.Errorf("email domain %q is not allowed", domain)
	}
	if len(excludeDomains) > 0 && hasAnySuffix(domain, excludeDomains) {
		return fmt.Errorf("email domain %q is not allowed", domain)
	}
	return nil
}

// URL validates an http/https url and optional scheme/extension/domain rules.
func URL(v string, httpsRequired bool, allowedExtensions, allowDomains, excludeDomains []string) error {
	u, err := url.Parse(v)
	if err != nil {
		return fmt.Errorf("%q is not a valid url", v)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return fmt.Errorf("url %q must use http or https", v)
	}
	if u.Hostname() == "" {
		return fmt.Errorf("url %q has no hostname", v)
	}
	if httpsRequired && u.Scheme != "https" {
		return fmt.Errorf("url %q must use https", v)
	}
	if len(allowedExtensions) > 0 {
		if ext := urlFileExtension(v); ext != "" && !slices.Contains(allowedExtensions, ext) {
			return fmt.Errorf("url extension %q is not allowed", ext)
		}
	}
	if len(allowDomains) > 0 && !hasAnySuffix(u.Hostname(), allowDomains) {
		return fmt.Errorf("url domain %q is not allowed", u.Hostname())
	}
	if len(excludeDomains) > 0 && hasAnySuffix(u.Hostname(), excludeDomains) {
		return fmt.Errorf("url domain %q is not allowed", u.Hostname())
	}
	return nil
}

// Phone validates an E.164-style phone number.
func Phone(v string) error {
	if !phoneRegex.MatchString(v) {
		return fmt.Errorf("%q is not a valid phone number", v)
	}
	return nil
}

// Location validates a "latitude,longitude" string.
func Location(v string) error {
	if !locationRegex.MatchString(v) {
		return fmt.Errorf("%q is not a valid location (expected \"latitude,longitude\")", v)
	}
	return nil
}

// Color validates a hex color string.
func Color(v string) error {
	if !colorRegex.MatchString(v) {
		return fmt.Errorf("%q is not a valid hex color", v)
	}
	return nil
}

// Date validates optional future/past constraints on a date-bearing value.
func Date(v time.Time, enforceFuture, enforcePast bool) error {
	if !enforceFuture && !enforcePast {
		return nil
	}
	today := time.Now().UTC().Truncate(24 * time.Hour)
	day := v.UTC().Truncate(24 * time.Hour)
	if enforceFuture && day.Before(today) {
		return fmt.Errorf("date %q must be in the future", v.Format(time.RFC3339))
	}
	if enforcePast && day.After(today) {
		return fmt.Errorf("date %q must be in the past", v.Format(time.RFC3339))
	}
	return nil
}

// EnumMember validates that v is one of the allowed numeric enum values.
func EnumMember(v int64, allowed []int64, name string) error {
	if slices.Contains(allowed, v) {
		return nil
	}
	return fmt.Errorf("%d is not a valid value for enum %q", v, name)
}

// JSONBytes validates that a raw JSON value is well-formed.
func JSONBytes(v []byte) error {
	if len(v) == 0 {
		return nil
	}
	if !json.Valid(v) {
		return fmt.Errorf("value is not valid JSON")
	}
	return nil
}

// Count validates the number of elements in an array against min/max bounds.
func Count(n int, minElements, maxElements int64) error {
	if maxElements > 0 && int64(n) > maxElements {
		return fmt.Errorf("array has more than the maximum of %d elements", maxElements)
	}
	if minElements > 0 && int64(n) < minElements {
		return fmt.Errorf("array has fewer than the minimum of %d elements", minElements)
	}
	return nil
}

// IsZeroEntity reports whether a nested entity value equals its zero value,
// compared via its generated JSON String(). Used to treat an unset one-to-one
// dependent record as absent (typed structs cannot otherwise distinguish
// "not provided" from "provided empty").
func IsZeroEntity(v interface{ String() string }) bool {
	z, ok := reflect.New(reflect.TypeOf(v)).Elem().Interface().(interface{ String() string })
	if !ok {
		return false
	}
	return v.String() == z.String()
}

// Index returns an indexed path segment (e.g. "order.items[2]") for reporting
// element- or nested-record-level issues.
func Index(path string, i int) string {
	return path + "[" + strconv.Itoa(i) + "]"
}

// Unique validates that all elements of a slice are distinct.
func Unique[T comparable](vs []T) error {
	seen := make(map[T]struct{}, len(vs))
	for _, v := range vs {
		if _, ok := seen[v]; ok {
			return fmt.Errorf("array elements must be unique")
		}
		seen[v] = struct{}{}
	}
	return nil
}

func hasAnySuffix(s string, suffixes []string) bool {
	for _, suf := range suffixes {
		if suf != "" && strings.HasSuffix(s, suf) {
			return true
		}
	}
	return false
}

func urlFileExtension(rawURL string) string {
	base := rawURL
	if idx := strings.IndexAny(base, "#?"); idx >= 0 {
		base = base[:idx]
	}
	idx := strings.LastIndex(base, ".")
	if idx < 0 || idx == len(base)-1 {
		return ""
	}
	if strings.ContainsAny(base[idx:], "/") {
		return ""
	}
	return strings.TrimSpace(base[idx+1:])
}
