// Code generated by nuzur go-code-gen. DO NOT EDIT.

package extension

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this Extension against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Extension) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("extension.uuid")
	}
	if e.Identifier == "" {
		c.Require("extension.identifier")
	} else {
		c.Field("extension.identifier", validation.String(e.Identifier, 0, 255, ""))

	}
	if e.DisplayName.Valid && e.DisplayName.String != "" {
		c.Field("extension.display_name", validation.String(e.DisplayName.String, 0, 255, ""))

	}
	if e.DisplayAuthorName.Valid && e.DisplayAuthorName.String != "" {
		c.Field("extension.display_author_name", validation.String(e.DisplayAuthorName.String, 0, 255, ""))

	}
	if e.Description.Valid && e.Description.String != "" {
		c.Field("extension.description", validation.String(e.Description.String, 0, 255, ""))

	}
	if e.URL.Valid && e.URL.String != "" {
		c.Field("extension.url", validation.String(e.URL.String, 0, 255, ""))

	}
	if e.Repository == "" {
		c.Require("extension.repository")
	} else {
		c.Field("extension.repository", validation.String(e.Repository, 0, 255, ""))

	}
	if e.ExtensionType.ToInt64() == 0 {
		c.Require("extension.extension_type")
	} else {
		c.Field("extension.extension_type", validation.EnumMember(e.ExtensionType.ToInt64(), []int64{0, 1, 2, 3}, "extension_type"))

	}
	if len(e.Tags) > 0 {
		c.Field("extension.tags", validation.Unique(e.Tags))
		for i, el := range e.Tags {
			c.Field(validation.Index("extension.tags", i), validation.String(el, 0, 0, ""))
		}

	}
	for i, item := range e.Visibility {
		c.Merge(validation.Index("extension.visibility", i), item.Validate())
	}
	if e.Status.ToInt64() == 0 {
		c.Require("extension.status")
	} else {
		c.Field("extension.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "extension_status"))

	}
	if e.OwnerUUID.IsNil() {
		c.Require("extension.owner_uuid")
	}
	if e.CreatedByUUID.IsNil() {
		c.Require("extension.created_by_uuid")
	}
	if e.UpdatedByUUID.IsNil() {
		c.Require("extension.updated_by_uuid")
	}

	return c.Result()
}
