// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/ai_usage"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAiUsageByProjectUuidRequest struct {
	ProjectUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAiUsageByProjectUuidRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("project_uuid", r.ProjectUUID.String())

	return nil
}

type FetchAiUsageByProjectUuidResponse struct {
	Results []main_entity.AiUsage
}
