// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/ai_usage"

	"github.com/nuzur/nem/enums"
	"go.uber.org/zap/zapcore"
)

type FetchAiUsageByContextRequest struct {
	Context enums.AiUsageContext

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAiUsageByContextRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchAiUsageByContextResponse struct {
	Results []main_entity.AiUsage
}
