// Code generated by nuzur go-code-gen. DO NOT EDIT.

package file_storage_config

import (
	"encoding/json"
	"log"

	"github.com/nuzur/nem/core/entity/file_object_storage_config"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FileStorageConfig struct {
	ObjectStore file_object_storage_config.FileObjectStorageConfig `json:"object_store"`
}

func (e FileStorageConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FileStorageConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FileStorageConfigFromJSON(data json.RawMessage) FileStorageConfig {
	entity := FileStorageConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FileStorageConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FileStorageConfigSliceFromJSON(data json.RawMessage) []FileStorageConfig {
	entity := []FileStorageConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FileStorageConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FileStorageConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FileStorageConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FileStorageConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FileStorageConfigToJSON: %v\n", err)
	}
	return res
}

func FileStorageConfigToJSON(e FileStorageConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FileStorageConfigToJSON: %v\n", err)
	}
	return res
}

func FileStorageConfigSliceToJSON(e []FileStorageConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FileStorageConfigSliceToJSON: %v\n", err)
	}
	return res
}
