// Code generated by nuzur go-code-gen. DO NOT EDIT.

package tcp_ip_ssh_connection_type_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this TcpIpSshConnectionTypeConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e TcpIpSshConnectionTypeConfig) Validate() error {
	c := validation.NewCollector()
	if e.SshHostname == "" {
		c.Require("tcp_ip_ssh_connection_type_config.ssh_hostname")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.ssh_hostname", validation.String(e.SshHostname, 0, 255, ""))

	}
	if e.SshUsername == "" {
		c.Require("tcp_ip_ssh_connection_type_config.ssh_username")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.ssh_username", validation.String(e.SshUsername, 0, 255, ""))

	}
	if e.SshPassword == "" {
		c.Require("tcp_ip_ssh_connection_type_config.ssh_password")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.ssh_password", validation.String(e.SshPassword, 0, 255, ""))

	}
	if e.SshKeyFile == "" {
		c.Require("tcp_ip_ssh_connection_type_config.ssh_key_file")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.ssh_key_file", validation.String(e.SshKeyFile, 0, 255, ""))

	}
	if e.Hostname == "" {
		c.Require("tcp_ip_ssh_connection_type_config.hostname")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.hostname", validation.String(e.Hostname, 0, 255, ""))

	}
	if e.Port == "" {
		c.Require("tcp_ip_ssh_connection_type_config.port")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.port", validation.String(e.Port, 0, 255, ""))

	}
	if e.Username == "" {
		c.Require("tcp_ip_ssh_connection_type_config.username")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.username", validation.String(e.Username, 0, 255, ""))

	}
	if e.Password == "" {
		c.Require("tcp_ip_ssh_connection_type_config.password")
	} else {
		c.Field("tcp_ip_ssh_connection_type_config.password", validation.String(e.Password, 0, 255, ""))

	}

	return c.Result()
}
