// Code generated by nuzur go-code-gen. DO NOT EDIT.

package automation_event

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type AutomationEvent struct {
	UUID              uuid.UUID                   `json:"uuid"`
	AutomationUUID    uuid.UUID                   `json:"automation_uuid"`
	ProjectUUID       uuid.UUID                   `json:"project_uuid"`
	ChangeRequestUUID uuid.UUID                   `json:"change_request_uuid"`
	Payload           json.RawMessage             `json:"payload,omitempty"`
	Status            enums.AutomationEventStatus `json:"status"`
	Attempts          int64                       `json:"attempts"`
	NextAttemptAt     null.Time                   `json:"next_attempt_at"`
	DeliveredAt       null.Time                   `json:"delivered_at"`
	LastError         null.String                 `json:"last_error"`
	CreatedAt         time.Time                   `json:"created_at"`
	UpdatedAt         time.Time                   `json:"updated_at"`
	CreatedByUUID     uuid.UUID                   `json:"created_by_uuid"`
	UpdatedByUUID     uuid.UUID                   `json:"updated_by_uuid"`
}

func (e AutomationEvent) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e AutomationEvent) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func AutomationEventFromJSON(data json.RawMessage) AutomationEvent {
	entity := AutomationEvent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error AutomationEventFromJSON: %v\n", err2)
		}
	}
	return entity
}

func AutomationEventSliceFromJSON(data json.RawMessage) []AutomationEvent {
	entity := []AutomationEvent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []AutomationEvent{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := AutomationEvent{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error AutomationEventSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e AutomationEvent) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AutomationEventToJSON: %v\n", err)
	}
	return res
}

func AutomationEventToJSON(e AutomationEvent) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AutomationEventToJSON: %v\n", err)
	}
	return res
}

func AutomationEventSliceToJSON(e []AutomationEvent) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error AutomationEventSliceToJSON: %v\n", err)
	}
	return res
}
