// Code generated by nuzur go-code-gen. DO NOT EDIT.

package automation_event

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this AutomationEvent against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e AutomationEvent) Validate() error {
	c := validation.NewCollector()
	if e.UUID.IsNil() {
		c.Require("automation_event.uuid")
	}
	if e.AutomationUUID.IsNil() {
		c.Require("automation_event.automation_uuid")
	}
	if e.ProjectUUID.IsNil() {
		c.Require("automation_event.project_uuid")
	}
	if e.ChangeRequestUUID.IsNil() {
		c.Require("automation_event.change_request_uuid")
	}
	c.Field("automation_event.payload", validation.JSONBytes(e.Payload))
	if e.Status.ToInt64() == 0 {
		c.Require("automation_event.status")
	} else {
		c.Field("automation_event.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3, 4, 5}, "automation_event_status"))

	}
	c.Field("automation_event.attempts", validation.Integer(e.Attempts, false, 0, 0, false, false, false, false, 0, 0))
	if e.CreatedByUUID.IsNil() {
		c.Require("automation_event.created_by_uuid")
	}
	if e.UpdatedByUUID.IsNil() {
		c.Require("automation_event.updated_by_uuid")
	}

	return c.Result()
}
