// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_project

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type UserProject struct {
	UUID                    uuid.UUID               `json:"uuid"`
	UserUUID                *uuid.UUID              `json:"user_uuid"`
	UserEmail               null.String             `json:"user_email"`
	ProjectUUID             uuid.UUID               `json:"project_uuid"`
	Role                    enums.UserProjectRole   `json:"role"`
	ReviewRequiredStructure bool                    `json:"review_required_structure"`
	ReviewRequiredData      bool                    `json:"review_required_data"`
	Status                  enums.UserProjectStatus `json:"status"`
	CreatedAt               time.Time               `json:"created_at"`
	UpdatedAt               time.Time               `json:"updated_at"`
	CreatedByUUID           uuid.UUID               `json:"created_by_uuid"`
	UpdatedByUUID           uuid.UUID               `json:"updated_by_uuid"`
}

func (e UserProject) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e UserProject) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func UserProjectFromJSON(data json.RawMessage) UserProject {
	entity := UserProject{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error UserProjectFromJSON: %v\n", err2)
		}
	}
	return entity
}

func UserProjectSliceFromJSON(data json.RawMessage) []UserProject {
	entity := []UserProject{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []UserProject{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := UserProject{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error UserProjectSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e UserProject) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserProjectToJSON: %v\n", err)
	}
	return res
}

func UserProjectToJSON(e UserProject) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserProjectToJSON: %v\n", err)
	}
	return res
}

func UserProjectSliceToJSON(e []UserProject) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error UserProjectSliceToJSON: %v\n", err)
	}
	return res
}
