// Code generated by nuzur go-code-gen. DO NOT EDIT.

package membership

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/membership/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchMembershipByType(
	ctx context.Context,
	req types.FetchMembershipByTypeRequest,
	opts ...Option,
) (types.FetchMembershipByTypeResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchMembershipByType:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchMembershipByTypeResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchMembershipByType(
				ctx,
				nemdb.FetchMembershipByTypeParams{
					Type: req.Type.ToInt64(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchMembershipByTypeResponse{}, err
			}
			return types.FetchMembershipByTypeResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchMembershipByTypeResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchMembershipByTypeResponse{}, fetchErr
	}
	result := v.(types.FetchMembershipByTypeResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
