// Code generated by nuzur go-code-gen. DO NOT EDIT.

package deployment_server

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e DeploymentServer) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"ssh_user":         entitytypes.StringFieldType,
		"ssh_port":         entitytypes.IntFieldType,
		"public_port":      entitytypes.IntFieldType,
		"http_port":        entitytypes.IntFieldType,
		"grpc_port":        entitytypes.IntFieldType,
		"container_name":   entitytypes.StringFieldType,
		"image_name":       entitytypes.StringFieldType,
		"domain":           entitytypes.StringFieldType,
		"public_url":       entitytypes.StringFieldType,
		"data_manager_url": entitytypes.StringFieldType,
		"local_agent_uuid": entitytypes.StringFieldType,
	}
}

func (e DeploymentServer) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "ssh_user")
	res = append(res, "ssh_port")
	res = append(res, "public_port")
	res = append(res, "http_port")
	res = append(res, "grpc_port")
	res = append(res, "container_name")
	res = append(res, "image_name")
	res = append(res, "domain")
	res = append(res, "public_url")
	res = append(res, "data_manager_url")
	res = append(res, "local_agent_uuid")

	return res
}

func (e DeploymentServer) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e DeploymentServer) EntityIdentifier() string {
	return "deployment_server"
}

func (e DeploymentServer) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e DeploymentServer) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
