// Code generated by nuzur go-code-gen. DO NOT EDIT.

package deployment_server

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"

	"github.com/nuzur/nem/core/entity/mapper"
)

type DeploymentServer struct {
	SshUser        null.String `json:"ssh_user"`
	SshPort        null.Int64  `json:"ssh_port"`
	PublicPort     null.Int64  `json:"public_port"`
	HTTPPort       null.Int64  `json:"http_port"`
	GrpcPort       null.Int64  `json:"grpc_port"`
	ContainerName  null.String `json:"container_name"`
	ImageName      null.String `json:"image_name"`
	Domain         null.String `json:"domain"`
	PublicURL      null.String `json:"public_url"`
	DataManagerURL null.String `json:"data_manager_url"`
	LocalAgentUUID *uuid.UUID  `json:"local_agent_uuid"`
}

func (e DeploymentServer) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e DeploymentServer) PrimaryKeyValues() []string {
	return []string{}
}

func DeploymentServerFromJSON(data json.RawMessage) DeploymentServer {
	entity := DeploymentServer{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error DeploymentServerFromJSON: %v\n", err2)
		}
	}
	return entity
}

func DeploymentServerSliceFromJSON(data json.RawMessage) []DeploymentServer {
	entity := []DeploymentServer{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []DeploymentServer{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := DeploymentServer{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error DeploymentServerSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e DeploymentServer) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DeploymentServerToJSON: %v\n", err)
	}
	return res
}

func DeploymentServerToJSON(e DeploymentServer) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DeploymentServerToJSON: %v\n", err)
	}
	return res
}

func DeploymentServerSliceToJSON(e []DeploymentServer) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error DeploymentServerSliceToJSON: %v\n", err)
	}
	return res
}
