// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/core/entity/project_extension"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type Project struct {
	UUID              uuid.UUID                            `json:"uuid"`
	Version           int64                                `json:"version"`
	Name              string                               `json:"name"`
	Description       null.String                          `json:"description"`
	Tags              json.RawMessage                      `json:"tags"`
	URL               null.String                          `json:"url"`
	OwnerUUID         uuid.UUID                            `json:"owner_uuid"`
	TeamUUID          uuid.UUID                            `json:"team_uuid"`
	AccessType        enums.ProjectAccessType              `json:"access_type"`
	ProjectExtensions []project_extension.ProjectExtension `json:"project_extensions"`
	Status            enums.ProjectStatus                  `json:"status"`
	CreatedAt         time.Time                            `json:"created_at"`
	UpdatedAt         time.Time                            `json:"updated_at"`
	CreatedByUUID     uuid.UUID                            `json:"created_by_uuid"`
	UpdatedByUUID     uuid.UUID                            `json:"updated_by_uuid"`
}

func (e Project) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Project) PrimaryKeyValues() []string {
	return []string{
		e.UUID.String(),
	}
}

func ProjectFromJSON(data json.RawMessage) Project {
	entity := Project{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ProjectFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ProjectSliceFromJSON(data json.RawMessage) []Project {
	entity := []Project{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Project{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Project{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ProjectSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Project) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ProjectToJSON: %v\n", err)
	}
	return res
}

func ProjectToJSON(e Project) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ProjectToJSON: %v\n", err)
	}
	return res
}

func ProjectSliceToJSON(e []Project) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ProjectSliceToJSON: %v\n", err)
	}
	return res
}
