// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project_version

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/project_version/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchProjectVersionByStatus(
	ctx context.Context,
	req types.FetchProjectVersionByStatusRequest,
	opts ...Option,
) (types.FetchProjectVersionByStatusResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchProjectVersionByStatus:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchProjectVersionByStatusResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchProjectVersionByStatus(
				ctx,
				nemdb.FetchProjectVersionByStatusParams{
					Status: req.Status.ToInt64(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchProjectVersionByStatusResponse{}, err
			}
			return types.FetchProjectVersionByStatusResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchProjectVersionByStatusResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchProjectVersionByStatusResponse{}, fetchErr
	}
	result := v.(types.FetchProjectVersionByStatusResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
