// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project_version

import (
	"context"
	"database/sql"
	"fmt"
	main_entity "github.com/nuzur/nem/core/entity/project_version"
	"github.com/nuzur/nem/core/module/project_version/types"
	repogen "github.com/nuzur/nem/core/repository/gen"

	"go.uber.org/zap"
	"slices"
)

func (m *module) List(ctx context.Context,
	request types.ListRequest,
	opts ...Option) (types.ListResponse, error) {

	reqPlusOne := request
	reqPlusOne.PageSize = request.PageSize + 1

	query, err := m.repository.BuildListEntityQuery(
		ctx,
		reqPlusOne,
		main_entity.ProjectVersion{},
		false)
	if err != nil {

		return types.ListResponse{}, err
	}

	resolvedOpts := applyAllOptions(opts)
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it runs on the transaction and can neither be
	// served from the shared cache nor be collapsed into another caller's
	// in-flight query.
	var querier interface {
		QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	} = m.repository.DB
	if resolvedOpts.SQLTx != nil {
		querier = resolvedOpts.SQLTx
	}
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("ListProjectVersion:%v", request)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.ListResponse), nil
		}
	}

	list := func() (any, error) {
		var rows *sql.Rows
		rows, err = querier.QueryContext(ctx, query)
		if err != nil {

			m.logger.Error("error in executing query for ListProjectVersion", zap.String("query", query), zap.Error(err))
			return types.ListResponse{}, err
		}
		defer rows.Close()
		var scanGetters []func(*repogen.ProjectVersion) any
		if len(request.GetIncludeFields()) > 0 {
			for _, f := range listFields {
				if slices.Contains(request.GetIncludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else if len(request.GetExcludeFields()) > 0 {
			for _, f := range listFields {
				if !slices.Contains(request.GetExcludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else {
			for _, f := range listFields {
				scanGetters = append(scanGetters, listFieldRegistry[f])
			}
		}

		var items []repogen.ProjectVersion
		for rows.Next() {
			var i repogen.ProjectVersion
			fields := make([]any, 0, len(scanGetters))
			for _, getter := range scanGetters {
				fields = append(fields, getter(&i))
			}
			if err := rows.Scan(fields...); err != nil {

				return types.ListResponse{}, err
			}
			items = append(items, i)
		}
		if err := rows.Close(); err != nil {

			return types.ListResponse{}, err
		}
		if err := rows.Err(); err != nil {

			return types.ListResponse{}, err
		}

		hasNextPage := false
		if len(items) > int(request.PageSize) {
			hasNextPage = true
			items = items[:request.PageSize]
		}

		return types.ListResponse{
			ProjectVersion: mapModelsToEntities(items),
			HasNextPage:    hasNextPage,
		}, nil
	}
	var v any
	var listErr error
	if skipShared {
		v, listErr = list()
	} else {
		v, listErr, _ = m.sg.Do(cacheKey, list)
	}
	if listErr != nil {
		return types.ListResponse{}, listErr
	}
	listResponse := v.(types.ListResponse)
	if !skipShared {
		m.cache.Set(cacheKey, listResponse, 0)
	}
	return listResponse, nil
}

var listFields = []string{

	"uuid",

	"version",

	"identifier",

	"description",

	"project_uuid",

	"entities",

	"relationships",

	"enums",

	"services",

	"base_version_uuid",

	"review_status",

	"deployments",

	"status",

	"created_at",

	"updated_at",

	"created_by_uuid",

	"updated_by_uuid",
}

var listFieldRegistry = map[string]func(*repogen.ProjectVersion) any{

	"uuid": func(i *repogen.ProjectVersion) any { return &i.UUID },

	"version": func(i *repogen.ProjectVersion) any { return &i.Version },

	"identifier": func(i *repogen.ProjectVersion) any { return &i.Identifier },

	"description": func(i *repogen.ProjectVersion) any { return &i.Description },

	"project_uuid": func(i *repogen.ProjectVersion) any { return &i.ProjectUUID },

	"entities": func(i *repogen.ProjectVersion) any { return &i.Entities },

	"relationships": func(i *repogen.ProjectVersion) any { return &i.Relationships },

	"enums": func(i *repogen.ProjectVersion) any { return &i.Enums },

	"services": func(i *repogen.ProjectVersion) any { return &i.Services },

	"base_version_uuid": func(i *repogen.ProjectVersion) any { return &i.BaseVersionUUID },

	"review_status": func(i *repogen.ProjectVersion) any { return &i.ReviewStatus },

	"deployments": func(i *repogen.ProjectVersion) any { return &i.Deployments },

	"status": func(i *repogen.ProjectVersion) any { return &i.Status },

	"created_at": func(i *repogen.ProjectVersion) any { return &i.CreatedAt },

	"updated_at": func(i *repogen.ProjectVersion) any { return &i.UpdatedAt },

	"created_by_uuid": func(i *repogen.ProjectVersion) any { return &i.CreatedByUUID },

	"updated_by_uuid": func(i *repogen.ProjectVersion) any { return &i.UpdatedByUUID },
}
