// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_varchar_config

import (
	"encoding/json"
	"log"

	"github.com/guregu/null/v6"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FieldTypeVarcharConfig struct {
	MinSize         int64       `json:"min_size"`
	MaxSize         int64       `json:"max_size"`
	RegexValidation null.String `json:"regex_validation"`
}

func (e FieldTypeVarcharConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FieldTypeVarcharConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FieldTypeVarcharConfigFromJSON(data json.RawMessage) FieldTypeVarcharConfig {
	entity := FieldTypeVarcharConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FieldTypeVarcharConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FieldTypeVarcharConfigSliceFromJSON(data json.RawMessage) []FieldTypeVarcharConfig {
	entity := []FieldTypeVarcharConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FieldTypeVarcharConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FieldTypeVarcharConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FieldTypeVarcharConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FieldTypeVarcharConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeVarcharConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeVarcharConfigToJSON(e FieldTypeVarcharConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeVarcharConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeVarcharConfigSliceToJSON(e []FieldTypeVarcharConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeVarcharConfigSliceToJSON: %v\n", err)
	}
	return res
}
