// Code generated by nuzur go-code-gen. DO NOT EDIT.

package project_version_deployment

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this ProjectVersionDeployment against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e ProjectVersionDeployment) Validate() error {
	c := validation.NewCollector()
	if e.EnviromentUUID.IsNil() {
		c.Require("project_version_deployment.enviroment_uuid")
	}
	if e.Status.ToInt64() == 0 {
		c.Require("project_version_deployment.status")
	} else {
		c.Field("project_version_deployment.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2, 3, 4, 5}, "project_version_deployment_status"))

	}

	return c.Result()
}
