// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/nuzur/nem/core/entity/user_project_version"

	"github.com/nuzur/nem/enums"
	"go.uber.org/zap/zapcore"
)

type FetchUserProjectVersionByStatusRequest struct {
	Status enums.UserProjectVersionStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchUserProjectVersionByStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchUserProjectVersionByStatusResponse struct {
	Results []main_entity.UserProjectVersion
}
