// Code generated by nuzur go-code-gen. DO NOT EDIT.

package deployment

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/deployment/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchDeploymentByUserUUIDAndHostAndIdentifier(
	ctx context.Context,
	req types.FetchDeploymentByUserUUIDAndHostAndIdentifierRequest,
	opts ...Option,
) (types.FetchDeploymentByUserUUIDAndHostAndIdentifierResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchDeploymentByUserUUIDAndHostAndIdentifier:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchDeploymentByUserUUIDAndHostAndIdentifierResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchDeploymentByUserUUIDAndHostAndIdentifier(
				ctx,
				nemdb.FetchDeploymentByUserUUIDAndHostAndIdentifierParams{
					UserUUID: req.UserUUID.String(),

					Host: req.Host,

					Identifier: req.Identifier,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchDeploymentByUserUUIDAndHostAndIdentifierResponse{}, err
			}
			return types.FetchDeploymentByUserUUIDAndHostAndIdentifierResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchDeploymentByUserUUIDAndHostAndIdentifierResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchDeploymentByUserUUIDAndHostAndIdentifierResponse{}, fetchErr
	}
	result := v.(types.FetchDeploymentByUserUUIDAndHostAndIdentifierResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
