// Code generated by nuzur go-code-gen. DO NOT EDIT.

package change_request_metadata

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"

	"github.com/nuzur/nem/core/entity/change_request_metadata_data"
)

func (e ChangeRequestMetadata) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"data": entitytypes.MultiDependantEntityFieldType,
	}
}

func (e ChangeRequestMetadata) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "data")

	return res
}

func (e ChangeRequestMetadata) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	res["data"] = change_request_metadata_data.ChangeRequestMetadataData{}.FieldIdentifierToTypeMap()
	return res
}

func (e ChangeRequestMetadata) EntityIdentifier() string {
	return "change_request_metadata"
}

func (e ChangeRequestMetadata) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e ChangeRequestMetadata) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
