// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enviorment

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/nuzur/nem/enums"
	"time"

	"github.com/nuzur/nem/core/entity/mapper"
)

type Enviorment struct {
	UUID          uuid.UUID              `json:"uuid"`
	Identifier    string                 `json:"identifier"`
	Critical      bool                   `json:"critical"`
	Status        enums.EnviormentStatus `json:"status"`
	CreatedAt     time.Time              `json:"created_at"`
	UpdatedAt     time.Time              `json:"updated_at"`
	CreatedByUUID uuid.UUID              `json:"created_by_uuid"`
	UpdatedByUUID uuid.UUID              `json:"updated_by_uuid"`
}

func (e Enviorment) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Enviorment) PrimaryKeyValues() []string {
	return []string{}
}

func EnviormentFromJSON(data json.RawMessage) Enviorment {
	entity := Enviorment{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error EnviormentFromJSON: %v\n", err2)
		}
	}
	return entity
}

func EnviormentSliceFromJSON(data json.RawMessage) []Enviorment {
	entity := []Enviorment{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Enviorment{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Enviorment{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error EnviormentSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Enviorment) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnviormentToJSON: %v\n", err)
	}
	return res
}

func EnviormentToJSON(e Enviorment) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnviormentToJSON: %v\n", err)
	}
	return res
}

func EnviormentSliceToJSON(e []Enviorment) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EnviormentSliceToJSON: %v\n", err)
	}
	return res
}
