// Code generated by nuzur go-code-gen. DO NOT EDIT.

package field_type_slug_config

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"

	"github.com/nuzur/nem/core/entity/mapper"
)

type FieldTypeSlugConfig struct {
	MinSize           int64       `json:"min_size"`
	MaxSize           int64       `json:"max_size"`
	RegexValidation   null.String `json:"regex_validation"`
	BasedOnFieldUUIDs []uuid.UUID `json:"based_on_field_uuids"`
}

func (e FieldTypeSlugConfig) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e FieldTypeSlugConfig) PrimaryKeyValues() []string {
	return []string{}
}

func FieldTypeSlugConfigFromJSON(data json.RawMessage) FieldTypeSlugConfig {
	entity := FieldTypeSlugConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error FieldTypeSlugConfigFromJSON: %v\n", err2)
		}
	}
	return entity
}

func FieldTypeSlugConfigSliceFromJSON(data json.RawMessage) []FieldTypeSlugConfig {
	entity := []FieldTypeSlugConfig{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []FieldTypeSlugConfig{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := FieldTypeSlugConfig{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error FieldTypeSlugConfigSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e FieldTypeSlugConfig) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeSlugConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeSlugConfigToJSON(e FieldTypeSlugConfig) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeSlugConfigToJSON: %v\n", err)
	}
	return res
}

func FieldTypeSlugConfigSliceToJSON(e []FieldTypeSlugConfig) json.RawMessage {
	if e == nil {
		return json.RawMessage{}
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error FieldTypeSlugConfigSliceToJSON: %v\n", err)
	}
	return res
}
