// Code generated by nuzur go-code-gen. DO NOT EDIT.

package automation

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/automation/types"
)

func (m *module) FetchAutomationByUUID(
	ctx context.Context,
	req types.FetchAutomationByUUIDRequest,
	opts ...Option,
) (types.FetchAutomationByUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchAutomationByUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAutomationByUUIDResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchAutomationByUUID(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchAutomationByUUIDResponse{}, err
		}
		return types.FetchAutomationByUUIDResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchAutomationByUUIDResponse{}, err
	}
	result := v.(types.FetchAutomationByUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
