// Code generated by nuzur go-code-gen. DO NOT EDIT.

package automation

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/automation/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchAutomationByProjectUUIDAndEntityUUIDAndEnabled(
	ctx context.Context,
	req types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledRequest,
	opts ...Option,
) (types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchAutomationByProjectUUIDAndEntityUUIDAndEnabled:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabled(
				ctx,
				nemdb.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledParams{
					ProjectUUID: req.ProjectUUID.String(),

					EntityUUID: req.EntityUUID.String(),

					Enabled: req.Enabled,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledResponse{}, err
			}
			return types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledResponse{}, fetchErr
	}
	result := v.(types.FetchAutomationByProjectUUIDAndEntityUUIDAndEnabledResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
