// Code generated by nuzur go-code-gen. DO NOT EDIT.

package automation

import (
	main_entity "github.com/nuzur/nem/core/entity/automation"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/mapper"

	"github.com/nuzur/nem/enums"
)

func mapModelsToEntities(models []nemdb.Automation) []main_entity.Automation {
	result := []main_entity.Automation{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m nemdb.Automation) main_entity.Automation {
	return main_entity.Automation{
		UUID:          mapper.StringToUUID(m.UUID),
		ProjectUUID:   mapper.StringToUUID(m.ProjectUUID),
		EntityUUID:    mapper.StringToUUID(m.EntityUUID),
		Name:          m.Name,
		Operation:     enums.AutomationOperation(m.Operation),
		Condition:     m.Condition,
		ActionType:    enums.AutomationActionType(m.ActionType),
		ActionConfig:  m.ActionConfig,
		Enabled:       m.Enabled,
		Status:        enums.AutomationStatus(m.Status),
		CreatedAt:     m.CreatedAt,
		UpdatedAt:     m.UpdatedAt,
		CreatedByUUID: mapper.StringToUUID(m.CreatedByUUID),
		UpdatedByUUID: mapper.StringToUUID(m.UpdatedByUUID),
	}
}
