// Code generated by nuzur go-code-gen. DO NOT EDIT.

package relationship_node_type_service_config

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e RelationshipNodeTypeServiceConfig) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"service_uuid": entitytypes.StringFieldType,
	}
}

func (e RelationshipNodeTypeServiceConfig) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "service_uuid")

	return res
}

func (e RelationshipNodeTypeServiceConfig) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e RelationshipNodeTypeServiceConfig) EntityIdentifier() string {
	return "relationship_node_type_service_config"
}

func (e RelationshipNodeTypeServiceConfig) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e RelationshipNodeTypeServiceConfig) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
