// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_project_version

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e UserProjectVersion) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":                 entitytypes.StringFieldType,
		"version":              entitytypes.IntFieldType,
		"project_version_uuid": entitytypes.StringFieldType,
		"user_uuid":            entitytypes.StringFieldType,
		"data":                 entitytypes.RawJSONFieldType,
		"status":               entitytypes.SingleEnumFieldType,
		"created_at":           entitytypes.TimestampFieldType,
		"updated_at":           entitytypes.TimestampFieldType,
		"created_by_uuid":      entitytypes.StringFieldType,
		"updated_by_uuid":      entitytypes.StringFieldType,
	}
}

func (e UserProjectVersion) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "version")
	res = append(res, "project_version_uuid")
	res = append(res, "user_uuid")
	res = append(res, "data")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "created_by_uuid")
	res = append(res, "updated_by_uuid")

	return res
}

func (e UserProjectVersion) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e UserProjectVersion) EntityIdentifier() string {
	return "user_project_version"
}

func (e UserProjectVersion) PrimaryKeyIdentifiers() []string {
	return []string{
		"uuid",
	}
}

func (e UserProjectVersion) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
