// Code generated by nuzur go-code-gen. DO NOT EDIT.

package store

import (
	entitytypes "github.com/nuzur/nem/core/entity/types"
)

func (e Store) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"uuid":            entitytypes.StringFieldType,
		"identifier":      entitytypes.StringFieldType,
		"description":     entitytypes.StringFieldType,
		"status":          entitytypes.SingleEnumFieldType,
		"created_at":      entitytypes.TimestampFieldType,
		"updated_at":      entitytypes.TimestampFieldType,
		"created_by_uuid": entitytypes.StringFieldType,
		"updated_by_uuid": entitytypes.StringFieldType,
	}
}

func (e Store) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "uuid")
	res = append(res, "identifier")
	res = append(res, "description")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "created_by_uuid")
	res = append(res, "updated_by_uuid")

	return res
}

func (e Store) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Store) EntityIdentifier() string {
	return "store"
}

func (e Store) PrimaryKeyIdentifiers() []string {
	return []string{}
}

func (e Store) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
