// Code generated by nuzur go-code-gen. DO NOT EDIT.

package connection_type_config

import (
	"github.com/nuzur/nem/core/entity/validation"
)

// Validate checks this ConnectionTypeConfig against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e ConnectionTypeConfig) Validate() error {
	c := validation.NewCollector()
	if validation.IsZeroEntity(e.TcpIp) {
		c.Require("connection_type_config.tcp_ip")
	} else {
		c.Merge("connection_type_config.tcp_ip", e.TcpIp.Validate())
	}
	if validation.IsZeroEntity(e.TcpIpSsh) {
		c.Require("connection_type_config.tcp_ip_ssh")
	} else {
		c.Merge("connection_type_config.tcp_ip_ssh", e.TcpIpSsh.Validate())
	}

	return c.Result()
}
