// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_team

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/user_team/types"
)

func (m *module) FetchUserTeamByUUID(
	ctx context.Context,
	req types.FetchUserTeamByUUIDRequest,
	opts ...Option,
) (types.FetchUserTeamByUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchUserTeamByUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchUserTeamByUUIDResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchUserTeamByUUID(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchUserTeamByUUIDResponse{}, err
		}
		return types.FetchUserTeamByUUIDResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchUserTeamByUUIDResponse{}, err
	}
	result := v.(types.FetchUserTeamByUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
