// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_team

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/user_team/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/mapper"
)

func (m *module) FetchUserTeamByUserUUID(
	ctx context.Context,
	req types.FetchUserTeamByUserUUIDRequest,
	opts ...Option,
) (types.FetchUserTeamByUserUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchUserTeamByUserUUID:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchUserTeamByUserUUIDResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchUserTeamByUserUUID(
				ctx,
				nemdb.FetchUserTeamByUserUUIDParams{
					UserUUID: mapper.UUIDPtrToNullString(req.UserUUID),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchUserTeamByUserUUIDResponse{}, err
			}
			return types.FetchUserTeamByUserUUIDResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchUserTeamByUserUUIDResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchUserTeamByUserUUIDResponse{}, fetchErr
	}
	result := v.(types.FetchUserTeamByUserUUIDResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
