// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_team

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/user_team/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchUserTeamByRole(
	ctx context.Context,
	req types.FetchUserTeamByRoleRequest,
	opts ...Option,
) (types.FetchUserTeamByRoleResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchUserTeamByRole:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchUserTeamByRoleResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchUserTeamByRole(
				ctx,
				nemdb.FetchUserTeamByRoleParams{
					Role: req.Role.ToInt64(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchUserTeamByRoleResponse{}, err
			}
			return types.FetchUserTeamByRoleResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchUserTeamByRoleResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchUserTeamByRoleResponse{}, fetchErr
	}
	result := v.(types.FetchUserTeamByRoleResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
