// Code generated by nuzur go-code-gen. DO NOT EDIT.

package user_team

import (
	main_entity "github.com/nuzur/nem/core/entity/user_team"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/nuzur/nem/core/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/nuzur/nem/enums"
)

func mapModelsToEntities(models []nemdb.UserTeam) []main_entity.UserTeam {
	result := []main_entity.UserTeam{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m nemdb.UserTeam) main_entity.UserTeam {
	return main_entity.UserTeam{
		UUID:                    mapper.StringToUUID(m.UUID),
		UserUUID:                mapper.StringToUUIDPtr(m.UserUUID),
		UserEmail:               null.NewString(m.UserEmail.String, m.UserEmail.Valid),
		TeamUUID:                mapper.StringToUUID(m.TeamUUID),
		Role:                    enums.UserTeamRole(m.Role),
		ReviewRequiredStructure: m.ReviewRequiredStructure,
		ReviewRequiredData:      m.ReviewRequiredData,
		Status:                  enums.UserTeamStatus(m.Status),
		CreatedAt:               m.CreatedAt,
		UpdatedAt:               m.UpdatedAt,
		CreatedByUUID:           mapper.StringToUUID(m.CreatedByUUID),
		UpdatedByUUID:           mapper.StringToUUID(m.UpdatedByUUID),
	}
}
