// Code generated by nuzur go-code-gen. DO NOT EDIT.

package ai_usage

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/ai_usage/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchAiUsageByProjectVersionUUID(
	ctx context.Context,
	req types.FetchAiUsageByProjectVersionUUIDRequest,
	opts ...Option,
) (types.FetchAiUsageByProjectVersionUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchAiUsageByProjectVersionUUID:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAiUsageByProjectVersionUUIDResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchAiUsageByProjectVersionUUID(
				ctx,
				nemdb.FetchAiUsageByProjectVersionUUIDParams{
					ProjectVersionUUID: req.ProjectVersionUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchAiUsageByProjectVersionUUIDResponse{}, err
			}
			return types.FetchAiUsageByProjectVersionUUIDResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchAiUsageByProjectVersionUUIDResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchAiUsageByProjectVersionUUIDResponse{}, fetchErr
	}
	result := v.(types.FetchAiUsageByProjectVersionUUIDResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
