// Code generated by nuzur go-code-gen. DO NOT EDIT.

package ai_usage

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/ai_usage/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchAiUsageByProvider(
	ctx context.Context,
	req types.FetchAiUsageByProviderRequest,
	opts ...Option,
) (types.FetchAiUsageByProviderResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchAiUsageByProvider:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAiUsageByProviderResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchAiUsageByProvider(
				ctx,
				nemdb.FetchAiUsageByProviderParams{
					Provider: req.Provider.ToInt64(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchAiUsageByProviderResponse{}, err
			}
			return types.FetchAiUsageByProviderResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchAiUsageByProviderResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchAiUsageByProviderResponse{}, fetchErr
	}
	result := v.(types.FetchAiUsageByProviderResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
