// Code generated by nuzur go-code-gen. DO NOT EDIT.

package ai_usage

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/ai_usage/types"

	"errors"
	nemdb "github.com/nuzur/nem/core/repository/gen"
)

func (m *module) FetchAiUsageByProjectUuid(
	ctx context.Context,
	req types.FetchAiUsageByProjectUuidRequest,
	opts ...Option,
) (types.FetchAiUsageByProjectUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchAiUsageByProjectUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAiUsageByProjectUuidResponse), nil
		}
	}
	v, fetchErr, _ := m.sg.Do(cacheKey, func() (any, error) {
		if req.OrderBy == "" {
			models, err := m.repository.Queries.FetchAiUsageByProjectUuid(
				ctx,
				nemdb.FetchAiUsageByProjectUuidParams{
					ProjectUUID: req.ProjectUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchAiUsageByProjectUuidResponse{}, err
			}
			return types.FetchAiUsageByProjectUuidResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchAiUsageByProjectUuidResponse{}, err
	}) // end sg.Do
	if fetchErr != nil {
		return types.FetchAiUsageByProjectUuidResponse{}, fetchErr
	}
	result := v.(types.FetchAiUsageByProjectUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
