// Code generated by nuzur go-code-gen. DO NOT EDIT.

package ai_usage

import (
	"context"
	"fmt"

	"github.com/nuzur/nem/core/module/ai_usage/types"
)

func (m *module) FetchAiUsageByUuid(
	ctx context.Context,
	req types.FetchAiUsageByUuidRequest,
	opts ...Option,
) (types.FetchAiUsageByUuidResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	cacheKey := fmt.Sprintf("FetchAiUsageByUuid:%v", req)
	if !resolvedOpts.SkipCache {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchAiUsageByUuidResponse), nil
		}
	}
	v, err, _ := m.sg.Do(cacheKey, func() (any, error) {
		models, err := m.repository.Queries.FetchAiUsageByUuid(
			ctx,
			req.UUID.String(),
		)
		if err != nil {

			return types.FetchAiUsageByUuidResponse{}, err
		}
		return types.FetchAiUsageByUuidResponse{
			Results: mapModelsToEntities(models),
		}, nil
	})
	if err != nil {
		return types.FetchAiUsageByUuidResponse{}, err
	}
	result := v.(types.FetchAiUsageByUuidResponse)
	if !resolvedOpts.SkipCache {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
