// Code generated by nuzur go-code-gen. DO NOT EDIT.

package ai_usage

import (
	"context"

	"github.com/gofrs/uuid"

	"github.com/nuzur/nem/core/module/ai_usage/types"
)

func (m *module) Upsert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	// check if primary keys are set to determine if this is an insert or update
	isInsert := true

	if req.AiUsage.UUID != uuid.Nil {
		isInsert = false
	}

	if isInsert {
		// auto-generate primary-key UUIDs for new records
		req.AiUsage.UUID = uuid.Must(uuid.NewV4())
		return m.Insert(ctx, req, opts...)
	}

	return m.Update(ctx, req, opts...)
}
