// Code generated by nuzur go-code-gen. DO NOT EDIT.

package ai_usage

import (
	"context"

	"github.com/nuzur/nem/core/module/ai_usage/types"
	nemdb "github.com/nuzur/nem/core/repository/gen"

	"github.com/gofrs/uuid"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.AiUsage.UUID == uuid.Nil {
		req.AiUsage.UUID = uuid.Must(uuid.NewV4())
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertAiUsage(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		UUID: req.AiUsage.UUID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) nemdb.InsertAiUsageParams {
	return nemdb.InsertAiUsageParams{
		UUID: req.AiUsage.UUID.String(),

		UserUUID: req.AiUsage.UserUUID.String(),

		ProjectUUID: req.AiUsage.ProjectUUID.String(),

		ProjectVersionUUID: req.AiUsage.ProjectVersionUUID.String(),

		UserPrompt: req.AiUsage.UserPrompt,

		Step: req.AiUsage.Step,

		Context: req.AiUsage.Context.ToInt64(),

		Provider: req.AiUsage.Provider.ToInt64(),

		InputTokens: req.AiUsage.InputTokens,

		OutputTokens: req.AiUsage.OutputTokens,

		Status: req.AiUsage.Status.ToInt64(),

		CreatedAt: req.AiUsage.CreatedAt,

		UpdatedAt: req.AiUsage.UpdatedAt,

		CreatedByUUID: req.AiUsage.CreatedByUUID.String(),

		UpdatedByUUID: req.AiUsage.UpdatedByUUID.String(),
	}
}
