// Code generated by nuzur go-code-gen. DO NOT EDIT.

package mapper

import (
	main_entity "github.com/nuzur/nem/core/entity/automation_event"
	pb "github.com/nuzur/nem/idl/gen"

	"encoding/json"

	"github.com/nuzur/nem/enums"

	"google.golang.org/protobuf/types/known/timestamppb"

	"github.com/guregu/null/v6"
)

func AutomationEventToProto(e main_entity.AutomationEvent) *pb.AutomationEvent {
	return &pb.AutomationEvent{
		Uuid:              e.UUID.String(),
		AutomationUuid:    e.AutomationUUID.String(),
		ProjectUuid:       e.ProjectUUID.String(),
		ChangeRequestUuid: e.ChangeRequestUUID.String(),
		Payload:           string(e.Payload),
		Status:            pb.AutomationEventStatus(e.Status),
		Attempts:          int64(e.Attempts),
		NextAttemptAt:     timestamppb.New(e.NextAttemptAt.ValueOrZero()),
		DeliveredAt:       timestamppb.New(e.DeliveredAt.ValueOrZero()),
		LastError:         e.LastError.ValueOrZero(),
		CreatedAt:         timestamppb.New(e.CreatedAt),
		UpdatedAt:         timestamppb.New(e.UpdatedAt),
		CreatedByUuid:     e.CreatedByUUID.String(),
		UpdatedByUuid:     e.UpdatedByUUID.String(),
	}
}

func AutomationEventSliceToProto(es []main_entity.AutomationEvent) []*pb.AutomationEvent {
	res := []*pb.AutomationEvent{}
	for _, e := range es {
		res = append(res, AutomationEventToProto(e))
	}
	return res
}

func AutomationEventFromProto(m *pb.AutomationEvent) main_entity.AutomationEvent {
	if m == nil {
		return main_entity.AutomationEvent{}
	}
	return main_entity.AutomationEvent{
		UUID:              StringToUUID(m.GetUuid()),
		AutomationUUID:    StringToUUID(m.GetAutomationUuid()),
		ProjectUUID:       StringToUUID(m.GetProjectUuid()),
		ChangeRequestUUID: StringToUUID(m.GetChangeRequestUuid()),
		Payload:           json.RawMessage([]byte(m.GetPayload())),
		Status:            enums.AutomationEventStatus(m.GetStatus()),
		Attempts:          int64(m.GetAttempts()),
		NextAttemptAt:     null.TimeFrom(m.GetNextAttemptAt().AsTime()),
		DeliveredAt:       null.TimeFrom(m.GetDeliveredAt().AsTime()),
		LastError:         null.StringFrom(m.LastError),
		CreatedAt:         m.GetCreatedAt().AsTime(),
		UpdatedAt:         m.GetUpdatedAt().AsTime(),
		CreatedByUUID:     StringToUUID(m.GetCreatedByUuid()),
		UpdatedByUUID:     StringToUUID(m.GetUpdatedByUuid()),
	}
}

func AutomationEventSliceFromProto(es []*pb.AutomationEvent) []main_entity.AutomationEvent {
	if es == nil {
		return []main_entity.AutomationEvent{}
	}
	res := []main_entity.AutomationEvent{}
	for _, e := range es {
		res = append(res, AutomationEventFromProto(e))
	}
	return res
}
