// Code generated by nuzur go-code-gen. DO NOT EDIT.

package mapper

import (
	main_entity "github.com/nuzur/nem/core/entity/connection"
	pb "github.com/nuzur/nem/idl/gen"

	"github.com/nuzur/nem/enums"

	"google.golang.org/protobuf/types/known/timestamppb"
)

func ConnectionToProto(e main_entity.Connection) *pb.Connection {
	return &pb.Connection{
		Uuid:           e.UUID.String(),
		Version:        int64(e.Version),
		StoreUuid:      e.StoreUUID.String(),
		EnviormentUuid: e.EnviormentUUID.String(),
		Identifier:     e.Identifier,
		DbType:         pb.ConnectionDbType(e.DbType),
		DbTypeConfig:   DbTypeConfigToProto(e.DbTypeConfig),
		DbVersion:      e.DbVersion,
		Type:           pb.ConnectionType(e.Type),
		TypeConfig:     ConnectionTypeConfigToProto(e.TypeConfig),
		Status:         pb.ConnectionStatus(e.Status),
		CreatedAt:      timestamppb.New(e.CreatedAt),
		UpdatedAt:      timestamppb.New(e.UpdatedAt),
		CreatedByUuid:  e.CreatedByUUID.String(),
		UpdatedByUuid:  e.UpdatedByUUID.String(),
	}
}

func ConnectionSliceToProto(es []main_entity.Connection) []*pb.Connection {
	res := []*pb.Connection{}
	for _, e := range es {
		res = append(res, ConnectionToProto(e))
	}
	return res
}

func ConnectionFromProto(m *pb.Connection) main_entity.Connection {
	if m == nil {
		return main_entity.Connection{}
	}
	return main_entity.Connection{
		UUID:           StringToUUID(m.GetUuid()),
		Version:        int64(m.GetVersion()),
		StoreUUID:      StringToUUID(m.GetStoreUuid()),
		EnviormentUUID: StringToUUID(m.GetEnviormentUuid()),
		Identifier:     m.GetIdentifier(),
		DbType:         enums.ConnectionDbType(m.GetDbType()),
		DbTypeConfig:   DbTypeConfigFromProto(m.GetDbTypeConfig()),
		DbVersion:      m.GetDbVersion(),
		Type:           enums.ConnectionType(m.GetType()),
		TypeConfig:     ConnectionTypeConfigFromProto(m.GetTypeConfig()),
		Status:         enums.ConnectionStatus(m.GetStatus()),
		CreatedAt:      m.GetCreatedAt().AsTime(),
		UpdatedAt:      m.GetUpdatedAt().AsTime(),
		CreatedByUUID:  StringToUUID(m.GetCreatedByUuid()),
		UpdatedByUUID:  StringToUUID(m.GetUpdatedByUuid()),
	}
}

func ConnectionSliceFromProto(es []*pb.Connection) []main_entity.Connection {
	if es == nil {
		return []main_entity.Connection{}
	}
	res := []main_entity.Connection{}
	for _, e := range es {
		res = append(res, ConnectionFromProto(e))
	}
	return res
}
