// Code generated by nuzur go-code-gen. DO NOT EDIT.

package mapper

import (
	main_entity "github.com/nuzur/nem/core/entity/extension"
	pb "github.com/nuzur/nem/idl/gen"

	"github.com/guregu/null/v6"

	"github.com/nuzur/nem/enums"

	"encoding/json"

	"google.golang.org/protobuf/types/known/timestamppb"
)

func ExtensionToProto(e main_entity.Extension) *pb.Extension {
	return &pb.Extension{
		Uuid:              e.UUID.String(),
		Version:           int64(e.Version),
		Identifier:        e.Identifier,
		DisplayName:       e.DisplayName.ValueOrZero(),
		DisplayAuthorName: e.DisplayAuthorName.ValueOrZero(),
		Description:       e.Description.ValueOrZero(),
		Url:               e.URL.ValueOrZero(),
		Verified:          e.Verified,
		Repository:        e.Repository,
		ExtensionType:     pb.ExtensionType(e.ExtensionType),
		Tags:              string(e.Tags),
		Pro:               e.Pro,
		Public:            e.Public,
		Visibility:        VisibilitySliceToProto(e.Visibility),
		Status:            pb.ExtensionStatus(e.Status),
		OwnerUuid:         e.OwnerUUID.String(),
		CreatedAt:         timestamppb.New(e.CreatedAt),
		UpdatedAt:         timestamppb.New(e.UpdatedAt),
		CreatedByUuid:     e.CreatedByUUID.String(),
		UpdatedByUuid:     e.UpdatedByUUID.String(),
	}
}

func ExtensionSliceToProto(es []main_entity.Extension) []*pb.Extension {
	res := []*pb.Extension{}
	for _, e := range es {
		res = append(res, ExtensionToProto(e))
	}
	return res
}

func ExtensionFromProto(m *pb.Extension) main_entity.Extension {
	if m == nil {
		return main_entity.Extension{}
	}
	return main_entity.Extension{
		UUID:              StringToUUID(m.GetUuid()),
		Version:           int64(m.GetVersion()),
		Identifier:        m.GetIdentifier(),
		DisplayName:       null.StringFrom(m.DisplayName),
		DisplayAuthorName: null.StringFrom(m.DisplayAuthorName),
		Description:       null.StringFrom(m.Description),
		URL:               null.StringFrom(m.Url),
		Verified:          m.GetVerified(),
		Repository:        m.GetRepository(),
		ExtensionType:     enums.ExtensionType(m.GetExtensionType()),
		Tags:              json.RawMessage([]byte(m.GetTags())),
		Pro:               m.GetPro(),
		Public:            m.GetPublic(),
		Visibility:        VisibilitySliceFromProto(m.GetVisibility()),
		Status:            enums.ExtensionStatus(m.GetStatus()),
		OwnerUUID:         StringToUUID(m.GetOwnerUuid()),
		CreatedAt:         m.GetCreatedAt().AsTime(),
		UpdatedAt:         m.GetUpdatedAt().AsTime(),
		CreatedByUUID:     StringToUUID(m.GetCreatedByUuid()),
		UpdatedByUUID:     StringToUUID(m.GetUpdatedByUuid()),
	}
}

func ExtensionSliceFromProto(es []*pb.Extension) []main_entity.Extension {
	if es == nil {
		return []main_entity.Extension{}
	}
	res := []main_entity.Extension{}
	for _, e := range es {
		res = append(res, ExtensionFromProto(e))
	}
	return res
}
