// Code generated by nuzur go-code-gen. DO NOT EDIT.

package mapper

import (
	main_entity "github.com/nuzur/nem/core/entity/field_type_config"
	pb "github.com/nuzur/nem/idl/gen"

	"encoding/json"
)

func FieldTypeConfigToProto(e main_entity.FieldTypeConfig) *pb.FieldTypeConfig {
	return &pb.FieldTypeConfig{
		Uuid:      string(e.UUID),
		Integer:   FieldTypeIntegerConfigToProto(e.Integer),
		Float:     FieldTypeFloatConfigToProto(e.Float),
		Decimal:   FieldTypeDecimalConfigToProto(e.Decimal),
		Boolean:   string(e.Boolean),
		Char:      FieldTypeCharConfigToProto(e.Char),
		Varchar:   FieldTypeVarcharConfigToProto(e.Varchar),
		Text:      FieldTypeTextConfigToProto(e.Text),
		Encrypted: FieldTypeEncryptedConfigToProto(e.Encrypted),
		Email:     FieldTypeEmailConfigToProto(e.Email),
		Phone:     FieldTypePhoneConfigToProto(e.Phone),
		Url:       FieldTypeURLConfigToProto(e.URL),
		Location:  string(e.Location),
		Color:     string(e.Color),
		RichText:  string(e.RichText),
		Code:      string(e.Code),
		Markdown:  string(e.Markdown),
		File:      FieldTypeFileConfigToProto(e.File),
		Image:     FieldTypeFileConfigToProto(e.Image),
		Video:     FieldTypeFileConfigToProto(e.Video),
		Audio:     FieldTypeFileConfigToProto(e.Audio),
		Enum:      FieldTypeEnumConfigToProto(e.Enum),
		Json:      FieldTypeJSONConfigToProto(e.JSON),
		Array:     FieldTypeArrayConfigToProto(e.Array),
		Date:      FieldTypeDateConfigToProto(e.Date),
		Datetime:  FieldTypeDatetimeConfigToProto(e.Datetime),
		Time:      string(e.Time),
		Slug:      FieldTypeSlugConfigToProto(e.Slug),
	}
}

func FieldTypeConfigSliceToProto(es []main_entity.FieldTypeConfig) []*pb.FieldTypeConfig {
	res := []*pb.FieldTypeConfig{}
	for _, e := range es {
		res = append(res, FieldTypeConfigToProto(e))
	}
	return res
}

func FieldTypeConfigFromProto(m *pb.FieldTypeConfig) main_entity.FieldTypeConfig {
	if m == nil {
		return main_entity.FieldTypeConfig{}
	}
	return main_entity.FieldTypeConfig{
		UUID:      json.RawMessage([]byte(m.GetUuid())),
		Integer:   FieldTypeIntegerConfigFromProto(m.GetInteger()),
		Float:     FieldTypeFloatConfigFromProto(m.GetFloat()),
		Decimal:   FieldTypeDecimalConfigFromProto(m.GetDecimal()),
		Boolean:   json.RawMessage([]byte(m.GetBoolean())),
		Char:      FieldTypeCharConfigFromProto(m.GetChar()),
		Varchar:   FieldTypeVarcharConfigFromProto(m.GetVarchar()),
		Text:      FieldTypeTextConfigFromProto(m.GetText()),
		Encrypted: FieldTypeEncryptedConfigFromProto(m.GetEncrypted()),
		Email:     FieldTypeEmailConfigFromProto(m.GetEmail()),
		Phone:     FieldTypePhoneConfigFromProto(m.GetPhone()),
		URL:       FieldTypeURLConfigFromProto(m.GetUrl()),
		Location:  json.RawMessage([]byte(m.GetLocation())),
		Color:     json.RawMessage([]byte(m.GetColor())),
		RichText:  json.RawMessage([]byte(m.GetRichText())),
		Code:      json.RawMessage([]byte(m.GetCode())),
		Markdown:  json.RawMessage([]byte(m.GetMarkdown())),
		File:      FieldTypeFileConfigFromProto(m.GetFile()),
		Image:     FieldTypeFileConfigFromProto(m.GetImage()),
		Video:     FieldTypeFileConfigFromProto(m.GetVideo()),
		Audio:     FieldTypeFileConfigFromProto(m.GetAudio()),
		Enum:      FieldTypeEnumConfigFromProto(m.GetEnum()),
		JSON:      FieldTypeJSONConfigFromProto(m.GetJson()),
		Array:     FieldTypeArrayConfigFromProto(m.GetArray()),
		Date:      FieldTypeDateConfigFromProto(m.GetDate()),
		Datetime:  FieldTypeDatetimeConfigFromProto(m.GetDatetime()),
		Time:      json.RawMessage([]byte(m.GetTime())),
		Slug:      FieldTypeSlugConfigFromProto(m.GetSlug()),
	}
}

func FieldTypeConfigSliceFromProto(es []*pb.FieldTypeConfig) []main_entity.FieldTypeConfig {
	if es == nil {
		return []main_entity.FieldTypeConfig{}
	}
	res := []main_entity.FieldTypeConfig{}
	for _, e := range es {
		res = append(res, FieldTypeConfigFromProto(e))
	}
	return res
}
