// Code generated by nuzur go-code-gen. DO NOT EDIT.

package mapper

import (
	main_entity "github.com/nuzur/nem/core/entity/project_extension"
	pb "github.com/nuzur/nem/idl/gen"

	"github.com/guregu/null/v6"

	"github.com/nuzur/nem/enums"

	"google.golang.org/protobuf/types/known/timestamppb"
)

func ProjectExtensionToProto(e main_entity.ProjectExtension) *pb.ProjectExtension {
	return &pb.ProjectExtension{
		Uuid:                      e.UUID.String(),
		ExtensionUuid:             e.ExtensionUUID.String(),
		ExtensionVersionUuid:      e.ExtensionVersionUUID.String(),
		ConfigurationEntityValues: e.ConfigurationEntityValues.ValueOrZero(),
		Blocking:                  e.Blocking,
		Status:                    pb.ProjectExtensionStatus(e.Status),
		CreatedAt:                 timestamppb.New(e.CreatedAt),
		UpdatedAt:                 timestamppb.New(e.UpdatedAt),
		CreatedByUuid:             e.CreatedByUUID.String(),
		UpdatedByUuid:             e.UpdatedByUUID.String(),
	}
}

func ProjectExtensionSliceToProto(es []main_entity.ProjectExtension) []*pb.ProjectExtension {
	res := []*pb.ProjectExtension{}
	for _, e := range es {
		res = append(res, ProjectExtensionToProto(e))
	}
	return res
}

func ProjectExtensionFromProto(m *pb.ProjectExtension) main_entity.ProjectExtension {
	if m == nil {
		return main_entity.ProjectExtension{}
	}
	return main_entity.ProjectExtension{
		UUID:                      StringToUUID(m.GetUuid()),
		ExtensionUUID:             StringToUUID(m.GetExtensionUuid()),
		ExtensionVersionUUID:      StringToUUID(m.GetExtensionVersionUuid()),
		ConfigurationEntityValues: null.StringFrom(m.ConfigurationEntityValues),
		Blocking:                  m.GetBlocking(),
		Status:                    enums.ProjectExtensionStatus(m.GetStatus()),
		CreatedAt:                 m.GetCreatedAt().AsTime(),
		UpdatedAt:                 m.GetUpdatedAt().AsTime(),
		CreatedByUUID:             StringToUUID(m.GetCreatedByUuid()),
		UpdatedByUUID:             StringToUUID(m.GetUpdatedByUuid()),
	}
}

func ProjectExtensionSliceFromProto(es []*pb.ProjectExtension) []main_entity.ProjectExtension {
	if es == nil {
		return []main_entity.ProjectExtension{}
	}
	res := []main_entity.ProjectExtension{}
	for _, e := range es {
		res = append(res, ProjectExtensionFromProto(e))
	}
	return res
}
