// Code generated by nuzur go-code-gen. DO NOT EDIT.

package mapper

import (
	main_entity "github.com/nuzur/nem/core/entity/project_version"
	pb "github.com/nuzur/nem/idl/gen"

	"github.com/nuzur/nem/enums"

	"google.golang.org/protobuf/types/known/timestamppb"
)

func ProjectVersionToProto(e main_entity.ProjectVersion) *pb.ProjectVersion {
	return &pb.ProjectVersion{
		Uuid:            e.UUID.String(),
		Version:         int64(e.Version),
		Identifier:      e.Identifier,
		Description:     e.Description,
		ProjectUuid:     e.ProjectUUID.String(),
		Entities:        EntitySliceToProto(e.Entities),
		Relationships:   RelationshipSliceToProto(e.Relationships),
		Enums:           EnumSliceToProto(e.Enums),
		Services:        ServiceSliceToProto(e.Services),
		BaseVersionUuid: StringFromUUIDPtr(e.BaseVersionUUID),
		ReviewStatus:    pb.ProjectVersionReviewStatus(e.ReviewStatus),
		Deployments:     ProjectVersionDeploymentSliceToProto(e.Deployments),
		Status:          pb.ProjectVersionStatus(e.Status),
		CreatedAt:       timestamppb.New(e.CreatedAt),
		UpdatedAt:       timestamppb.New(e.UpdatedAt),
		CreatedByUuid:   e.CreatedByUUID.String(),
		UpdatedByUuid:   e.UpdatedByUUID.String(),
	}
}

func ProjectVersionSliceToProto(es []main_entity.ProjectVersion) []*pb.ProjectVersion {
	res := []*pb.ProjectVersion{}
	for _, e := range es {
		res = append(res, ProjectVersionToProto(e))
	}
	return res
}

func ProjectVersionFromProto(m *pb.ProjectVersion) main_entity.ProjectVersion {
	if m == nil {
		return main_entity.ProjectVersion{}
	}
	return main_entity.ProjectVersion{
		UUID:            StringToUUID(m.GetUuid()),
		Version:         int64(m.GetVersion()),
		Identifier:      m.GetIdentifier(),
		Description:     m.GetDescription(),
		ProjectUUID:     StringToUUID(m.GetProjectUuid()),
		Entities:        EntitySliceFromProto(m.GetEntities()),
		Relationships:   RelationshipSliceFromProto(m.GetRelationships()),
		Enums:           EnumSliceFromProto(m.GetEnums()),
		Services:        ServiceSliceFromProto(m.GetServices()),
		BaseVersionUUID: StringToUUIDPtr(m.GetBaseVersionUuid()),
		ReviewStatus:    enums.ProjectVersionReviewStatus(m.GetReviewStatus()),
		Deployments:     ProjectVersionDeploymentSliceFromProto(m.GetDeployments()),
		Status:          enums.ProjectVersionStatus(m.GetStatus()),
		CreatedAt:       m.GetCreatedAt().AsTime(),
		UpdatedAt:       m.GetUpdatedAt().AsTime(),
		CreatedByUUID:   StringToUUID(m.GetCreatedByUuid()),
		UpdatedByUUID:   StringToUUID(m.GetUpdatedByUuid()),
	}
}

func ProjectVersionSliceFromProto(es []*pb.ProjectVersion) []main_entity.ProjectVersion {
	if es == nil {
		return []main_entity.ProjectVersion{}
	}
	res := []main_entity.ProjectVersion{}
	for _, e := range es {
		res = append(res, ProjectVersionFromProto(e))
	}
	return res
}
