// Code generated by nuzur go-code-gen. DO NOT EDIT.

package mapper

import (
	main_entity "github.com/nuzur/nem/core/entity/user_connection_execution"
	pb "github.com/nuzur/nem/idl/gen"

	"github.com/nuzur/nem/enums"

	"github.com/guregu/null/v6"

	"google.golang.org/protobuf/types/known/timestamppb"
)

func UserConnectionExecutionToProto(e main_entity.UserConnectionExecution) *pb.UserConnectionExecution {
	return &pb.UserConnectionExecution{
		Uuid:          e.UUID.String(),
		Status:        pb.UserConnectionExecutionStatus(e.Status),
		ResultsPath:   e.ResultsPath.ValueOrZero(),
		NumResults:    int64(e.NumResults),
		StartedAt:     timestamppb.New(e.StartedAt.ValueOrZero()),
		FinishedAt:    timestamppb.New(e.FinishedAt.ValueOrZero()),
		EstimatedTime: e.EstimatedTime.ValueOrZero(),
		UserMsg:       e.UserMsg.ValueOrZero(),
	}
}

func UserConnectionExecutionSliceToProto(es []main_entity.UserConnectionExecution) []*pb.UserConnectionExecution {
	res := []*pb.UserConnectionExecution{}
	for _, e := range es {
		res = append(res, UserConnectionExecutionToProto(e))
	}
	return res
}

func UserConnectionExecutionFromProto(m *pb.UserConnectionExecution) main_entity.UserConnectionExecution {
	if m == nil {
		return main_entity.UserConnectionExecution{}
	}
	return main_entity.UserConnectionExecution{
		UUID:          StringToUUID(m.GetUuid()),
		Status:        enums.UserConnectionExecutionStatus(m.GetStatus()),
		ResultsPath:   null.StringFrom(m.ResultsPath),
		NumResults:    int64(m.GetNumResults()),
		StartedAt:     null.TimeFrom(m.GetStartedAt().AsTime()),
		FinishedAt:    null.TimeFrom(m.GetFinishedAt().AsTime()),
		EstimatedTime: null.StringFrom(m.EstimatedTime),
		UserMsg:       null.StringFrom(m.UserMsg),
	}
}

func UserConnectionExecutionSliceFromProto(es []*pb.UserConnectionExecution) []main_entity.UserConnectionExecution {
	if es == nil {
		return []main_entity.UserConnectionExecution{}
	}
	res := []main_entity.UserConnectionExecution{}
	for _, e := range es {
		res = append(res, UserConnectionExecutionFromProto(e))
	}
	return res
}
